### ISSUE TITLE
Crash in test

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#1032]
```
12-11 18:52:25.214: E/MonitoringInstr(7068): java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at android.graphics.Path.setFillType(Path.java:260)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:66)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:86)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:61)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:35)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:61)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:43)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:230)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:192)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:393)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.samples.views.FilmStripView.setComposition(FilmStripView.kt:31)
12-11 18:52:25.214: E/MonitoringInstr(7068): 	at com.airbnb.lottie.samples.SnapshotTestActivity$snapshotFilmstrip$$inlined$suspendCoroutine$lambda$1.run(SnapshotTestActivity.kt:48)
```
Lamoda-anim_favourites

**Comment by NewOrin** [comment]
I have this crash in my project, can u tell me how to solve this? 
It's the json file's problem or lottie bug? 
thx.
