### ISSUE TITLE
Sample app crashes 

### ISSUE THREAD

**Issue by VitaminPSG** [airbnb/lottie-android#1078]
`Stack trace: `
2019-01-06 21:38:03.568 4519-4519/com.airbnb.lottie E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie, PID: 4519
    java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.Collections$EmptyList.get(Collections.java:4502)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getCurrentKeyframe(BaseKeyframeAnimation.java:86)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:56)
        at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:451)
        at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:117)
        at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:129)
        at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:105)
        at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
        at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:155)
        at com.airbnb.lottie.LottieDrawable.setFrame(LottieDrawable.java:555)
        at com.airbnb.lottie.LottieDrawable.setProgress(LottieDrawable.java:574)
        at com.airbnb.lottie.LottieDrawable.addValueCallback(LottieDrawable.java:793)
        at com.airbnb.lottie.LottieAnimationView.addValueCallback(LottieAnimationView.java:662)
        at com.airbnb.lottie.samples.DynamicActivity.setupValueCallbacks(DynamicActivity.kt:59)
        at com.airbnb.lottie.samples.DynamicActivity.access$setupValueCallbacks(DynamicActivity.kt:19)
        at com.airbnb.lottie.samples.DynamicActivity$onCreate$5.run(DynamicActivity.kt:53)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by gpeal** [comment]
@VitaminPSG Can you include repro steps and the animation that caused this?

**Comment by VitaminPSG** [comment]
@gpeal Steps: Open app -> choose `Dynamic Properties`
this is video: https://vimeo.com/user93762018/review/310664567/c7b8a3b1e2
**lottie_fileName**="AndroidWave.json"

**Comment by gpeal** [comment]
@VitaminPSG The link 404s

**Comment by gpeal** [comment]
Fixed by #1084
