### ISSUE TITLE
AnimatableIntegerValue on a null object reference

### ISSUE THREAD

**Issue by chienpao** [airbnb/lottie-android#109]
I have encountered a bug when I load my own json file,
I also send my AE file to Airbnb mail, please help to fix the bug, many thanks.
the error log as below,

02-16 11:35:06.965 11133-11326/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                   Process: com.airbnb.lottie, PID: 11133
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                       at com.airbnb.lottie.animatable.AnimatableIntegerValue.<init>(AnimatableIntegerValue.java:27)
                                                       at com.airbnb.lottie.model.Layer.fromJson(Layer.java:88)
                                                       at com.airbnb.lottie.model.LottieComposition.fromJsonSync(LottieComposition.java:145)
                                                       at com.airbnb.lottie.model.LottieComposition.fromInputStream(LottieComposition.java:97)
                                                       at com.airbnb.lottie.model.LottieComposition$FileCompositionLoader.doInBackground(LottieComposition.java:266)
                                                       at com.airbnb.lottie.model.LottieComposition$FileCompositionLoader.doInBackground(LottieComposition.java:254)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by chienpao** [comment]
Excuse me, I just put my json file and AE file here, please check. thanks.
Json file [http://chienpao.com:5000/fbsharing/G4PO4ZR6](url)
AE file [http://chienpao.com:5000/fbsharing/boJwueO4](url)

**Comment by gpeal** [comment]
@chienpao Can you try updating to Lottie 1.0.3 and trying again? It should be fixed.

**Comment by gpeal** [comment]
@chienpao I was successfully able to play this animation on master.

**Comment by chienpao** [comment]
@gpeal thanks for ur help, I will try this.
