### ISSUE TITLE
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieDrawable.recycleBitmaps()' on a null object reference

### ISSUE THREAD

**Issue by 456838** [airbnb/lottie-android#1116]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieDrawable.recycleBitmaps()' on a null object reference
        at com.airbnb.lottie.LottieAnimationView.recycleBitmaps(LottieAnimationView.java:256)
        at com.airbnb.lottie.LottieAnimationView.setImageDrawable(LottieAnimationView.java:176)
        at com.airbnb.lottie.LottieAnimationView.setImageDrawable(LottieAnimationView.java:171)
        at android.widget.ImageView.<init>(ImageView.java:190)
        at android.widget.ImageView.<init>(ImageView.java:171)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:90)
        	... 44 more

onVersion:2.5.6
  @VisibleForTesting void recycleBitmaps() {
    // AppCompatImageView constructor will set the image when set from xml
    // before LottieDrawable has been initialized
    if (lottieDrawable != null) {
      lottieDrawable.recycleBitmaps();
    }
  }

onVersion:2.7.0

  @VisibleForTesting void recycleBitmaps() {
    // AppCompatImageView constructor will set the image when set from xml
    // before LottieDrawable has been initialized
    lottieDrawable.recycleBitmaps();
  }

**Comment by gpeal** [comment]
Lottie 3.0.0-beta1 (beta2 coming out today or tomorrow) no longer has this code path.
