### ISSUE TITLE
Process 'command 'E:\AndroidStudio\jre\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by wahyip** [airbnb/lottie-android#1139]
After adding implementation 'com.airbnb.android:lottie:2.3.1' not able to compile the project the throw below error Process 'command 'E:\AndroidStudio\jre\bin\java.exe'' finished with non-zero exit value 1

Details Log

`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDesugarForSoonest_googleplayDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@E:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@E:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
	at com.android.build.gradle.internal.transforms.DesugarTransform.transform(DesugarTransform.java:236)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 49 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@E:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
	at com.android.build.gradle.internal.transforms.DesugarTransform.transform(DesugarTransform.java:230)
	... 52 more
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@E:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@E:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
	at com.android.build.gradle.internal.transforms.DesugarTransform.lambda$processNonCachedOnes$3(DesugarTransform.java:316)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'E:\AndroidStudio\jre\bin\java.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
	... 6 more

`

build.gradle:
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "..."
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 11
        versionName "2.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath = true
            }
        }
        multiDexEnabled true
        ndk {
            abiFilters 'armeabi' , 'x86', 'armeabi-v7a', 'x86_64', 'mips', 'mips64'
        }
    }

    android {
        dexOptions {
            incremental true
            preDexLibraries = false
            javaMaxHeapSize "4g"
        }
        lintOptions{
            checkReleaseBuilds false
            abortOnError false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

    }

    flavorDimensions "soonest"
    productFlavors {
        soonest_service {
            dimension "soonest"
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "service"]
        }
        soonest_googleplay {
            dimension "soonest"
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "googleplay"]
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'typedefs.txt'
        exclude 'META-INF/rxjava.properties'
    }

    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }

    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation files('libs/jcore-android-1.2.1.jar')
    implementation files('libs/jpush-android-3.1.3.jar')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.android.support:multidex:1.0.0'
    compile('com.android.support:design:26.1.0') {
        exclude module: 'support-annotations'
    }
    compile files('libs/tbs_sdk_thirdapp_v3.6.0.1310_43612_sharewithdownload_withoutGame_obfs_20180706_163319.jar')
    compile 'com.alibaba:fastjson:1.1.53.android'
    compile 'com.joooonho:selectableroundedimageview:1.0.1'
    compile project(':simon_core')
    implementation 'com.chenenyu.router:router:1.5.2'

    annotationProcessor 'com.chenenyu.router:compiler:1.5.1'
    api 'com.tbruyelle.rxpermissions:rxpermissions:0.9.3@aar'
    implementation 'cat.ereza:customactivityoncrash:1.5.0'
    compile 'com.tencent.bugly:crashreport:latest.release' 
    compile 'com.tencent.bugly:nativecrashreport:latest.release' 
    compile project(path: ':indexlib')

    compile project(':MPChartLib')
    compile project(':smallchart')
    compile project(':SwipeMenuRecyclerViewlibrary')
    implementation files('libs/asmack-android-8-4.0.7.jar')
    compile 'com.github.todou:appbarspring:1.0.6'
    compile 'com.nineoldandroids:library:2.4.0'

    implementation 'top.zibin:Luban:1.1.8'
    compile project(path: ':pullzoom')
    compile project(path: ':ncalendar')
    compile project(path: ':ganttchart')
    compile project(':floatwindow')
    compile project(path: ':imageedit')
    compile 'com.airbnb.android:lottie:2.3.1'
}
`

**Comment by wahyip** [comment]
oh~ it's v7 jar repeat~ 
    implementation ('com.airbnb.android:lottie:2.3.1'){
        exclude module: 'com.android.support:appcompat-v7'
        exclude module: 'com.android.support:appcompat-v4'
    }

**Comment by wahyip** [comment]
> After adding implementation 'com.airbnb.android:lottie:2.3.1' not able to compile the project the throw below error Process 'command 'E:\AndroidStudio\jre\bin\java.exe'' finished with non-zero exit value 1
> 
> Details Log
> 
> `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDesugarForSoonest_googleplayDebug'.
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
> at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
> at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
> at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
> at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
> at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
> at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
> at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
> at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
> at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
> at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
> at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
> at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
> at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
> at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
> at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
> at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
> at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
> at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
> at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
> at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
> at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
> at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@e:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
> at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
> at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
> at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
> at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
> at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
> ... 33 more
> Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@e:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
> at com.android.build.gradle.internal.transforms.DesugarTransform.transform(DesugarTransform.java:236)
> at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
> at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
> at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
> ... 49 more
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@e:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
> at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
> at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
> at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
> at com.android.build.gradle.internal.transforms.DesugarTransform.transform(DesugarTransform.java:230)
> ... 52 more
> Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@e:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
> at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@e:\Erp\app\build\intermediates\tmp\desugar_args5569457885528010798}
> at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
> at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
> at com.android.build.gradle.internal.transforms.DesugarTransform.lambda$processNonCachedOnes$3(DesugarTransform.java:316)
> at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
> ... 4 more
> Caused by: org.gradle.process.internal.ExecException: Process 'command 'E:\AndroidStudio\jre\bin\java.exe'' finished with non-zero exit value 1
> at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
> at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
> ... 6 more
> 
> `
> 
> build.gradle:
> `apply plugin: 'com.android.application'
> 
> android {
> compileSdkVersion 26
> buildToolsVersion '26.0.2'
> defaultConfig {
> applicationId "..."
> minSdkVersion 17
> targetSdkVersion 26
> versionCode 11
> versionName "2.0"
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> javaCompileOptions {
> annotationProcessorOptions {
> includeCompileClasspath = true
> }
> }
> multiDexEnabled true
> ndk {
> abiFilters 'armeabi' , 'x86', 'armeabi-v7a', 'x86_64', 'mips', 'mips64'
> }
> }
> 
> ```
> android {
>     dexOptions {
>         incremental true
>         preDexLibraries = false
>         javaMaxHeapSize "4g"
>     }
>     lintOptions{
>         checkReleaseBuilds false
>         abortOnError false
>     }
> }
> 
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>     }
> 
> }
> 
> flavorDimensions "soonest"
> productFlavors {
>     soonest_service {
>         dimension "soonest"
>         manifestPlaceholders = [UMENG_CHANNEL_VALUE: "service"]
>     }
>     soonest_googleplay {
>         dimension "soonest"
>         manifestPlaceholders = [UMENG_CHANNEL_VALUE: "googleplay"]
>     }
> }
> 
> packagingOptions {
>     exclude 'META-INF/LICENSE'
>     exclude 'META-INF/NOTICE'
>     exclude 'META-INF/LICENSE.txt'
>     exclude 'META-INF/NOTICE.txt'
>     exclude 'META-INF/services/javax.annotation.processing.Processor'
>     exclude 'typedefs.txt'
>     exclude 'META-INF/rxjava.properties'
> }
> 
> sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }
> 
> compileOptions {
>     targetCompatibility 1.8
>     sourceCompatibility 1.8
> }
> ```
> }
> 
> dependencies {
> implementation fileTree(include: ['*.jar'], dir: 'libs')
> implementation 'com.android.support:appcompat-v7:26.1.0'
> implementation 'com.android.support.constraint:constraint-layout:1.0.2'
> implementation files('libs/jcore-android-1.2.1.jar')
> implementation files('libs/jpush-android-3.1.3.jar')
> testImplementation 'junit:junit:4.12'
> androidTestImplementation 'com.android.support.test🏃1.0.1'
> androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
> compile 'com.android.support:multidex:1.0.0'
> compile('com.android.support:design:26.1.0') {
> exclude module: 'support-annotations'
> }
> compile files('libs/tbs_sdk_thirdapp_v3.6.0.1310_43612_sharewithdownload_withoutGame_obfs_20180706_163319.jar')
> compile 'com.alibaba:fastjson:1.1.53.android'
> compile 'com.joooonho:selectableroundedimageview:1.0.1'
> compile project(':simon_core')
> implementation 'com.chenenyu.router:router:1.5.2'
> 
> ```
> annotationProcessor 'com.chenenyu.router:compiler:1.5.1'
> api 'com.tbruyelle.rxpermissions:rxpermissions:0.9.3@aar'
> implementation 'cat.ereza:customactivityoncrash:1.5.0'
> compile 'com.tencent.bugly:crashreport:latest.release' 
> compile 'com.tencent.bugly:nativecrashreport:latest.release' 
> compile project(path: ':indexlib')
> 
> compile project(':MPChartLib')
> compile project(':smallchart')
> compile project(':SwipeMenuRecyclerViewlibrary')
> implementation files('libs/asmack-android-8-4.0.7.jar')
> compile 'com.github.todou:appbarspring:1.0.6'
> compile 'com.nineoldandroids:library:2.4.0'
> 
> implementation 'top.zibin:Luban:1.1.8'
> compile project(path: ':pullzoom')
> compile project(path: ':ncalendar')
> compile project(path: ':ganttchart')
> compile project(':floatwindow')
> compile project(path: ':imageedit')
> compile 'com.airbnb.android:lottie:2.3.1'
> ```
> }
> `
