### ISSUE TITLE
Version 3.0.0 NullPointerException on some Device

### ISSUE THREAD

**Issue by OwnLeiX** [airbnb/lottie-android#1171]
We updated Lottie Animation Version to 3.0.0, find there is some Exception on some devices.
1.Sansum S7 Android 7.0
2.Nubia X6 Android 4.4.2

And Here's the log.
03-29 11:51:21.659 22169-22169/com.*****.*****E/*******.CaughtExp: java.lang.NullPointerException
        at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:96)
        at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:29)
        at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:84)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:31)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:65)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:36)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:31)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:65)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:54)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:57)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:245)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:207)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:406)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:66)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:63)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:150)
        at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:137)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5137)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by gpeal** [comment]
@OwnLeiX Can you attach your aep file? Are there any steps to reproduce this?

**Comment by gpeal** [comment]
@OwnLeiX Something isn't right from your stack trace. It's not possible to get a NullPointerException on the line in your stack trace
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java#L96

**Comment by gpeal** [comment]
I'm going to close this for now. The stack trace doesn't line up with production code and it hasn't been reported by anybody else yet. Feel free to reopen if you have more info.
