### ISSUE TITLE
why lottie exception doesn't point to my own code that invoked lottie anim?

### ISSUE THREAD

**Issue by jhwsx** [airbnb/lottie-android#1195]
I have used lottie anim in my app vastly, but the problem that I faced is a lot of OOMs, which is very   frustrating.
The log collected by google vitals or U-App is the following:
```text
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
	at com.airbnb.lottie.b.b.a(Unknown Source)
	at com.airbnb.lottie.f.b(Unknown Source)
	at com.airbnb.lottie.c.c.c.f(Unknown Source)
	at com.airbnb.lottie.c.c.c.b(Unknown Source)
	at com.airbnb.lottie.c.c.a.a(Unknown Source)
	at com.airbnb.lottie.c.c.b.b(Unknown Source)
	at com.airbnb.lottie.c.c.a.a(Unknown Source)
	at com.airbnb.lottie.c.c.b.b(Unknown Source)
	at com.airbnb.lottie.c.c.a.a(Unknown Source)
	at com.airbnb.lottie.f.draw(Unknown Source)
	at android.widget.ImageView.onDraw(ImageView.java:1058)
	at android.view.View.draw(View.java:15410)
	at android.view.View.buildDrawingCache(View.java:14617)
	at android.view.View.getDisplayList(View.java:14277)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.support.constraint.ConstraintLayout.dispatchDraw(Unknown Source)
	at android.view.View.getDisplayList(View.java:14296)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.getDisplayList(View.java:14296)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.draw(View.java:15413)
	at android.view.View.getDisplayList(View.java:14301)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.draw(View.java:15413)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at android.view.View.getDisplayList(View.java:14301)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.getDisplayList(View.java:14296)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.getDisplayList(View.java:14296)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.getDisplayList(View.java:14296)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.View.draw(View.java:15124)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
	at android.view.View.draw(View.java:15413)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2583)
	at android.view.View.getDisplayList(View.java:14301)
	at android.view.View.getDisplayList(View.java:14343)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2777)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2643)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
	at android.view.Choreographer.doCallbacks(Choreographer.java:614)
	at android.view.Choreographer.doFrame(Choreographer.java:584)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```
In fact, I have read the log carefully, but I cannot find any line of my own code, which makes it diffult for me to pinpoint the root cause.

**Comment by gpeal** [comment]
@jhwsx Do your lottie animations have images?

**Comment by jhwsx** [comment]
yes，they do.

**Comment by jhwsx** [comment]
But I do not think that whether they have images is the point of this issue.

**Comment by gpeal** [comment]
@jhwsx It is because your app ran out of memory trying to allocate space for the images in your animations. How many images do you have and how large are they? Can you attach a zip with your animation?

**Comment by jhwsx** [comment]
I choose three of them, which have more images:
- [sweep.zip](https://github.com/airbnb/lottie-android/files/3150418/sweep.zip)
- [notification.zip](https://github.com/airbnb/lottie-android/files/3150416/notification.zip)
- [battery.zip](https://github.com/airbnb/lottie-android/files/3150413/battery.zip)

Could you please help me detect something abnormal?

**Comment by jhwsx** [comment]
Thank you.
