### ISSUE TITLE
App crash on android 6.0.1

### ISSUE THREAD

**Issue by malinkang** [airbnb/lottie-android#1202]
My Code

```java
class PlayerActivity : MyActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_player)
        var item = intent.getParcelableExtra("item") as CenterPopup

        ivClose.setOnClickListener {
            finish()
        }

        animationView.setOnClickListener {
            WebViewFragment.toWeb(this, item.url)
            finish()
        }
        try {
            showLoading()
            LottieCompositionFactory.fromUrl(this, item.source)
                    .addListener {
                        hideLoading()
                        animationView.setComposition(it)
                        animationView.playAnimation()
                    }.addFailureListener {
                        hideLoading()
                        it.printStackTrace()
                    }
        } catch (e: Exception) {
            finish()
        }
    }
}
```

My log

```
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
    at android.view.View.updateDisplayListIfDirty(View.java:15237)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.updateDisplayListIfDirty(View.java:15237)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.draw(View.java:16248)
    at android.view.View.updateDisplayListIfDirty(View.java:15242)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.draw(View.java:16248)
    at android.view.View.updateDisplayListIfDirty(View.java:15242)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.updateDisplayListIfDirty(View.java:15237)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.draw(View.java:16248)
    at android.view.View.updateDisplayListIfDirty(View.java:15242)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.updateDisplayListIfDirty(View.java:15237)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.updateDisplayListIfDirty(View.java:15237)
    at android.view.View.draw(View.java:16015)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
    at android.view.View.draw(View.java:16248)
    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2827)
    at android.view.View.updateDisplayListIfDirty(View.java:15242)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2662)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2481)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2091)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1127)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6156)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
    at android.view.Choreographer.doCallbacks(Choreographer.java:704)
    at android.view.Choreographer.doFrame(Choreographer.java:640)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:878)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5619)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

```

**Comment by gpeal** [comment]
@malinkang Are you sure this is from Lottie? There is no Lottie code in your stack trace?
