### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by hbzhzw** [airbnb/lottie-android#1212]
may be huawei device error, but if we can do something to avoid it ....

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at android.view.HwNsdImpl.checkAdBlock(HwNsdImpl.java:750)
at android.view.View.skipInvalidate(View.java:12713)
at android.view.View.invalidateInternal(View.java:12800)
at android.view.View.invalidate(View.java:12790)
at android.view.View.invalidate(View.java:12774)
at android.widget.ImageView.invalidateDrawable(ImageView.java:248)
at com.airbnb.lottie.LottieAnimationView.invalidateDrawable(SourceFile:192)
at com.airbnb.lottie.LottieDrawable.invalidateSelf(SourceFile:261)
at com.airbnb.lottie.model.layer.BaseLayer.invalidateSelf(SourceFile:158)
at com.airbnb.lottie.model.layer.BaseLayer.onValueChanged(SourceFile:121)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.notifyListeners(SourceFile:60)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(SourceFile:55)
                                                              getValue
at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.setProgress(SourceFile:83)
at com.airbnb.lottie.model.layer.BaseLayer.setProgress(SourceFile:412)
at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(SourceFile:139)
at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(SourceFile:103)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(SourceFile:88)
at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(SourceFile:96)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
at android.view.Choreographer.doCallbacks(Choreographer.java:698)
at android.view.Choreographer.doFrame(Choreographer.java:630)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5659)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by todo-fixme** [comment]
try turning off hardware acceleration

**Comment by gpeal** [comment]
[Here](https://github.com/SivanLiu/HwFrameWorkSource/blob/master/P9_8_0_0/src/main/java/android/view/HwNsdImpl.java#L54) is the closest thing I can find to the Huawei source and fixing that would be totally out of Lottie's control. Hopefully this was just a one time occurrence.
