### ISSUE TITLE
NetworkFetcher:121 NullPointerException

### ISSUE THREAD

**Issue by chenjianping99** [airbnb/lottie-android#1213]
Caused by: java.lang.NullPointerException
        at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:121)
        at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:93)
        at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:62)
        at com.airbnb.lottie.network.NetworkFetcher$1.call(NetworkFetcher.java:49)
        at com.airbnb.lottie.network.NetworkFetcher$1.call(NetworkFetcher.java:47)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by chenjianping99** [comment]
switch (connection.getContentType())    <--------------debug find this line, connection.getContentType() is null
