### ISSUE TITLE
3.0.3 - NullPointerException @ Samsung SM-G930f (Android 7.0，API 24)

### ISSUE THREAD

**Issue by todo-fixme** [airbnb/lottie-android#1220]
device:Samsung SM-G930f (Android 7.0，API 24)
lottie:3.0.2
The problem occurs in the constructor of BaseStrokeContent.java
Like this:widthAnimation = width.createAnimation();
The width is null

--------------------------------------------
[22.zip](https://github.com/airbnb/lottie-android/files/3190662/22.zip)

![image](https://user-images.githubusercontent.com/48200410/57915606-b446b780-78c3-11e9-89f0-c0ff3387c62a.png)
![image](https://user-images.githubusercontent.com/48200410/57915626-c45e9700-78c3-11e9-83c4-06ffb831a35c.png)

ps carsh log：
 java.lang.NullPointerException
  at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:69)
        at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:29)
        at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:84)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:31)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:65)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:36)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:31)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:65)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:54)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:57)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:245)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:207)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:412)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:69)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:66)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:150)
        at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:137)

**Comment by gpeal** [comment]
@todo-fixme Ar eyou sure you are on 3.0.2? That line of code doesn't match the actual source
https://github.com/airbnb/lottie-android/blob/v3.0.2/lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java#L69

**Comment by todo-fixme** [comment]
@gpeal YES! I reformat code ,That line of code doesn't match the actual source
I debug the code , i found that as i say
-----------------------
The problem occurs in the constructor of BaseStrokeContent.java
Like this:widthAnimation = width.createAnimation();
The width is NULL

**Comment by gpeal** [comment]
@todo-fixme What do you mean you reformatted the code? Aren't you using the published artifact? can you make a sample project that reproduces this?

**Comment by todo-fixme** [comment]
@gpeal **tody,update code to v3.0.3**

![image](https://user-images.githubusercontent.com/48200410/58147631-10c42100-7c8e-11e9-9215-1d3f1d90e7c9.png)

**the debug info is shown in the screenshot** 

![image](https://user-images.githubusercontent.com/48200410/58147698-55e85300-7c8e-11e9-84dc-23a6d5ec8576.png)

https://github.com/airbnb/lottie-android/blob/v3.0.3/lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java#L67

so,the bug is same at https://github.com/airbnb/lottie-android/issues/1229

**Comment by todo-fixme** [comment]
@gpeal 

I change the call api , from "setAnimationFromJson(String jsonString)" to “setAnimation(JSONObject json)” in the LottieAnimationView.java 

i don't know why,but it's work.

i guess something wrong when JSONObject  to String by the JsonReader
