### ISSUE TITLE
How to solve OOM problem?

### ISSUE THREAD

**Issue by pangzhaolong** [airbnb/lottie-android#1235]
**Read this or your issue will be closed**

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

**Comment by pangzhaolong** [comment]
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
       at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:115)
       at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:839)
       at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
       at com.airbnb.lottie.model.layer.ImageLayer.getBounds(ImageLayer.java:52)
       at com.airbnb.lottie.model.layer.CompositionLayer.getBounds(CompositionLayer.java:112)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:209)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
       at android.widget.ImageView.onDraw(ImageView.java:1037)
       at android.view.View.draw(View.java:14492)
       at android.view.View.getDisplayList(View.java:13389)
       at android.view.View.getHardwareLayerDisplayList(View.java:13416)
       at android.view.View.getHardwareLayer(View.java:13127)
       at android.view.View.getDisplayList(View.java:13355)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.getDisplayList(View.java:13384)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14495)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13389)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13384)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13384)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13384)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.draw(View.java:14209)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14495)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
       at android.view.View.getDisplayList(View.java:13389)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by gpeal** [comment]
@pangzhaolong Lottie works best when your animation is all vectors. Try and convert any After Effects image layers to shape layers and reduce images as much as possible. Ideally, you'll have 0 images.

**Comment by pangzhaolong** [comment]
> @pangzhaolong Lottie works best when your animation is all vectors. Try and convert any After Effects image layers to shape layers and reduce images as much as possible. Ideally, you'll have 0 images.

Thanks. I will let the UI desinger know about this.
