### ISSUE TITLE
com.airbnb.lottie.model.content.ShapeData.getInitialPoint()' on a null object reference

### ISSUE THREAD

**Issue by shizhongyu** [airbnb/lottie-android#1252]
![image](https://user-images.githubusercontent.com/13025541/59032428-d87d2f00-8898-11e9-9029-339bdbbbbfbe.png)

**Comment by gpeal** [comment]
@shizhongyu Please attach your animation and any repro steps.

**Comment by shizhongyu** [comment]
[sleep (2).txt](https://github.com/airbnb/lottie-android/files/3274662/sleep.2.txt)

**Comment by shizhongyu** [comment]
@gpeal

**Comment by grandstaish** [comment]
We're getting a very similar error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.airbnb.lottie.model.content.ShapeData.getCurves()' on a null object reference
        at com.airbnb.lottie.model.content.ShapeData.interpolateBetween(ShapeData.java:55)
        at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:23)
        at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:11)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
        at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:61)
        at com.airbnb.lottie.animation.content.FillContent.draw(FillContent.java:88)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
```

**Comment by gpeal** [comment]
@shizhongyu @grandstaish Have you upgraded to Lottie 3.0+ (3.0.6 is the latest)?
@shizhongyu Your animation renders fine for me.
@grandstaish The second one is https://github.com/airbnb/lottie-android/issues/1177 and the others might be related.

**Comment by grandstaish** [comment]
Updating lottie fixed the issue 🙈 Thanks @gpeal!

**Comment by gpeal** [comment]
@shizhongyu I'm going to close this because upgrading will likely fix this for you too.

**Comment by bruscantini** [comment]
This sol'n doesn't work if I need to stay on version 2.6.1 for iOS purposes. Any fix without upgrading?
