### ISSUE TITLE
crash in Lottie on Nougat for Lenovo devices

### ISSUE THREAD

**Issue by Shivamgarg1528** [airbnb/lottie-android#1256]
Getting below crash on Android-Nougat for Lenovo devices only

Fatal Exception: java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:66)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
       at com.airbnb.lottie.LottieTask.access$300(LottieTask.java:26)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

Caused by java.lang.IllegalStateException: Expected END_OBJECT but was END_ARRAY
       at android.util.JsonReader.expect(JsonReader.java:310)
       at android.util.JsonReader.endObject(JsonReader.java:301)
       at com.airbnb.lottie.parser.ContentModelParser.parse(ContentModelParser.java:96)
       at com.airbnb.lottie.parser.ShapeGroupParser.parse(ShapeGroupParser.java:30)
       at com.airbnb.lottie.parser.ContentModelParser.parse(ContentModelParser.java:48)
       at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:113)
       at com.airbnb.lottie.parser.LottieCompositionParser.parseAssets(LottieCompositionParser.java:142)
       at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:75)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:229)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:163)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:157)
       at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:129)
       at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:116)
       at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:114)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by gpeal** [comment]
@Shivamgarg1528 Upgrade to 3.0.6. The entire JsonReader has been replaced.
