### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by MrEricChen** [airbnb/lottie-android#1258]
**Reporting an error as soon as it is opened**

log:
java.lang.OutOfMemoryError: Failed to allocate a 12582924 byte allocation with 306820 free bytes and 299KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:114)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:800)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.getBounds(ImageLayer.java:52)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:198)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:190)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:312)
        at android.widget.ImageView.onDraw(ImageView.java:1176)
        at android.view.View.draw(View.java:15382)
        at android.view.View.buildDrawingCacheImpl(View.java:14628)
        at android.view.View.buildDrawingCache(View.java:14490)
        at android.view.View.updateDisplayListIfDirty(View.java:14299)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:15385)
        at android.view.View.updateDisplayListIfDirty(View.java:14318)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14313)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14313)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14313)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14313)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.View.draw(View.java:15110)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.draw(View.java:15385)
        at android.widget.FrameLayout.draw(FrameLayout.java:600)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2841)
        at android.view.View.updateDisplayListIfDirty(View.java:14318)
        at android.view.View.getDisplayList(View.java:14340)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2660)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2482)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1168)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6219)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)

**Comment by gpeal** [comment]
It looks like your app happened to run out of memory when allocating a Bitmap for Lottie but it is highly unlikely that Lottie is the root cause as it does very few allocations, especially in 3.0+.

**Comment by MrEricChen** [comment]
Got it.
Thanks

**Comment by Jiawei1994** [comment]
> Got it.
> Thanks
Hi,How did you solve the problem？
