### ISSUE TITLE
ConcurrentModificationException in the newest version (3.0.1)

### ISSUE THREAD

**Issue by zjfandroid** [airbnb/lottie-android#1262]
# main(1)
java.util.ConcurrentModificationException

1 java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
2 java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
3 java.util.AbstractCollection.finishToArray(AbstractCollection.java:232)
4 java.util.AbstractCollection.toArray(AbstractCollection.java:143)
5 java.util.ArrayList.<init>(ArrayList.java:191)
6 com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:1)
7 com.airbnb.lottie.LottieTask.access$200(LottieTask.java:1)
8 com.airbnb.lottie.LottieTask$1.run(LottieTask.java:4)
9 android.os.Handler.handleCallback(Handler.java:891)
10 android.os.Handler.dispatchMessage(Handler.java:102)
11 android.os.Looper.loop(Looper.java:207)
12 android.app.ActivityThread.main(ActivityThread.java:7539)
13 java.lang.reflect.Method.invoke(Native Method)
14 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
15 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by tyh470075227** [comment]
why close it? I use 2.7.0 version.I has the same crash.


java.util.ConcurrentModificationException
1
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
2
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
3
at java.util.AbstractCollection.finishToArray(AbstractCollection.java:232)
4
at java.util.AbstractCollection.toArray(AbstractCollection.java:143)
5
at java.util.ArrayList.<init>(ArrayList.java:191)
6
at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:151)
7
at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:140)
8
at android.os.Handler.handleCallback(Handler.java:808)
9
at android.os.Handler.dispatchMessage(Handler.java:101)
10
at android.os.Looper.loop(Looper.java:166)

**Comment by stevemelon** [comment]
this bug still exist in version5.2.0

java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:568)
at com.airbnb.lottie.LottieAnimationView$$InternalSyntheticLambda$0$9fe98adb495c4ab24af6fd3c4622b40e76732db750aeef8f69b8407c879af319$0.onResult(LottieAnimationView.java:4)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:148)
at com.airbnb.lottie.LottieTask.lambda$notifyListeners$0(LottieTask.java:136)
at com.airbnb.lottie.LottieTask.$r8$lambda$Rpnx63cLRLCF9DbgjiFM7rp0Vik(LottieTask.java:0)
