### ISSUE TITLE
ANR held mutexes= "mutator lock"(shared held)

### ISSUE THREAD

**Issue by yangjingbo** [airbnb/lottie-android#1269]
I use api "com.airbnb.android:lottie:2.5.1", to run monkey, then ANR hapens

----- pid 5621 at 2019-05-31 04:52:41 -----
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x780d6c18 self=0x7c99814c00
  | sysTid=5621 nice=-10 cgrp=default sched=0/0 handle=0x7d1f7f2548
  | state=R schedstat=( 9410665350249 249412674861 1715843 ) utm=914978 stm=26088 core=6 HZ=100
  | stack=0x7ffc859000-0x7ffc85b000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:410)
  at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:139)
  at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:139)
  at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:139)
  at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:102)
  at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
  at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:94)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
  at android.view.Choreographer.doCallbacks(Choreographer.java:833)
  at android.view.Choreographer.doFrame(Choreographer.java:765)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:201)
  at android.app.ActivityThread.main(ActivityThread.java:6823)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by gpeal** [comment]
@yangjingbo Can you run this with 3.0.6? Lottie doesn't have any mutexes

**Comment by gpeal** [comment]
I'm closing this for now because this was on an old version of Lottie and I think this was more related to general Android deadlock that just happened to be in Lottie code rather than a Lottie one.
