### ISSUE TITLE
buildDrawingCache null pointer exception

### ISSUE THREAD

**Issue by mashahbazi** [airbnb/lottie-android#1317]
Hi
I have two times crash report in my project fabric from lottie library.
the error exception is null pointer exception.
I use lottie version 3.0.1.
this is error stack trace:

`
android.view.View.buildDrawingCache + 13841 (View.java:13841)
com.airbnb.lottie.LottieAnimationView.buildDrawingCache + 821 (LottieAnimationView.java:821)
android.view.View.getDisplayList + 13558 (View.java:13558)
.
.
.
`

the crash is in android 4.4.2 and it have enough free memory and disk size.
consider that I checked it it android 4.4.2 and it work good

**Comment by gpeal** [comment]
If this is extremely rare and only on 4.4.2, it may be an oem specific platform bug. I likely won't have time to spend on this myself but it you would like to and find a fix, I would accept a PR.

**Comment by mashahbazi** [comment]
@gpeal So if you don't have time fix it why you close the issue. Closing issue meaning that it solved.

**Comment by gpeal** [comment]
@mashahbazi Unfortunately, nobody else works on Lottie issues so I pretty aggressively close issues to prevent them from piling up indefinitely.
However, if multiple people start reporting the same issue enough to warrant it getting reprioritized, I'll duplicate and keep one of them open for tracking.

**Comment by Sanjay-F** [comment]
+1
I use lottie version 3.0.1.

the crash is in android  4.4/6.0 os
and it have enough free memory and disk size.
 
-------

java.lang.NullPointerException
at android.view.View.buildDrawingCache(View.java:13851)
at com.airbnb.lottie.LottieAnimationView.buildDrawingCache(LottieAnimationView.java:931)
at android.view.View.getDisplayList(View.java:13568)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.draw(View.java:14749)
at android.view.View.getDisplayList(View.java:13598)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.draw(View.java:14749)
at android.widget.FrameLayout.draw(FrameLayout.java:534)
at android.view.View.getDisplayList(View.java:13598)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.draw(View.java:14749)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
at android.view.View.getDisplayList(View.java:13598)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at  FeedPullToRefreshRecyclerView.dispatchDraw(FeedPullToRefreshRecyclerView.java:86)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.draw(View.java:14749)
at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
at android.view.View.getDisplayList(View.java:13598)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.draw(View.java:14749)
at android.widget.FrameLayout.draw(FrameLayout.java:534)
at android.view.View.getDisplayList(View.java:13598)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.View.draw(View.java:14440)
at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2387)
at android.view.View.getDisplayList(View.java:13590)
at android.view.View.getDisplayList(View.java:13645)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2722)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2587)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2210)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:560)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(NativeStart.java)
