### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.airbnb.lottie.LottieDrawable$a.a(com.airbnb.lottie.LottieComposition)' on a null object reference

### ISSUE THREAD

**Issue by Sanjay-F** [airbnb/lottie-android#1407]
**Describe the bug**
 java.lang.NullPointerException: Attempt to invoke interface method 'void com.airbnb.lottie.LottieDrawable$a.a(com.airbnb.lottie.LottieComposition)' on a null object reference
at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:477)
at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java:79)
at com.airbnb.lottie.LottieComposition$Factory$ListenerAdapter.onResult(LottieComposition.java:342)
at com.airbnb.lottie.LottieComposition$Factory$ListenerAdapter.onResult(LottieComposition.java:330)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:153)
at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:140)
at android.os.Handler.handleCallback(Handler.java:907)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**What version of Lottie did you test this on?**
v3.0.2
 
**What version of Android did you test this on?**
6.0-10.0

**Steps To Reproduce**

i can't reproduce.

**Screenshots**

**Comment by gpeal** [comment]
Please try with 3.2.2. It's likely that this was fixed by one of these
https://github.com/airbnb/lottie-android/issues?utf8=%E2%9C%93&q=is%3Aissue+NullPointerException

Please reopen with an unobfuscated stack trace if it happens with 3.2.2.

**Comment by zhuangzhitu** [comment]
No fix, 3.5.0 still exists @gpeal

**Comment by zhuangzhitu** [comment]
https://github.com/airbnb/lottie-android/issues/1702
