### ISSUE TITLE
Crash in v3.2.0 if android:scaleType="fitCenter" is set

### ISSUE THREAD

**Issue by zboing** [airbnb/lottie-android#1432]
If the user uses 3.2.0 dependency and uses the below code in the layout xml he will notice that the app crashes with below lines.
In version 3.1.0 this crash doesn't occur.

        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/soccer"
            android:layout_width="match_parent"
            android:layout_height="300dp"
            android:layout_centerInParent="true"
            android:layout_margin="20dp"
            android:scaleType="fitCenter"
            app:lottie_autoPlay="true"
            app:lottie_fileName="soccer-field.json"
            app:lottie_loop="true" />

```
     Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class com.airbnb.lottie.LottieAnimationView
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieDrawable.setScaleType(android.widget.ImageView$ScaleType)' on a null object reference
        at com.airbnb.lottie.LottieAnimationView.setScaleType(LottieAnimationView.java:847)
 E/AndroidRuntime:     at android.widget.ImageView.<init>(ImageView.java:171)
        at android.widget.ImageView.<init>(ImageView.java:145)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:124)
        	... 32 more
```

**Comment by boduan402** [comment]
I will send out a PR to fix this soon.

**Comment by aymeekouakou** [comment]
Hi,
I have the same issue. Work perfectly in 2.8.0

**Comment by boduan402** [comment]
PR is under review.

**Comment by somesh-basicx** [comment]
Will there be a bug fix release right after this PR?

**Comment by AndroidDeveloperLB** [comment]
Just a note:
This occurs on centerCrop scaleType too, as I wrote here (with sample) : 
https://github.com/airbnb/lottie-android/issues/1435

**Comment by PattaFeuFeu** [comment]
This also occured for me with `centerInside` as the `scaleType`.

```xml
<com.airbnb.lottie.LottieAnimationView
    android:id="@+id/lav_animation"
    android:layout_width="0dp"
    android:layout_height="0dp"
    android:layout_margin="32dp"
    android:scaleType="centerInside"
    app:layout_constraintDimensionRatio="1:1"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:lottie_autoPlay="false"
    app:lottie_loop="true"
    app:lottie_rawRes="@raw/lottie_reservation_1" />
```

**Comment by AndroidDeveloperLB** [comment]
Why is this closed?
Is it fixed? What should I put on gradle as dependency?

**Comment by PattaFeuFeu** [comment]
Because it is fixed.

Version 3.2.2 and newer work. I am using 3.2.2 in production currently—that one definitely resolves the issue.

**Comment by AndroidDeveloperLB** [comment]
@PattaFeuFeu OK thank you.
Too bad nobody wrote on which version it's fixed when it got closed

**Comment by Nan0fm** [comment]
Hi 

I've got the same issue

    implementation 'com.airbnb.android:lottie:3.2.0'

    `<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
       >

          <ImageView
            android:id="@+id/ivMain"
            android:layout_width="0dp"
            android:layout_height="300dp"
            android:layout_marginStart="40dp"
            android:layout_marginEnd="40dp"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/scanLine"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintBottom_toBottomOf="@id/ivMain"
            app:layout_constraintEnd_toEndOf="@id/ivMain"
            android:scaleType="fitCenter"
            app:layout_constraintStart_toStartOf="@id/ivMain"
            app:layout_constraintTop_toTopOf="@id/ivMain"
            app:lottie_autoPlay="true"
            app:lottie_fileName="scan_line_500.json"
            app:lottie_loop="true" />

    </androidx.constraintlayout.widget.ConstraintLayout>
`

Error
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieDrawable.setScaleType(android.widget.ImageView$ScaleType)' on a null object reference
2020-05-07 16:13:15.677 19816-19816   E/AndroidRuntime:     at com.airbnb.lottie.LottieAnimationView.setScaleType(LottieAnimationView.java:847)
        at android.widget.ImageView.<init>(ImageView.java:203)
        at android.widget.ImageView.<init>(ImageView.java:172)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:124)



Without 
  android:scaleType="fitCenter"
it's not crashing.
