### ISSUE TITLE
Bug: crash of "InflateException" when using Lottie 3.2.0

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#1435]
**Describe the bug**
Crash.

**What version of Lottie did you test this on?**
3.2.0

**What version of Android did you test this on?**
Android 10 (Q). on Pixel 2.

**Steps To Reproduce**
Just have a simple animation view of Lottie, and run the app.
The issue doesn't exist on 3.1.0.

The bug is that it crashes with this log:
```
Caused by: android.view.InflateException: Binary XML file line #7 in com.example.user.lottietest:layout/activity_main: Error inflating class com.airbnb.lottie.LottieAnimationView
```
[2019-11-17_12-29-47.zip](https://github.com/airbnb/lottie-android/files/3855472/2019-11-17_12-29-47.zip)
[LottieTest.zip](https://github.com/airbnb/lottie-android/files/3855473/LottieTest.zip)

**Comment by droidluv** [comment]
Same crash happening for me as well with even more info, apparently the LottieDrawable instance is becoming null

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieDrawable.setScaleType(android.widget.ImageView$ScaleType)' on a null object reference
        at com.airbnb.lottie.LottieAnimationView.setScaleType(LottieAnimationView.java:847)
        at android.widget.ImageView.<init>(ImageView.java:221)
        at android.widget.ImageView.<init>(ImageView.java:188)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:124)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at com.burstoralcare.mainmodule.videolist.adapter.VideoListAdapter.onCreateViewHolder(VideoListAdapter.kt:40) 
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114) 
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303) 
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627) 
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587) 
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391) 
        at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128) 
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1841) 
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5302) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:790) 
        at android.view.Choreographer.doFrame(Choreographer.java:721) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by droidluv** [comment]
Seems like this might be a duplicate of https://github.com/airbnb/lottie-android/issues/1432, mine is exactly the same where the setScale type crashes because the LottieDrawable instance becomes null

**Comment by AndroidDeveloperLB** [comment]
Guys I don't even use anything special here...

**Comment by droidluv** [comment]
@AndroidDeveloperLB from your attached video its apparent the app is crashing when calling setScaleType this is a duplicate of this https://github.com/airbnb/lottie-android/issues/1432 there is PR sent for a fix, but this might issue might be stemming from somehing else, I suggest you close this and follow the mentioned issue for how the resolution for this goes

**Comment by AndroidDeveloperLB** [comment]
@droidluv But I use just centerCrop...

**Comment by droidluv** [comment]
This is a bug, no matter what you use for scale type it will crash

**Comment by AndroidDeveloperLB** [comment]
I thought it's about this specific scale type. OK I will close it and just comment there.

**Comment by codeemphasize** [comment]
I had the same issue and yes it is correct app crashes after removing scaleType is running is perfectly. Thank you. droidluv
