### ISSUE TITLE
Crash when load animator file

### ISSUE THREAD

**Issue by jiangbing321** [airbnb/lottie-android#1457]
**When load the animator json file, the app crash. Following is the back trace.  Attach the sample project. I try it on IOS platform and it is ok. The lottie version is 3.2.2**

2019-12-06 17:07:27.240 10045-10045/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testcjb, PID: 10045
    java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:73)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:66)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:90)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:83)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalArgumentException: The Path cannot loop back on itself.
        at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:185)
        at android.view.animation.PathInterpolator.initCubic(PathInterpolator.java:158)
        at android.view.animation.PathInterpolator.<init>(PathInterpolator.java:89)
        at androidx.core.view.animation.PathInterpolatorCompat.create(PathInterpolatorCompat.java:82)
        at com.airbnb.lottie.parser.KeyframeParser.parseKeyframe(KeyframeParser.java:140)
        at com.airbnb.lottie.parser.KeyframeParser.parse(KeyframeParser.java:68)
        at com.airbnb.lottie.parser.KeyframesParser.parse(KeyframesParser.java:41)
        at com.airbnb.lottie.parser.AnimatableValueParser.parse(AnimatableValueParser.java:79)
        at com.airbnb.lottie.parser.AnimatableValueParser.parseInteger(AnimatableValueParser.java:38)
        at com.airbnb.lottie.parser.AnimatableTransformParser.parse(AnimatableTransformParser.java:98)
        at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:132)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:121)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:87)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:280)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:273)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:203)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:196)
        at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:159)
        at com.airbnb.lottie.LottieCompositionFactory$3.call(LottieCompositionFactory.java:144)
        at com.airbnb.lottie.LottieCompositionFactory$3.call(LottieCompositionFactory.java:139)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

**Comment by jiangbing321** [comment]
[TestCJB.zip](https://github.com/airbnb/lottie-android/files/3931355/TestCJB.zip)
This is  the android sample project, it contains the animator file
