### ISSUE TITLE
 java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder

### ISSUE THREAD

**Issue by susirsusir** [airbnb/lottie-android#1462]
使用zip文件直接播放动效
代码如下：
 mAnimationView.setAnimation("playground_bg.zip");
 mAnimationView.playAnimation();
 
zip文件存在asstes当中

在播放动效的页面，第一次打开这个页面，动效播放正常。
退出当前页面，第二次进入，onAttachedToWindow之后发生崩溃

报错如下：
E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:107)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:839)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:32)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
        at android.view.View.draw(View.java:20261)

lottie版本 2.7.0

**Comment by gpeal** [comment]
http://airbnb.io/lottie/#/android?id=images

**Comment by susirsusir** [comment]
> http://airbnb.io/lottie/#/android?id=images

Zip file
Alternatively, you can create a zip file with your json and images together. Lottie can unzip and read the contents. This can be done for local files or from a url.

描述可以直接播放zip文件的，我的用法不对么？

**Comment by crazy1235** [comment]
所以不了了之了？
