### ISSUE TITLE
java.lang.IllegalStateException: Unable to parse composition

### ISSUE THREAD

**Issue by blackvirus** [airbnb/lottie-android#1474]
I get error in Google Pixel Emulator API 27

FATAL EXCEPTION: main
    Process: com.vingroup.vinid.staging, PID: 844
    java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:74)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:67)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:91)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:84)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at ac.<init>(Unknown Source:21)
        at x.getErrorStream(Unknown Source:48)
        at com.google.firebase.perf.network.zzd.getErrorStream(com.google.firebase:firebase-perf@@19.0.0:146)
        at com.google.firebase.perf.network.zzb.getErrorStream(com.google.firebase:firebase-perf@@19.0.0:37)
        at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:96)
        at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:79)
        at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:48)
        at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
        at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:84)
        at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:81)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by gpeal** [comment]
@blackvirus Lottie doesn't use firebase at all. It might be related to [this](https://www.youtube.com/watch?v=cTJEzvUlTSQ). Are you doing something with Firebase network analytics that might be doing a bytecode transformation?

**Comment by blackvirus** [comment]
Thanks for your reply, after few days, we got problem. We had conflict with Cloudfare library. When Lottie fetch from Network with HttpUrlConnection, how some it gets implementation HttpUrlConnection from Cloudfare. We still working on this

**Comment by gpeal** [comment]
@blackvirus I don't think this is Lottie related. If you think it is, please create a repro in the issue-repro module and reopen this.
