### ISSUE TITLE
Crash when adding Lottie dependency

### ISSUE THREAD

**Issue by Zoomagic** [airbnb/lottie-android#1475]
I'm currently adding lottie 3.3.1 to my project, but it made the app crash on startup. This seemed to be due to lottie using an old version of `androidx.appcompat`. I used `./gradlew app:dependencies` to see whats up and found the following.
```
 com.airbnb.android:lottie:3.3.1
|    +--- androidx.appcompat:appcompat:1.0.0 -> 1.1.0 (*)
|    \--- com.squareup.okio:okio:1.17.4
```
i had to setup my dependency with the following group exclude:
``` 
implementation ("com.airbnb.android:lottie:3.3.1"){
        exclude group: 'androidx.appcompat'    }
```
in the project i use the 1.1.0 version of `appcompat`.

**Comment by gpeal** [comment]
@Zoomagic That doesn't seem right.  All of our apps are on 1.1 and even in your list there, you can see that gradle automatically promoted appcompat fro 1.0.0 to 1.1.0.

What was the actual crash?

**Comment by Zoomagic** [comment]
So sorry for forgetting the crash log. `2020-01-07 09:26:55.760 17543-17543/app.undo.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.undo.android, PID: 17543
    java.lang.ExceptionInInitializerError
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at app.undo.android.domain.application.singletons.SdkManager.initMapbox(SdkManager.kt:35)
        at app.undo.android.domain.application.singletons.SdkManager.initialize(SdkManager.kt:21)
        at app.undo.android.domain.application.ApplicationController.onCreate(ApplicationController.kt:37)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: libmapbox-gl.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$ReLinkerLibraryLoader.load(LibraryLoaderProviderImpl.java:38)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60) 
        at app.undo.android.domain.application.singletons.SdkManager.initMapbox(SdkManager.kt:35) 
        at app.undo.android.domain.application.singletons.SdkManager.initialize(SdkManager.kt:21) 
        at app.undo.android.domain.application.ApplicationController.onCreate(ApplicationController.kt:37) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

This happens if I don't exclude the group. Maybe it's the other way around if the appcompat have been promoted..

**Comment by Zoomagic** [comment]
Just tried excluding it from my MapBox dependency - that worked as well. Ill write them, thank you for your time :)
