### ISSUE TITLE
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xa0a69048: I/O error during system call, Software caused connection abort

### ISSUE THREAD

**Issue by wz1993** [airbnb/lottie-android#1479]
java.lang.IllegalStateException: Unable to parse composition
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:75)
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:73)
    at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
    at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
    at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7094)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xa0a69048: I/O error during system call, Software caused connection abort
    at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
    at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
    at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
    at java.io.InputStream.read(InputStream.java:101)
    at com.airbnb.lottie.network.NetworkCache.writeTempCacheFile(NetworkCache.java:83)
    at com.airbnb.lottie.network.NetworkFetcher.getResultFromConnection(NetworkFetcher.java:148)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:101)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:79)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:48)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:71)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
javax.net.ssl.SSLException: Read error: ssl=0xa0a69048: I/O error during system call, Software caused connection abort
    at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
    at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
    at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
    at java.io.InputStream.read(InputStream.java:101)
    at com.airbnb.lottie.network.NetworkCache.writeTempCacheFile(NetworkCache.java:83)
    at com.airbnb.lottie.network.NetworkFetcher.getResultFromConnection(NetworkFetcher.java:148)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:101)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:79)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:48)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:71)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

**Comment by gpeal** [comment]
@wz1993 Add a [failure listener ](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L441)so you can catch/retry these. Lottie can't magically make a device's internet work.
