### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by porkyhead** [airbnb/lottie-android#148]
I have two animations playing in concurrently in a viewpager. Each animation contains images. Using via xml only. When my app exits I get the following crash:

Process: com.medicomip.eagle2, PID: 4287
                  java.util.ConcurrentModificationException
                      at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                      at java.util.HashMap$KeyIterator.next(HashMap.java:885)
                      at com.airbnb.lottie.ImageAssetBitmapManager.recycleBitmaps(ImageAssetBitmapManager.java:68)
                      at com.airbnb.lottie.LottieDrawable.recycleBitmaps(LottieDrawable.java:114)
                      at com.airbnb.lottie.LottieAnimationView.recycleBitmaps(LottieAnimationView.java:170)
                      at com.airbnb.lottie.LottieAnimationView.onDetachedFromWindow(LottieAnimationView.java:161)
                      at android.view.View.dispatchDetachedFromWindow(View.java:15446)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
                      at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3255)
                      at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5881)
                      at android.view.ViewRootImpl.die(ViewRootImpl.java:5858)
                      at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
                      at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
                      at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4207)
                      at android.app.ActivityThread.-wrap6(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Any suggestions?

Best regards Christian

**Comment by gpeal** [comment]
@porkyhead Thanks for the report. I'll fix this.

**Comment by MrGatsby2** [comment]
u may use iterator to cope whit it, fyi,when i use images, my image isn't at the right place as designed by AE @gpeal

**Comment by gpeal** [comment]
@MrGatsby2 Can you attach the broken AE file to #71 and reopen it if there is an issue? Happy to take a look.
