### ISSUE TITLE
Changing the order of the bodymovin json causes the library to crash

### ISSUE THREAD

**Issue by khalideali** [airbnb/lottie-android#1529]
I'm making some changes to the bodymovin json which causes the properties to get reordered. I've created a simple bodymovin json to illustrate this issue. 

This is the original bodymovin json: 
`"shapes": [
        {
          "ty": "gr",
          "it": [
            {
              "ty": "rc",
              "d": 1,
              "s": {
                "a": 0,
                "k": [
                  682.273,
                  196.422
                ],
                "ix": 2
              },
              "p": {
                "a": 0,
                "k": [
                  0,
                  0
                ],
                "ix": 3
              },
              "r": {
                "a": 0,
                "k": 0,
                "ix": 4
              },
              "nm": "Rectangle Path 1",
              "mn": "ADBE Vector Shape - Rect",
              "hd": false
            },`

This is the modified json:
`"shapes": [
        {
          "ty": "gr",
          "it": [
            {
              "r": {
                "a": 0,
                "k": 0,
                "ix": 4
              },
              "ty": "rc",
              "d": 1,
              "s": {
                "a": 0,
                "k": [
                  682.273,
                  196.422
                ],
                "ix": 2
              },
              "p": {
                "a": 0,
                "k": [
                  0,
                  0
                ],
                "ix": 3
              },
              "nm": "Rectangle Path 1",
              "mn": "ADBE Vector Shape - Rect",
              "hd": false
            },`

Here are the full bodymovin files as well as the AE file:
[Archive.zip](https://github.com/airbnb/lottie-android/files/4289994/Archive.zip)

All I I changed is moving the "r" property before the "ty" property. This is the simplest change I've made to the bodymovin json to reproduce this issue. However, I've also noticed other cases where the app wouldn't crash but the shape wouldn't appear. 

What version of Lottie did you test this on?
3.3.0

What version of Android did you test this on?
Android 10

Logcat: 
`    java.lang.NullPointerException: Attempt to invoke virtual method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableFloatValue.createAnimation()' on a null object reference
        at com.airbnb.lottie.animation.content.RectangleContent.<init>(RectangleContent.java:43)
        at com.airbnb.lottie.model.content.RectangleShape.toContent(RectangleShape.java:50)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:35)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:46)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:290)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:484)
     `

**Comment by gpeal** [comment]
This is the expected behavior because Lottie uses streaming json parsing so the order matters.
