### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by adamvarhegyi** [airbnb/lottie-android#153]
I use **Lottie** in an **activity.**

**View:**

     <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:lottie_fileName="splash_animation.json"
            app:lottie_loop="true"
            app:lottie_autoPlay="true" />

**Activity:**

` @BindView(R.id.animation_view) LottieAnimationView lottieAnimationView;`
```

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        unbinder = ButterKnife.bind(this);

        lottieAnimationView.setImageAssetsFolder("images");

//.. more code here

```
```

 @Override
    public void onDestroy() {
        super.onDestroy();

        if(unbinder!=null) {
            unbinder.unbind();
        }

//.. more code here

```

When I leave the activity like starting a new one from this current activity or finishing this activity by `onBackPressed` I got the following exception like in the next 1-2 second:

```
02-23 10:12:22.859: E/AndroidRuntime(13085): java.util.ConcurrentModificationException
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.airbnb.lottie.ImageAssetBitmapManager.recycleBitmaps(ImageAssetBitmapManager.java:68)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.airbnb.lottie.LottieDrawable.recycleBitmaps(LottieDrawable.java:114)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.airbnb.lottie.LottieAnimationView.recycleBitmaps(LottieAnimationView.java:170)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.airbnb.lottie.LottieAnimationView.onDetachedFromWindow(LottieAnimationView.java:161)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.View.dispatchDetachedFromWindow(View.java:14561)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3068)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.ViewRootImpl.die(ViewRootImpl.java:5583)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3867)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.os.Looper.loop(Looper.java:148)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at java.lang.reflect.Method.invoke(Native Method)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-23 10:12:22.859: E/AndroidRuntime(13085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

Can someone help me ? I did not found anything about this in the closed issues, nor in google.

The Lottie assets that I us**e can be found here with .json and images:**
https://drive.google.com/open?id=0B90TJcUpITEuZEcteGZYZHg2LVE

**Comment by gpeal** [comment]
Thanks for the report
#148

**Comment by adamvarhegyi** [comment]
Err. Thanks and close? Any suggestion what should I change to make this work?

**Comment by gpeal** [comment]
Upgrade to 1.5.1

**Comment by adamvarhegyi** [comment]
Thank you very much.
