### ISSUE TITLE
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by sunnydlee** [airbnb/lottie-android#1558]
version：android 9.0 
device：OPPO PBDM00

**code:**
`<com.airbnb.lottie.LottieAnimationView
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            app:lottie_autoPlay="true"
            app:lottie_fileName="data_net_error.json"
            app:lottie_imageAssetsFolder="images_net_error"
            app:lottie_loop="true"
            />
`

**log：**
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded(Utils.java:242)
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:117)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1037)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.LottieDrawable.drawWithNewAspectRatio(LottieDrawable.java:1176)
        at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:378)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:370)
        at android.widget.ImageView.onDraw(ImageView.java:1379)
        at android.view.View.draw(View.java:20503)
        at android.view.View.updateDisplayListIfDirty(View.java:19370)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
        at android.view.View.updateDisplayListIfDirty(View.java:19330)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3990)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3741)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3036)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1874)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8141)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1146)
        at android.view.Choreographer.doCallbacks(Choreographer.java:957)
        at android.view.Choreographer.doFrame(Choreographer.java:884)

**Comment by gpeal** [comment]
Closing due to no repro steps. Feel free to reopen with repro steps.

**Comment by 1wayticket** [comment]
```

1 com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded(Utils.java:248)
--
2 com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:117)
3 com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:974)
4 com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
5 com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
6 com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:221)
7 com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
8 com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:221)
9 com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:357)
10 android.widget.ImageView.onDraw(ImageView.java:1532)
11 android.view.View.draw(View.java:21618)
12 android.view.View.updateDisplayListIfDirty(View.java:20483)
13 android.view.View.draw(View.java:21350)
14 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
15 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
16 android.view.View.updateDisplayListIfDirty(View.java:20474)
17 android.view.View.draw(View.java:21350)
18 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
19 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
20 android.view.View.updateDisplayListIfDirty(View.java:20474)
21 android.view.View.draw(View.java:21350)
22 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
23 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
24 android.view.View.updateDisplayListIfDirty(View.java:20474)
25 android.view.View.draw(View.java:21350)
26 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
27 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
28 android.view.View.draw(View.java:21621)
29 com.android.internal.policy.DecorView.draw(DecorView.java:964)
30 android.view.View.updateDisplayListIfDirty(View.java:20483)
31 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
32 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
33 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
34 android.view.ViewRootImpl.draw(ViewRootImpl.java:3840)
35 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648)
36 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
37 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
38 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
39 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
40 android.view.Choreographer.doCallbacks(Choreographer.java:875)
41 android.view.Choreographer.doFrame(Choreographer.java:776)
42 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
43 android.os.Handler.handleCallback(Handler.java:888)
44 android.os.Handler.dispatchMessage(Handler.java:100)
45 android.os.Looper.loop(Looper.java:213)
46 android.app.ActivityThread.main(ActivityThread.java:8169)
47 java.lang.reflect.Method.invoke(Native Method)
48 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
49 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


```
This bug is happend occasionally among huawei/sumsung/oppo and so on when I update lottie to 3.1.0.
Is it a bug newly in v3.1.0?

**Comment by 1wayticket** [comment]
> version：android 9.0
> device：OPPO PBDM00
> 
> **code:**
> `<com.airbnb.lottie.LottieAnimationView android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" app:lottie_autoPlay="true" app:lottie_fileName="data_net_error.json" app:lottie_imageAssetsFolder="images_net_error" app:lottie_loop="true" /> `
> 
> **log：**
> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> at com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded(Utils.java:242)
> at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:117)
> at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1037)
> at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
> at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
> at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
> at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
> at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
> at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
> at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
> at com.airbnb.lottie.LottieDrawable.drawWithNewAspectRatio(LottieDrawable.java:1176)
> at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:378)
> at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:370)
> at android.widget.ImageView.onDraw(ImageView.java:1379)
> at android.view.View.draw(View.java:20503)
> at android.view.View.updateDisplayListIfDirty(View.java:19370)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4438)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4411)
> at android.view.View.updateDisplayListIfDirty(View.java:19330)
> at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
> at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
> at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
> at android.view.ViewRootImpl.draw(ViewRootImpl.java:3990)
> at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3741)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3036)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1874)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8141)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1146)
> at android.view.Choreographer.doCallbacks(Choreographer.java:957)
> at android.view.Choreographer.doFrame(Choreographer.java:884)

Do you have any solution about this problem? It seemed a bug bug only we report it.
