### ISSUE TITLE
java.lang.OutOfMemoryError happens without any bitmap

### ISSUE THREAD

**Issue by jhwsx** [airbnb/lottie-android#1562]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
My code is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lav_mix_progress"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@id/tv_mix_progress"
        app:layout_constraintDimensionRatio="h,1:1"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_chainStyle="packed"
        app:layout_constraintWidth_percent="0.5"
        app:lottie_loop="true"
        app:lottie_rawRes="@raw/anim_set_video_show" />

    <TextView
        android:id="@+id/tv_mix_progress"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/edit_video_mix_progress"
        android:textColor="@color/common_white"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/lav_mix_progress" />
</androidx.constraintlayout.widget.ConstraintLayout>
```
```java
public class EditVideoMixProgressDialogFragment extends DialogFragment {
    private static final String TAG = EditVideoMixProgressDialogFragment.class.getSimpleName();

    private LottieAnimationView lavMixProgress;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate: ");
        setCancelable(false);
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        Log.i(TAG, "onCreateView: ");
        final Window window = getDialog().getWindow();
        window.setBackgroundDrawableResource(android.R.color.transparent);
        window.getDecorView().setPadding(0, 0, 0, 0);
        WindowManager.LayoutParams wlp = window.getAttributes();
        wlp.gravity = Gravity.CENTER;
        wlp.width = WindowManager.LayoutParams.MATCH_PARENT;
        wlp.height = WindowManager.LayoutParams.MATCH_PARENT;
        window.setAttributes(wlp);
        return inflater.inflate(R.layout.edit_video_mix_progress_dialog_fragment,
                container, false);
    }

    public static void showMixDialog(AppCompatActivity activity) {
        if (fragment == null) {
            fragment = EditVideoMixProgressDialogFragment.newInstance();
            fragment.show(activity.getSupportFragmentManager(), TAG);
        }
    }

    public static void dismissMixDialog() {
        if (fragment != null) {
            fragment.dismiss();
            fragment = null;
        }
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        Log.i(TAG, "onViewCreated: ");
        lavMixProgress = view.findViewById(R.id.lav_mix_progress);
        lavMixProgress.playAnimation();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        Log.i(TAG, "onDestroyView: ");
        if (lavMixProgress != null) {
            lavMixProgress.cancelAnimation();
        }
        fragment = null;
    }

    private static EditVideoMixProgressDialogFragment newInstance() {
        Bundle args = new Bundle();
        EditVideoMixProgressDialogFragment fragment = new EditVideoMixProgressDialogFragment();
        fragment.setArguments(args);
        return fragment;
    }
    private static EditVideoMixProgressDialogFragment fragment;

}

```
```text
05-10 14:15:44.306 E/AndroidRuntime( 3574): FATAL EXCEPTION: main
05-10 14:15:44.306 E/AndroidRuntime( 3574): Process: com.koki.callshow, PID: 3574
05-10 14:15:44.306 E/AndroidRuntime( 3574): java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 552 free bytes and 552B until OOM
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at java.util.concurrent.CopyOnWriteArrayList.iterator(CopyOnWriteArrayList.java:184)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at java.util.concurrent.CopyOnWriteArraySet.iterator(CopyOnWriteArraySet.java:306)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:87)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:98)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.view.Choreographer.doFrame(Choreographer.java:628)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.os.Handler.handleCallback(Handler.java:815)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.os.Looper.loop(Looper.java:205)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at android.app.ActivityThread.main(ActivityThread.java:5814)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at java.lang.reflect.Method.invoke(Native Method)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
05-10 14:15:44.306 E/AndroidRuntime( 3574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```
**What version of Lottie did you test this on?**
3.4.0
**What version of Android did you test this on?**
6.0
**Steps To Reproduce**

1, when I play the lottie, it crashes sometimes.
[anim_set_video_show.zip](https://github.com/airbnb/lottie-android/files/4605248/anim_set_video_show.zip)

**Screenshots**
None.

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
![image](https://user-images.githubusercontent.com/1307745/81521843-53e32e00-92fd-11ea-9a4e-b9c82d26a300.png)
This is your animation on loop with nothing else. The memory graph is flat.
![image](https://user-images.githubusercontent.com/1307745/81521892-812fdc00-92fd-11ea-850b-1a34120bdcc6.png)
This is the same empty app with no animation. The stats are barely any different.

**Comment by jhwsx** [comment]
Thanks.

**Comment by linkinamine** [comment]
Hey @gpeal @jhwsx,I am facing a similar issue on API 26, however testing on API 28 didn't generate any memory overhead in the graphics section.
@gpeal did you try with an api-26 device? 

@jhwsx switching to software rendering. reduced the memory consumption by half, leaving it as automatic was rendering the animation as a  hardware. Following the logic added here: 

https://github.com/airbnb/lottie-android/pull/1072/commits/3cd7bfc9fc525f7f0dd9ef0e421d79240144d9f2#diff-3fed8fdab23c1f8e4ddab55a92bb30f1
