### ISSUE TITLE
LottieCompositionFactory.fromUrl crash

### ISSUE THREAD

**Issue by chenjianping99** [airbnb/lottie-android#1573]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:107)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:839)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:32)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
        at android.view.View.draw(View.java:20234)
        at android.view.View.buildDrawingCacheImpl(View.java:19505)
        at android.view.View.buildDrawingCache(View.java:19365)
        at android.view.View.draw(View.java:19954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
**What version of Lottie did you test this on?**
2.7.0
**What version of Android did you test this on?**
All
**Steps To Reproduce**

**Screenshots**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
http://airbnb.io/lottie/#/android?id=images
