### ISSUE TITLE
Out of memory: crash when show many animations frequently (RAM can't release after animation done)

### ISSUE THREAD

**Issue by xensius** [airbnb/lottie-android#1574]
*** Config Info ***
Version used: com.airbnb.android:lottie:3.4.0
appcompat: androidx

minSdkVersion 16
targetSdkVersion 29
compileSdkVersion = 29
buildToolsVersion = "29.0.2"

Device used: Asus Asus_X008D (Android 7.0) --> I catched crash on this device easier (128 MB ram for app)

*** Sample project: https://github.com/xensius/TestLottie

** Describe the bug:
My app shows many different gift animations frequently. ex: A,B,C,D, ... is gift animation. My app will play animation A then animation A done, app will play animation B .... then for C, D, ...

i logged usage ram info, and i see when animation play RAM usage increased but when animation is done, RAM usage is not released or hard to release and make a crash when get full RAM.
i checked on devices: the issue occurs on Redmi 3s (Android 6.0), Samsung GT-I9505 (Android 5.01), Asus Asus_X008D (Android 7.0) but Lottie works OK about RAM usage on Samsung A20s (Android 9.0).

Thank team very much and hope get your reply soon!!!

**Comment by gpeal** [comment]
@xensius Lottie caches compositions by default so that if you want to render them again, Lottie doesn't have to parse your json file again. If you call `LottieCompositionCache.getInstance().clear()`, it will clear the cache.
I tested it with your project and Lottie retained no objects after clearing the cache.

**Comment by anus-ali** [comment]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 90012 byte allocation with 51584 free bytes and 50KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeByteArray(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:744)
       at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:113)
       at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1103)
       at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:64)
       at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:34)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
       at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1294)
       at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:407)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:397)
       at android.widget.ImageView.onDraw(ImageView.java:1197)
       at android.view.View.draw(View.java:16536)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:


Facing this crash 
Android 5.1.1
Device is Galaxy A5
