### ISSUE TITLE
Unable to parse composition JsonUtf8Reader.nextNonWhitespace

### ISSUE THREAD

**Issue by AyushGoel529** [airbnb/lottie-android#1582]
We are setting a lottie animation through URL:
In below code view is of type LottieAnimationView.

try {
String lottieUrl = Constants.LOTTIE_BASE_URL + lottieName + ".json";
view.setAnimationFromUrl(lottieUrl);
} catch (Exception e) {
e.printStackTrace();
}

I have cross checked all the Lottie URL we are using and they are fine. Still it is showing parse error some times

Below is the error log. Please help to resolve the crash or catch the same.

Caused by java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:74)
       at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:67)
       at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:91)
       at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:84)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
       at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Caused by java.io.EOFException: End of input
       at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.nextNonWhitespace(JsonUtf8Reader.java:943)
       at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:300)
       at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:174)
       at com.airbnb.lottie.parser.JsonUtils.jsonToPoint(JsonUtils.java:47)
       at com.airbnb.lottie.parser.JsonUtils.jsonToPoints(JsonUtils.java:39)
       at com.airbnb.lottie.parser.ShapeDataParser.parse(ShapeDataParser.java:50)
       at com.airbnb.lottie.parser.ShapeDataParser.parse(ShapeDataParser.java:15)
       at com.airbnb.lottie.parser.KeyframeParser.parseKeyframe(KeyframeParser.java:99)
       at com.airbnb.lottie.parser.KeyframeParser.parse(KeyframeParser.java:68)
       at com.airbnb.lottie.parser.KeyframesParser.parse(KeyframesParser.java:41)
       at com.airbnb.lottie.parser.AnimatableValueParser.parse(AnimatableValueParser.java:87)
       at com.airbnb.lottie.parser.AnimatableValueParser.parseShapeData(AnimatableValueParser.java:55)
       at com.airbnb.lottie.parser.MaskParser.parse(MaskParser.java:49)
       at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:141)
       at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:121)
       at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:87)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:353)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:346)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:276)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:269)
       at com.airbnb.lottie.LottieCompositionFactory$4.call(LottieCompositionFactory.java:259)
       at com.airbnb.lottie.LottieCompositionFactory$4.call(LottieCompositionFactory.java:256)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by gpeal** [comment]
@AyushGoel529 You must set a failure listener. The animation will be loaded asynchronously so your try/catch there won't do anything
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L461
