### ISSUE TITLE
Android 5.1.1 Unable to create layer for LottieAnimationView android.os.MessageQueue.nativePollOnce

### ISSUE THREAD

**Issue by wu1178279937** [airbnb/lottie-android#1632]
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for LottieAnimationView
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:148)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5475)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by Mryushen** [comment]
android.graphics.Path.set(Path.java:96)
2
com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java)
3
com.airbnb.lottie.animation.content.FillContent.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(FillContent.java)
4
com.airbnb.lottie.animation.content.ContentGroup.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(ContentGroup.java)
5
com.airbnb.lottie.animation.content.ContentGroup.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(ContentGroup.java)
6
com.airbnb.lottie.model.layer.ShapeLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(ShapeLayer.java)
7
com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java)
8
com.airbnb.lottie.model.layer.CompositionLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(CompositionLayer.java)

**Comment by yushiwo** [comment]
I met the same problem too
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for LottieAnimationView
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5418)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

lottie 3.7.0， android 5
