### ISSUE TITLE
IllegalStateException: Unable to parse composition 

### ISSUE THREAD

**Issue by yoonhok524** [airbnb/lottie-android#1633]
**Describe the bug**
I have some lottie files.
Other file works fine, but only one file doesn't work.
Actually, the file works fine on the Web environment.
But it doesn't work on Android.

I think that it may be the file issue.
Anyway when I try to show the lottie animation on Android, I face the crash with:
```
java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:75)
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:73)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
        at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:135)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:121)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:87)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:262)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:255)
        at com.airbnb.lottie.LottieCompositionFactory$7.call(LottieCompositionFactory.java:247)
        at com.airbnb.lottie.LottieCompositionFactory$7.call(LottieCompositionFactory.java:244)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**What version of Lottie did you test this on?**
I was using the version 3.0.7.
I tried to use the latest version 3.4.2.
But it same...

**What version of Android did you test this on?**
Android 10, Android 7

**Comment by yoonhok524** [comment]
I tried to write the json text in here, but my browser still waiting...
You can access the json file in here: https://static.stgspoon.com/vn/stickers/seasonal/sticker_vn_fullmoon/sticker_vn_fullmoon_lottie.json
Could you check what

**Comment by gpeal** [comment]
@yoonhok524 Your animation has a luma inverted matte which isn't supported. https://github.com/airbnb/lottie-android/pull/1638 will prevent it from crashing and add a warning though.
