### ISSUE TITLE
oom

### ISSUE THREAD

**Issue by chenyichao** [airbnb/lottie-android#1634]
--logversion:utracea
Process Name: &#39;com.ziyin.yue&#39;
Thread Name: &#39;main&#39;
Back traces starts.
java.lang.OutOfMemoryError: Failed to allocate a 2107236 byte allocation with 199232 free bytes and 194KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:635)
	at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:116)
	at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1037)
	at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
	at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
	at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
	at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1221)
	at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:380)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:370)
	at android.widget.ImageView.onDraw(ImageView.java:1246)
	at android.view.View.draw(View.java:16221)
	at android.view.View.updateDisplayListIfDirty(View.java:15218)
	at android.view.View.draw(View.java:15991)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3438)
	at android.view.View.updateDisplayListIfDirty(View.java:15213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3612)
	at android.view.View.updateDisplayListIfDirty(View.java:15178)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2773)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2592)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1209)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6330)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
	at android.view.Choreographer.doCallbacks(Choreographer.java:674)
	at android.view.Choreographer.doFrame(Choreographer.java:610)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
Back traces ends.

**Comment by VaidyaMilind** [comment]
load a scaled-down version into memory

**Comment by gpeal** [comment]
@chenyichao Lottie itself uses low memory and OutOfMemoryExceptions are thrown wherever it happens to run out of memory although it's rarely the root cause. If you think there is a specific issue, please create a sample project that reproduces it.
