### ISSUE TITLE
Crash : Unable to start activity ComponentInfo{com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter preview

### ISSUE THREAD

**Issue by Aliendroid8045** [airbnb/lottie-android#1651]
Device: Emulator Google pixel 2
OS: Android 10

Steps to reproduce: 
Launch the app and click 3 animations inside the showcase.
![Screenshot_1603038384](https://user-images.githubusercontent.com/13978101/96373896-f3baa880-1134-11eb-8bf6-d3db9550f7db.png)

Crash report:
2020-10-18 11:13:32.333 9155-9155/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie, PID: 9155
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter preview
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter preview
        at com.airbnb.lottie.samples.model.AnimationDataV2.<init>(Unknown Source:69)
        at com.airbnb.lottie.samples.model.AnimationDataV2$Creator.createFromParcel(Unknown Source:122)
        at com.airbnb.lottie.samples.model.CompositionArgs$Creator.createFromParcel(Unknown Source:58)
        at android.os.Parcel.readParcelable(Parcel.java:2973)
        at android.os.Parcel.readValue(Parcel.java:2866)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getParcelable(Bundle.java:951)
        at android.content.Intent.getParcelableExtra(Intent.java:7928)
        at com.airbnb.lottie.samples.PlayerActivity.onCreate(PlayerActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by gpeal** [comment]
This must have been a bug on the lottiefiles side. It's no longer in the showcase but when I searched for it, it worked.
