### ISSUE TITLE
Lottie Android app crash when you go to "Lottiefiles" and then go to "Popular" - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by olekstomek** [airbnb/lottie-android#1672]
Xiaomi Mi9, Android 10. Log:

```
java.lang.IndexOutOfBoundsException: Index: 44612, Size: 22322
	at androidx.paging.PagedStorage.get(PagedStorage.java:138)
	at androidx.paging.PagedList.get(PagedList.java:633)
	at com.airbnb.epoxy.paging.PagedListModelCache.getModels(PagedListModelCache.kt:200)
	at com.airbnb.epoxy.paging.PagedListEpoxyController.buildModels(PagedListEpoxyController.kt:74)
	at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:276)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by gpeal** [comment]
I believe this is fixed on master. I can no longer reproduce it there.
