### ISSUE TITLE
Lottie Android app crash when you use search

### ISSUE THREAD

**Issue by olekstomek** [airbnb/lottie-android#1673]
Xiaomi Mi9, Android 10.

First.
1. Go to Lottiefiles
2. Go to Search 
3. Input "." (dot) 
4. Confirm searching
5. Result:

```
java.lang.IllegalStateException: TODO
	at androidx.paging.ContiguousPagedList$1.onPageError(ContiguousPagedList.java:153)
	at androidx.paging.DataSource$LoadCallbackHelper.dispatchOnCurrentThread(DataSource.java:351)
	at androidx.paging.DataSource$LoadCallbackHelper$1.run(DataSource.java:337)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

Second. 
1. Go to Lottiefiles
2. Go to Search 
3. Input eg.: "test"
4. Confirm searching
5. Search again "test" or another word
6. Result:

```
java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
	at android.widget.TextView.onKeyUp(TextView.java:8601)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2847)
	at android.view.View.dispatchKeyEvent(View.java:13487)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:485)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1843)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4021)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:388)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5574)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5442)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4947)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5000)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4966)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5106)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5163)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4947)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5000)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4966)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4947)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7699)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7668)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7629)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4720)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by gpeal** [comment]
I believe this is fixed on master it reproduces in the Play Store version but not on master (for me at least).
