### ISSUE TITLE
Lottie Android app crash when you go to Lottiefiles when device is offline

### ISSUE THREAD

**Issue by olekstomek** [airbnb/lottie-android#1681]
Turn off mobile internet connection and WiFi on your smartphone and go to Lottiefiles. It throws always:

```
java.lang.IllegalStateException: TODO
	at androidx.paging.ContiguousPagedList$1.onPageError(ContiguousPagedList.java:153)
	at androidx.paging.DataSource$LoadCallbackHelper.dispatchOnCurrentThread(DataSource.java:351)
	at androidx.paging.DataSource$LoadCallbackHelper$1.run(DataSource.java:337)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by gpeal** [comment]
This no longer happens on master.
