### ISSUE TITLE
Error in Android OS 7.1 Nougat API Level 25

### ISSUE THREAD

**Issue by eshantmittal** [airbnb/lottie-android#1698]
Hi Team

I am getting below error in Android OS 7.1 Nougat API Level 25

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 4194304 free bytes and 6MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
        at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:533)
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:101)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1037)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
        at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1221)
        at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:380)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:370)
        at android.widget.ImageView.onDraw(ImageView.java:1316)
        at android.view.View.draw(View.java:17185)
        at android.view.View.buildDrawingCacheImpl(View.java:16474)
        at android.view.View.buildDrawingCache(View.java:16335)
        at com.airbnb.lottie.LottieAnimationView.buildDrawingCache(LottieAnimationView.java:990)
        at android.view.View.draw(View.java:16943)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17188)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.draw(View.java:17093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:17188)
        at android.view.View.draw(View.java:17093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:17188)
        at android.view.View.draw(View.java:17093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17091)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17188)
        at com.android.internal.policy.DecorView.draw(DecorView.java:753)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2913)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2827)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
 E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by eshantmittal** [comment]
I have already update my AndroidManifest.xml file with this


android:largeHeap="true"
android:hardwareAccelerated="false"

**Comment by gpeal** [comment]
An OOM rarely has a root cause where it finally actually runs out of memory. Lottie needs _some_ memory to run and if you app was already on the verge of getting killed, it might push it over the edge but this isn't necessarily an indication that there is problem with Lottie itself.

If you think there is, create a repro in the issue-repro module that shows unexpectedly large memory usage.
