### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.airbnb.lottie.f$a.a(com.airbnb.lottie.d)' on a null object reference at com.airbnb.lottie.LottieDrawable.setComposition(SourceFile:229)

### ISSUE THREAD

**Issue by zhuangzhitu** [airbnb/lottie-android#1702]
**lottie version: 3.5.0**

**Android API 28/29 the following crash occurs :**     can you help me? 

java.lang.NullPointerException: Attempt to invoke interface method 'void com.airbnb.lottie.f$a.a(com.airbnb.lottie.d)' on a null object reference
at com.airbnb.lottie.LottieDrawable.setComposition(SourceFile:229)
at com.airbnb.lottie.LottieAnimationView.setComposition(SourceFile:550)
at com.airbnb.lottie.LottieAnimationView$2.onResult(SourceFile:84)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(SourceFile:144)
at com.airbnb.lottie.LottieTask.access$000(SourceFile:27)
                                access$100
                                access$200
                                access$300
at com.airbnb.lottie.LottieTask$1.run(SourceFile:131)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:238)
android.app.ActivityThread.main(ActivityThread.java:7798)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by zhuangzhitu** [comment]
![image](https://user-images.githubusercontent.com/13757638/102969451-b1e12080-4530-11eb-9d58-ec58a62e71b0.png)

**Comment by zhuangzhitu** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.airbnb.lottie.f$a.a(com.airbnb.lottie.d)' on a null object reference
at com.airbnb.lottie.LottieDrawable$LazyCompositionTask.run(com.airbnb.lottie.d)
at com.airbnb.lottie.LottieDrawable.setComposition(SourceFile:229)
at com.airbnb.lottie.LottieAnimationView.setComposition(SourceFile:550)
at com.airbnb.lottie.LottieAnimationView$2.onResult(SourceFile:84)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(SourceFile:144)
at com.airbnb.lottie.LottieTask.access$000(SourceFile:27)
                                access$100
                                access$200
                                access$300
at com.airbnb.lottie.LottieTask$1.run(SourceFile:131)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:238)
android.app.ActivityThread.main(ActivityThread.java:7798)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by zhuangzhitu** [comment]
@gpeal

**Comment by gpeal** [comment]
@zhuangzhitu I read through the code for ArrayList and ArrayListIterator and I don't see how this could be possible. I have never heard of anybody else having this issue either. If you could provide any repro steps, that would be necessary to fix this.

**Comment by zhuangzhitu** [comment]
> @zhuangzhitu I read through the code for ArrayList and ArrayListIterator and I don't see how this could be possible. I have never heard of anybody else having this issue either. If you could provide any repro steps, that would be necessary to fix this.

This is crash, which we use online, about 100 or so, focusing on Android 28,29. I'm not sure how this would happen unless we add a null object to lazyCompositionTasks, but looking at the code is unlikely.

**Comment by zhuangzhitu** [comment]
> @zhuangzhitu I read through the code for ArrayList and ArrayListIterator and I don't see how this could be possible. I have never heard of anybody else having this issue either. If you could provide any repro steps, that would be necessary to fix this.

Someone mentioned it. Please have a look：https://github.com/airbnb/lottie-android/issues/1407 @gpeal
