### ISSUE TITLE
FileNotFoundException while loading the animation from URL 

### ISSUE THREAD

**Issue by pattupatidar** [airbnb/lottie-android#1738]
I have one animation json hosted at my server. When I try to load the animation using setAnimation(url) in my **Android** application sometimes it is showing **FileNotFoundException**. 
Please Note: The animation file name which is hosted on my server is: lottie_animation.json. Mostly I am able to load the animation but sometimes it is throwing **FileNotFoundException**

Caused by java.io.FileNotFoundException: /data/user/0/com.myapp/cache/lottie_network_cache/lottie_cache_httpsstaticmyapplottielottie_animationjson.temp.json (No such file or directory)
       at java.io.FileInputStream.open(FileInputStream.java)
       at java.io.FileInputStream.<init>(FileInputStream.java:146)
       at com.airbnb.lottie.network.NetworkFetcher.getResultFromConnection(NetworkFetcher.java:167)
       at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:108)
       at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:86)
       at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:52)
       at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
       at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:91)
       at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:88)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by gpeal** [comment]
@pattupatidar Can you reproduce this in the issue-repro module in the library?
