### ISSUE TITLE
I have a question about ClassCastException  🐱

### ISSUE THREAD

**Issue by is1988** [airbnb/lottie-android#1740]
**ERROR LOG**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zh.demo/com.zh.demo.ui.activity.SplashActivity}: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to com.airbnb.lottie.LottieAnimationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to com.airbnb.lottie.LottieAnimationView
        at com.zh.demo.ui.activity.SplashActivity.initView(SplashActivity.java:40)
        at com.zh.base.BaseActivity.initActivity(BaseActivity.java:38)
        at com.zh.base.BaseActivity.onCreate(BaseActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7088)
        at android.app.Activity.performCreate(Activity.java:7079)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
```

**SplashActivity**

```
public final class SplashActivity extends MyActivity {

    private LottieAnimationView mLottieView;
    private View mDebugView;

    @Override
    protected int getLayoutId() {
        return R.layout.splash_activity;
    }

    @Override
    protected void initView() {
        mLottieView = findViewById(R.id.iv_splash_lottie);
        mDebugView = findViewById(R.id.iv_splash_debug);

        mLottieView.addAnimatorListener(new AnimatorListenerAdapter() {
            @Override
            public void onAnimationEnd(Animator animation) {
                startActivity(TestHomeActivity.class);
                finish();
            }
        });
    }
```

**XML**

```
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/iv_splash_lottie"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginBottom="40dp"
        app:lottie_autoPlay="true"
        app:lottie_loop="false"
        app:lottie_rawRes="@raw/test" />
```

 _Caused by: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to com.airbnb.lottie.LottieAnimationView_

**Why?Excuse me, what did I do wrong**  🐱 🐱 🐱

**Comment by gpeal** [comment]
Unfortunately, it's not possible to tell without a full sample app but I can only provide technical support (vs bugs in the library) for GitHub sponsors at this point.
