### ISSUE TITLE
Keyframe containsProgress error #387

### ISSUE THREAD

**Issue by tuananhdtu** [airbnb/lottie-android#1772]
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
at com.airbnb.lottie.value.Keyframe.containsProgress(Keyframe.java:124)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation$KeyframesWrapperImpl.isValueChanged(BaseKeyframeAnimation.java:297)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:62)
at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:553)
at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:137)
at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:154)
at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:70)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:159)
at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:208)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:449)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:614)
at vnapps.ikara.app.view.chatroom.ChatRoomActivity$2.onAnimationEnd(ChatRoomActivity.java:522)
at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:217)
at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:453)
at com.airbnb.lottie.LottieDrawable$2.run(LottieDrawable.java:442)
at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:220)
at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:564)
at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by gpeal** [comment]
@tuananhdtu It appears that system animations are disabled. You have a few options:
1) User the built in `repeatCount` APIs to handle looping rather than calling play from onAnimationEnd.
2) Check whether system animations are disabled using the [same method as Lottie](https://github.com/airbnb/lottie-android/blob/8d0ea7d98bbd8a83d81ffed1d4f5febb9009cac4/lottie/src/main/java/com/airbnb/lottie/utils/Utils.java#L261) and don't do this if they are disabled.
3) Use 3.6.2-SNAPSHOT or wait for the upcoming 3.7.0 release where you can call `setIgnoreSystemAnimations(true)` to have it animate despite system animations being disabled.

**Comment by tuananhdtu** [comment]
Thank you @gpeal

**Comment by laurentyhuel** [comment]
> 3\. setIgnoreSystemAnimations(true)

Ma animation are not played on a specific device, now with `setIgnoreSystemAnimations`  it works,  maybe could be added to http://airbnb.io/lottie/#/android?id=troubleshooting section
