### ISSUE TITLE
com.airbnb.lottie.parser.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $

### ISSUE THREAD

**Issue by holybin** [airbnb/lottie-android#1799]
- lottie：3.5.0 release
- android：7.1.2
- my question: when i use setAnimationFromUrl to load a zip file  url （like this：http://xxx/yyy.zip）from remote，i get this error below. but when i switch to use setAnimation to load the same zip file from local, it is ok。VERY STRANGE!
> [E][2021-04-14 +8.0 15:10:38.153][1095, 2*][LottieAnimationController][, , 1095][[42549K] [playLottieAnimationFromUrl] load lottieUrl error  com.airbnb.lottie.parser.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
	at com.airbnb.lottie.parser.moshi.JsonReader.syntaxError(JsonReader.java:249)
	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:952)
	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:348)
	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:137)
	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:57)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:390)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:383)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:313)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:306)
	at com.airbnb.lottie.network.NetworkFetcher.fromJsonStream(NetworkFetcher.java:145)
	at com.airbnb.lottie.network.NetworkFetcher.fromInputStream(NetworkFetcher.java:118)
	at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:82)
	at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:43)
	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:98)
	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:95)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by gpeal** [comment]
Unfortunately, there isn't enough information to debug what is happening here. If you're able to attach a sample project that reproduces this, feel free to reopen this with it!
