### ISSUE TITLE
Crash "ClassNotFoundException" when unmarshalling on a custom wrapper over the LottieAnimationView

### ISSUE THREAD

**Issue by ashishkrishnan** [airbnb/lottie-android#1802]
Hey folks, I wasn't sure on what category I could place this before a discussion with the library maintainers. Apologies here.

I have been working with a custom view wrapper over a LottieAnimationView that provides me with
- custom APIs to control animations (We have a case where we have two different animations states when the user is online or offline)
- The wrapper maintains an internal state of its corresponding UI animation to be set.

Here is a sample of the custom SavedState that extends the BaseSavedState.
```
 class SavedState : BaseSavedState {
        var foo: Boolean = false
        var _lottieState: Parcelable? = null

        constructor() : this(null)

        constructor(superState: Parcelable?) : super(superState)

        constructor(parcel: Parcel) : super(parcel) {
            foo = parcel.readInt() == 1
            _lottieState = parcel.readParcelable(BaseSavedState::class.java.classLoader)
        }

        constructor(superState: Parcelable?, foo: Boolean) : this(superState) {
            this.foo = foo
            this._lottieState = superState
        }

        override fun writeToParcel(out: Parcel?, flags: Int) {
            super.writeToParcel(out, flags)
            out?.writeInt(if (foo) 1 else 0)
            out?.writeParcelable(_lottieState, PARCELABLE_WRITE_RETURN_VALUE)
        }

        companion object {
            @JvmField
            val CREATOR: Parcelable.Creator<SavedState> = object : Parcelable.Creator<SavedState> {
                override fun createFromParcel(source: Parcel): SavedState {
                    return SavedState(source)
                }

                override fun newArray(size: Int): Array<SavedState> {
                    return Array(size) { SavedState() }
                }
            }
        }
```
Since, the LottieAnimationView's SavedState is a private static class, we had to go with the approach to send add a property in our custom view state class and then it on the restore callback.

```
override fun onSaveInstanceState(): Parcelable {
        val superState = super.onSaveInstanceState()
        return SavedState(superState, foo)
    }

    override fun onRestoreInstanceState(state: Parcelable?) {
        val savedState = state as? SavedState
        super.onRestoreInstanceState(savedState?._lottieState)

        if (savedState != null) this.foo = savedState.foo
    }
```

The problem that we are facing is when on Android 6 and above, we reset a dangerous permission say Location and given the activity is restarted, the framework does throws an error 
```
Class not found when unmarshalling: com.airbnb.lottie.LottieAnimationView$SavedState
                         E  java.lang.ClassNotFoundException: com.airbnb.lottie.LottieAnimationView$SavedState
                         E  	at java.lang.Class.classForName(Native Method)
                         E  	at java.lang.Class.forName(Class.java:454)
                         E  	at android.os.Parcel.readParcelableCreator(Parcel.java:3338)
                         E  	at android.os.Parcel.readParcelable(Parcel.java:3272)
                         E  	at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
                         E  	at android.view.View$BaseSavedState.<init>(View.java:28688)
                         E  	at android.view.View$BaseSavedState.<init>(View.java:28677)
                         E  	at com.example.CustomLottieView$SavedState.<init>(CustomLottieView.kt:170)
                         E  	at com.example.CustomLottieView$SavedState$Companion$CREATOR$1.createFromParcel(CustomLottieView.kt:190)
                         E  	at com.example.CustomLottieView$SavedState$Companion$CREATOR$1.createFromParcel(CustomLottieView.kt:188)
                         E  	at android.os.Parcel.readParcelable(Parcel.java:3281)
                         E  	at android.os.Parcel.readValue(Parcel.java:3174)
                         E  	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
                         E  	at android.os.Parcel.readSparseArray(Parcel.java:2792)
                         E  	at android.os.Parcel.readValue(Parcel.java:3231)
                         E  	at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)

```

Is there any recommendation for a workaround?

**Comment by gpeal** [comment]
@ashishkrishnan  Could you attach a sample project the reproduces this?

**Comment by ashishkrishnan** [comment]
@gpeal Sure, will attach one!

**Comment by ashishkrishnan** [comment]
@gpeal Hey! 

I have created this pull request on my forked repo.
Please take a look

Pull request: https://github.com/ashishkrishnan/lottie-android/pull/1

Screen grab with logcat: https://github.com/ashishkrishnan/lottie-android/blob/827afb5ce38d6595baebc1d31865cb965cf4d949/issue-repro/video-sample/Screen%20Recording%202021-05-09%20at%207.28.33%20PM.mov

**Comment by gpeal** [comment]
@ashishkrishnan I was able to resolve this by passing in LottieAnimationView::class.java.classLoader as the 2nd param in this constructor:
```
        constructor(parcel: Parcel) : super(parcel, LottieAnimationView::class.java.classLoader) {
            foo = parcel.readInt() == 1
        }
```
As far as I can tell, there isn't a specific issue with the LottieAnimationView.SavedState class. Feel free to put up a PR if you think there is a change that needs to be made though.
