### ISSUE TITLE
Font asset not found

### ISSUE THREAD

**Issue by ronaldinho161** [airbnb/lottie-android#1806]
Hello,

I am trying to change text of lottie animation from Android code. I tried different animation files, but result is always 👍   java.lang.RuntimeException: Font asset not found fonts/Some Font.ttf . In the final version I have a "delete" button and I am trying to set my own text like this : 
        val textDelegate = TextDelegate(animView);
        textDelegate.setText("EDIT", "DELETE");
        animView.setTextDelegate(textDelegate);
        animView.playAnimation()

Lottie version 3.7.0
Android versions tested : 8,9,10

Is this the correct way to change the text?

**Comment by hasancse91** [comment]
@gpeal  I've faced the same issue. 
My [lottie file](https://lottiefiles.com/animations/sliced-text-choose-your-fighter-l0JPPtnja0) contains custom font. When I don't set custom delegate it's working fine. Custom font also applied. But when I set text delegate to lottie view, I got the runtime exception.

```java.lang.RuntimeException: Font asset not found fonts/Helvetica Neue LT Std.ttf
   at android.graphics.Typeface.createFromAsset(Typeface.java:1061)
   at com.airbnb.lottie.manager.FontAssetManager.getFontFamily(FontAssetManager.java:104)
   at com.airbnb.lottie.manager.FontAssetManager.getTypeface(FontAssetManager.java:65)
   at com.airbnb.lottie.LottieDrawable.getTypeface(LottieDrawable.java:1304)
   at com.airbnb.lottie.model.layer.TextLayer.getTypeface(TextLayer.java:311)
   at com.airbnb.lottie.model.layer.TextLayer.drawTextWithFont(TextLayer.java:231)
   at com.airbnb.lottie.model.layer.TextLayer.drawLayer(TextLayer.java:136)
   at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:259)
   at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
   at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:259)
   at com.airbnb.lottie.LottieDrawable.drawDirectlyToCanvas(LottieDrawable.java:1432)
   at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:527)
   at android.widget.ImageView.onDraw(ImageView.java:1446)
   at android.view.View.draw(View.java:24190)
   at android.view.View.updateDisplayListIfDirty(View.java:23056)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
   at android.view.View.updateDisplayListIfDirty(View.java:23047)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at android.view.View.updateDisplayListIfDirty(View.java:23047)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at android.view.View.updateDisplayListIfDirty(View.java:23047)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at android.view.View.updateDisplayListIfDirty(View.java:23047)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at android.view.View.updateDisplayListIfDirty(View.java:23047)
   at android.view.View.draw(View.java:23920)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4566)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4327)
   at android.view.View.draw(View.java:24193)
   at com.android.internal.policy.DecorView.draw(DecorView.java:827)
   at android.view.View.updateDisplayListIfDirty(View.java:23056)
   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
   at android.view.ViewRootImpl.draw(ViewRootImpl.java:5234)
   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4900)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4049)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
   at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
   at android.view.Choreographer.doFrame(Choreographer.java:938)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
   at android.os.Handler.handleCallback(Handler.java:959)
   at android.os.Handler.dispatchMessage(Handler.java:100)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8501)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)```
