### ISSUE TITLE
Impossible to catch exception when URL returns 404

### ISSUE THREAD

**Issue by WBertan** [airbnb/lottie-android#1810]
When loading animation with `setAnimationFromUrl` and the URL gives 404 the app crashes.
My main issue is, I could not catch this with a `try...catch`.
Do we have any way to catch and handle this case, instead of crashing the app?

```
Fatal Exception: java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:79)
       at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:72)
       at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:96)
       at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:89)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:162)
       at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:28)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:137)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 ```
 ```
 Caused by java.lang.IllegalArgumentException: Unable to fetch https://url_to_my_asset. Failed with 404
 ```

**Comment by gpeal** [comment]
@WBertan I recommend setting your own [LottieNetworkFetcher](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/network/LottieNetworkFetcher.java) in [Lottie.initialize](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/Lottie.java#L18). you can implement whatever logic you want there.

Alternatively, you can use your existing network stack to fetch the json as a string and then use the `LottieCompositionFactory` APIs to create the composition.

**Comment by WBertan** [comment]
@gpeal Thanks! Will have a look into that.
But I still think the lib should not crash the whole app if the URL returns `404`. I see as it maybe should provide something for us to handle that case directly in the class, so we can make the decision to hide the animation, or change to something else.
In the worst scenario, I would expect to at least not render anything, instead of again, crash the app.

**Comment by gpeal** [comment]
@WBertan Fair point, in general the single shot fire and forget setAnimation from a URL is not a great design in retrospect. It should probably be deprecated and replaced with something more robust. In lottie-compose, it returns a result type which is a more modern and canonical way to do it.

I haven't spent much time improving the Java API lately and would recommend using one of the above approaches for now.
