### ISSUE TITLE
IllegalStateException: Unable to parse composition

### ISSUE THREAD

**Issue by djdominoSVK** [airbnb/lottie-android#1829]
**Describe the bug**
Hi, I have animation which works fine in Web or iOS app,  but does not work on Android at all.
I also tried using animation in LottieFiles Android app and Lottie logo is loaded instead of animation.

https://lottiefiles.com/share/4gtaxcax

My app crashes after setting animation  with exception:

`    java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:79)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:72)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:96)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:89)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:162)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:28)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:137)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: com.airbnb.lottie.parser.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $
        at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:151)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:56)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:390)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:383)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:313)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:306)
        at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:269)
        at com.airbnb.lottie.LottieCompositionFactory$3.call(LottieCompositionFactory.java:234)
        at com.airbnb.lottie.LottieCompositionFactory$3.call(LottieCompositionFactory.java:229)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

**What version of Lottie did you test this on?**
Lottie 3.7.0

**What version of Android did you test this on?**
Android 11 (Samsung S10+)

**Steps To Reproduce**
App always crashes after loading animation.

It's probably problem with animation and I am really sorry to bother you, but i don't know where is the problem from this exception and on iOS platform it work's well. According to graphic designer, animation uses only features allowed in iOS & Android.

**Comment by gpeal** [comment]
This isn't a valid json file. The contents of the file are quoted and then the actual json quotes are escaped. It might work on other platforms because they might be auto-unescaping the text or due to some other implementation detail but because this isn't actually valid json as-is, the expectation is that this won't work on Android.

**Comment by kkuby** [comment]
I solved this same parse error.
I deleted ' \ ' and first and last's ' " ' in my json lottie file.
You can compare your json file with any free animation json in (https://lottiefiles.com/featured).
