### ISSUE TITLE
Migrate app:lottie_colorFilter to compose

### ISSUE THREAD

**Issue by KristapsKrumins** [airbnb/lottie-android#1835]
How to set XML attribute app:lottie_colorFilter in compose? From docs it seems that I need to use rememberLottieDynamicProperty, but I dont know what to pass in keyPath.
```
val dynamicProperties = rememberLottieDynamicProperties(
                    rememberLottieDynamicProperty(
                        property = LottieProperty.COLOR_FILTER,
                        value = Color.Black.toArgb(),
                        keyPath = arrayOf(KeyPath.COMPOSITION.keysToString())
                    ),
                )
```

**Comment by gpeal** [comment]
Use `**`. That's all LottieAnimationView does under the hood
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L208

**Comment by KristapsKrumins** [comment]
@gpeal This also does not work, loading animation is white and not black.
```
val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.loading))
val dynamicProperties = rememberLottieDynamicProperties(
                    rememberLottieDynamicProperty(
                        property = LottieProperty.COLOR_FILTER,
                        value = Color.Black.toArgb(),
                        keyPath = arrayOf(KeyPath("**").keysToString())
                    ),
                )
LottieAnimation(
                    composition,
                    iterations = Int.MAX_VALUE,
                    dynamicProperties = dynamicProperties
                )
```

**Comment by gpeal** [comment]
It's `arrayOf("")` or removed the named parameters and use `rememberLottieDynamicProperty(LottieProperty.COLOR_FILTER. Color.Black.toArgb(), "**")`

In you're code, you're stringifying the KeyPath object.

**Comment by KristapsKrumins** [comment]
@gpeal This results in crash
```
at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:31)
    java.lang.ClassCastException: java.lang.Integer cannot be cast to android.graphics.ColorFilter
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
        at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:46)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:31)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
        at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1284)
        at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:403)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:393)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:247)
        at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1284)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$2.invoke(LottieAnimation.kt:84)
        at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:403)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$2.invoke(LottieAnimation.kt:69)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:393)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:101)
```

**Comment by gpeal** [comment]
@KristapsKrumins The code I wrote was just off the top of my head. Please refer to the code I linked to see what `LottieAnimationView` does under the hood
```kotlin
rememberLottieDynamicProperty(LottieProperty.COLOR_FILTER. SimpleColorFilter(Color.Black.toArgb()), "**")
```

**Comment by KristapsKrumins** [comment]
Thanks, the following code does the job
```
rememberLottieDynamicProperty(
                        property = LottieProperty.COLOR_FILTER,
                        value = SimpleColorFilter(Color.Black.toArgb()),
                        keyPath = arrayOf("**")
                    )
```
