### ISSUE TITLE
FillContent ANR

### ISSUE THREAD

**Issue by kshitiz-dunzo** [airbnb/lottie-android#1889]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Describe the bug**
We have used lottie in our android app. We run it endlessly in a loop unless the user decides to exit the activity by pressing back button or kills the app. We are getting a lot of ANRs on our crashlytics because of this.

**Steps To Reproduce**

1. Add a lottie animation view.
2. Keep the animation running in a loop endlessly.
3. This ANR might happen

Logs from our crashlytics:
Caused by com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
       at java.util.Arrays.copyOf(Arrays.java:3136)
       at java.util.Arrays.copyOf(Arrays.java:3106)
       at java.util.ArrayList.grow(ArrayList.java:275)
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
       at java.util.ArrayList.add(ArrayList.java:467)
       at com.airbnb.lottie.animation.content.FillContent.setContents(FillContent.java:71)
       at com.airbnb.lottie.animation.content.ContentGroup.setContents(ContentGroup.java:113)
       at com.airbnb.lottie.animation.content.ContentGroup.setContents(ContentGroup.java:113)
       at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:26)
       at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:46)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:298)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:503)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:80)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:78)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7807)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by gpeal** [comment]
@kshitiz-dunzo Do you need to call `setComposition` every time?

**Comment by kshitiz-dunzo** [comment]
@gpeal no. Basically we get a url from our backend through which we load the animations. The URL changes after every x seconds through a polling API and then we have to change the animation. This is our code to load them:

`fun setAnimation(animationUrl: String) {
		animationView.visibility = VISIBLE
		try {
			animationView.setAnimationFromUrl(animationUrl)
		} catch (e: MalformedURLException) {
			Log.logException(Throwable("Invalid animation url - $animationUrl"))
			return
		}
		animationView.repeatCount = INFINITE
		animationView.playAnimation()
	}`

**Comment by gpeal** [comment]
@kshitiz-dunzo I'm not sure what can be done here, to be honest. This ANR inside of ArrayList. Are the stack traces from all ANRs identical?

**Comment by kshitiz-dunzo** [comment]
@gpeal I feel it's not related to array list. Here are some more logs(This happens inside the draw method in FillContent):

Caused by com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
       at java.lang.Object.internalClone(Object.java)
       at java.lang.Object.clone(Object.java:259)
       at android.graphics.ColorSpace$Named.values(ColorSpace.java:231)
       at android.graphics.ColorSpace.get(ColorSpace.java:1383)
       at android.graphics.Color.colorSpace(Color.java:704)
       at android.graphics.Paint.setAlpha(Paint.java:1126)
       at com.airbnb.lottie.animation.content.FillContent.draw(FillContent.java:87)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:113)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:222)
       at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1221)
       at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:380)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:370)
       at android.widget.ImageView.onDraw(ImageView.java:1434)
       at android.view.View.draw(View.java:21768)
       at android.view.View.updateDisplayListIfDirty(View.java:20640)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
       at android.view.View.updateDisplayListIfDirty(View.java:20596)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3756)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3560)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2891)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1796)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7831)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7438)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:989)

**Comment by kshitiz-dunzo** [comment]
Lottie version that we are using: 3.4.0

**Comment by gpeal** [comment]
@kshitiz-dunzo that's a different stack than your first one and is still an ANR inside of Android APIs, not Lottie which indicates to me that this issue isn't specific to Lottie. Lottie just happens to be in the stack trace when it ANRs. Without a repro, I don't think I'll be able to help here.

**Comment by kshitiz-dunzo** [comment]
@gpeal okay. Can you give me some insights on the performance impact a lottie animation might have on a device if it's running endlessly? We are basically setting the animation via a URL that we get from our backend and this URL changes after every "x" mins. Once set the animation repeats infinitely.

**Comment by kshitiz-dunzo** [comment]
@gpeal I highly doubt that users play around with developer options and even the ones that do would have their animations disabled. Battery saver can be a good lead, if the batter saver does disable animations then is there a workaround in lottie for it?

Also I was reading some of lottie's code and as we are setting animation via URL, it does call setComposition again internally. And as it is a different animation IMO it won't return from the if check inside the setComposition as well. Is this ok?

**Comment by gpeal** [comment]
@kshitiz-dunzo At scale, tons of users mess with animation scale on their actual devices. You will have a combination of real developers + people who just want to disable animations going in there and messing with settings.

**Comment by gpeal** [comment]
@kshitiz-dunzo I'm going to have to close this because I don't think there is anything actionable to be done on the Lottie side here.
