### ISSUE TITLE
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0 in lottie library

### ISSUE THREAD

**Issue by RohanBhagat1** [airbnb/lottie-android#1921]
Hi, I am facing an issue with the Lottie animation.
The json file I am trying to render in the android app is not rendering. The stack trace I am getting is added below.
Though the json file is running appropriately on Lottie site.

StackTrace:
2021-10-12 14:56:15.392 11174-11174/in.ludo.supremegold E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.ludo.supremegold, PID: 11174
    java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:78)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:71)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:95)
        at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:88)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
        at java.lang.String.charAt(Native Method)
        at android.graphics.Color.parseColor(Color.java:1384)
        at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:129)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:121)
        at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:87)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:390)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:383)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:313)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:306)
        at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:196)
        at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:161)
        at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:158)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

Lottie lib version: 4.1.0
json file link: https://drive.google.com/file/d/1MuToXXYAF2XAtmbWan7Ha7rQRdfhve1j/view?usp=sharing

Please share what is the issue. Is it with respect to json or somewhat in the internal parsing

**Comment by gpeal** [comment]
There is a solid layer with a missing color. You can see it in the json where it says `sc: ""` That should have a color value. Either your json has been manipulated or there is a bug in whatever tools or plugin you used to manipulate it. As a test, I replaced it with `sc: "#ff0000"` and it rendered just fine.

**Comment by Semper-Viventem** [comment]
I faced the same issue and was confused that this string works fine on iOS and the web but leads to a crash on Android. Maybe it's better to clarify an exception message or make behavior consistent between platforms?
