### ISSUE TITLE
NullPointerException crash in LottieComposition.getLayers()

### ISSUE THREAD

**Issue by chinalwb** [airbnb/lottie-android#1958]
**Describe the bug**
Race condition caused NPE.

See the exception stack below:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.airbnb.lottie.LottieComposition.getLayers()' on a null object reference
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:298)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:504)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:81)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:79)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

This is a race condition issue so not always reproducible.

I was using version 3.4.1, but I checked the code in master branch, the key part to this issue keeps the same between version 3.4.1 and the latest version 4.2.2.

**Steps To Reproduce**
Race condition issue, there is no fix steps to reproduce.

See the issue analysis in PR #1959 .

**Comment by WilbertClark** [comment]
Hello hello I understand the digital breakdown of the data to form receipts
codes now what they call promo codes and other transactions are receipts of
transactioning a cell data deletion and everything that the membrane pulls
up and you guys you need codes using numbers YZ 8 through zero g and H2 x
so I'm just saying the codes that now or not much of a key as a skeleton
key or a key to the state or key to other businesses these are basically
promo codes and Kohl's to you guys company of sales put outs inputs and
receipts therefore I would not indulge still transact structure makeup draw
anything from you guys state of data to so what call a key to spend on Nerf
years communication etc I would rather have my money a trust funding the
bank with a bank account of my own instead of to be penalized and you guys
report me back to the people that I invest with as Steph robbery class at a
felony FBI approved and it's insurance another choice that adds up to five
days to a year Day to a year etc thank you
