### ISSUE TITLE
Crash: Curves must have the same number of control points

### ISSUE THREAD

**Issue by m1ga** [airbnb/lottie-android#197]
Playing the "I'm thirsty" animation from LottieFiles (http://www.lottiefiles.com/download/77) produces this error on Android:

```
Sending event: exception on thread: main msg:java.lang.IllegalStateException: Curves must have the same number of control points. This: 5	Shape 1: 7	Shape 2: 7; Titanium 6.0.2,2017/02/24 11:22,undefined
[ERROR] TiApplication: java.lang.IllegalStateException: Curves must have the same number of control points. This: 5	Shape 1: 7	Shape 2: 7
[ERROR] TiApplication: 	at com.airbnb.lottie.ShapeData.interpolateBetween(ShapeData.java:58)
[ERROR] TiApplication: 	at com.airbnb.lottie.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:19)
[ERROR] TiApplication: 	at com.airbnb.lottie.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:7)
[ERROR] TiApplication: 	at com.airbnb.lottie.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:114)
[ERROR] TiApplication: 	at com.airbnb.lottie.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:54)
[ERROR] TiApplication: 	at com.airbnb.lottie.BaseLayer.setProgress(BaseLayer.java:227)
[ERROR] TiApplication: 	at com.airbnb.lottie.CompositionLayer.setProgress(CompositionLayer.java:60)
[ERROR] TiApplication: 	at com.airbnb.lottie.LottieDrawable.setProgress(LottieDrawable.java:252)
[ERROR] TiApplication: 	at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:54)
[ERROR] TiApplication: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
[ERROR] TiApplication: 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1298)
[ERROR] TiApplication: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1339)
[ERROR] TiApplication: 	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:715)
[ERROR] TiApplication: 	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
[ERROR] TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
[ERROR] TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
[ERROR] TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:559)
[ERROR] TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
[ERROR] TiApplication: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

using the latest Lottie-android or using the Lottie Android app (version 1.5.3)
No crash on iOS btw.

**Comment by gpeal** [comment]
@m1ga That animation was exported with a very old version of bodymovin. I'm currently working with him to get an updated version on the site. Lottiefiles also added a disclaimer for animations that were exported with old versions.

**Comment by m1ga** [comment]
👍 thank you  once again 😄
