### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Paint$Cap com.airbnb.lottie.model.content.ShapeStroke$LineCapType.toPaintCap()' on a null object reference

### ISSUE THREAD

**Issue by yifei8** [airbnb/lottie-android#1988]
api 'com.airbnb.android:lottie:4.2.2'

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Paint$Cap com.airbnb.lottie.model.content.ShapeStroke$LineCapType.toPaintCap()' on a null object reference
        at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:29)
        at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:82)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:35)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:31)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:58)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:318)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:217)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:586)
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:148)
        at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:28)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:135)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8215)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by gpeal** [comment]
@yifei8 Can you attach your json file? I think it may be missing a value? Was it exported with Bodymovin in After Effects or something else?

**Comment by gpeal** [comment]
I'm auto closing this because you didn't follow the issue template but feel free to reopen it with the required information.
