### ISSUE TITLE
my App crash when I use it to back to another Fragment

### ISSUE THREAD

**Issue by gkj17** [airbnb/lottie-android#1989]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. Fork this repository into your account.
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.

**Link to fork with a repro in the issue-repro module**

**Describe the bug**

**Steps To Reproduce**

I have 2 fragment with Lottie , but when I back from fragmentA to fragmentB, my App crash,and logcat show me the error message like:
java.lang.ClassCastException: com.airbnb.lottie.LottieAnimationView$SavedState cannot be cast to android.widget.ProgressBar$SavedState
        at android.widget.ProgressBar.onRestoreInstanceState(ProgressBar.java:2263)
        at android.view.View.dispatchRestoreInstanceState(View.java:20896)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4071)
        at android.view.View.restoreHierarchyState(View.java:20874)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:640)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3008)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2999)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:559)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:262)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1717)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1654)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:8158)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:959)

**Comment by gpeal** [comment]
Can you attach a sample project that reproduces this?

**Comment by gkj17** [comment]
I've solved this problem, it's not a Lottie problem, but I have a little experience in making mistakes: the id of LottieAnimationView is loading, but I have another view whose id is also loading (a third-party video library), so this problem occurs.

**Comment by gkj17** [comment]
Thank you very much for noticing!
