### ISSUE TITLE
Shape data was missing information in R8 obfuscating mode

### ISSUE THREAD

**Issue by AlexeyPanchenko** [airbnb/lottie-android#2014]
**Describe the bug**

When I use lottie with APG 3.6.4 and proguard (`isMinifyEnabled = true`) it works correctly. But when I update AGP to 7.0.4 with forced R8 (`isMinifyEnabled = true`) I get an error:

```
java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$a.onResult(SourceFile:5)
        at com.airbnb.lottie.LottieAnimationView$c.onResult(SourceFile:8)
        at hi6.run(SourceFile:20)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Shape data was missing information.
        at y1b.a(SourceFile:35)
        at gu5.a(SourceFile:47)
        at hu5.a(SourceFile:15)
        at yr1.a(SourceFile:75)
        at yr1.a(SourceFile:160)
        at pw5.a(SourceFile:65)
        at yh6.a(SourceFile:95)
        at com.airbnb.lottie.a.c(SourceFile:1)
        at com.airbnb.lottie.a.b(SourceFile:3)
        at com.airbnb.lottie.c.call(SourceFile:5)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

If disable R8 (`isMinifyEnabled = false`) with AGP 7.0.4 it works correctly.

**Steps To Reproduce**

1. Update AGP to 7.0.4
2. Build with `isMinifyEnabled = true`
3. Call `setAnimation(rawResId)`

**Comment by gpeal** [comment]
AGP gets tighter with every app version. Lots of apps (including ours at Tonal) are using R8 with AGP 7/7.1 without issue. I would look into your proguard config and see if you can debug the issue. If you can reproduce this in a sample app, feel free to reopen this with it.
