### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by shrastiRisor** [airbnb/lottie-android#2021]
ANR during Animation

main (runnable): tid=1 systid=17909
       at android.widget.ImageView.getDrawable(ImageView.java:456)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:505)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:80)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:78)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:938)

Android 11
vivo 1915
It was reported on Crashlytics

**Comment by gpeal** [comment]
This is unlikely due to Lottie itself and likely due to overall OS performance and it just happened to trigger the ANR here.
