### ISSUE TITLE
Unable to open asset.     java.io.FileNotFoundException: at android.content.res.AssetManager.nativeOpenAsset

### ISSUE THREAD

**Issue by sanketkoladiya** [airbnb/lottie-android#2043]
I am trying to load the animation from network. I am downloading the zip file in cache of application and then unzip the zip and assign the **setImageAssetsFolder()** and load the json file programmatically as well. Now the issue is that json file is working file means my transition of images is showing but the image is not loading even after setting the AssetFolder properly. I double check the images is present or not. its there but still getting the below exception.

Unable to open asset.
    java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.myapplication/cache/Resource/previewRender/images/img_9.png
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:881)
        at android.content.res.AssetManager.open(AssetManager.java:858)
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:108)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1100)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:70)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:35)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)
        at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1297)
        at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:403)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:393)
        at android.widget.ImageView.onDraw(ImageView.java:1444)
        at android.view.View.draw(View.java:22528)
        at android.view.View.buildDrawingCacheImpl(View.java:21791)
        at android.view.View.buildDrawingCache(View.java:21646)
        at com.airbnb.lottie.LottieAnimationView.buildDrawingCache(LottieAnimationView.java:1085)
        at android.view.View.draw(View.java:22246)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at com.android.internal.policy.DecorView.draw(DecorView.java:812)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4442)

i am using the below dependencies:

**implementation 'com.airbnb.android:lottie:4.2.2'**

I am testing the application on Android 11 version. Storage and all permission is granted. Any help would be appreciated.

**Comment by gpeal** [comment]
You don't need to unzip your downloaded file. You may point Lottie at the ZipInputStream and it will unzip it and automatically link your images.
The assets for `setImageAssetsFolder` would be part of the assets compiled into your APK and probably not what you're looking for here.
