### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by dilkw** [airbnb/lottie-android#2050]
Hello, my app crashed suddenly, a total of 40 crashes, affecting 40 users, I hope to get your help, the crash information is as follows:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.airbnb.lottie.v.a.h()' on a null object reference
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getInterpolatedCurrentKeyframeProgress(BaseKeyframeAnimation.java:104)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:128)
       at com.airbnb.lottie.model.layer.BaseLayer.setupInOutAnimations(BaseLayer.java:157)
       at com.airbnb.lottie.model.layer.BaseLayer.<init>(BaseLayer.java:122)
       at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:21)
       at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:46)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:290)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:484)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:80)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:78)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7359)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by gpeal** [comment]
@dilkw Are there any patterns such as Android OS versions?

**Comment by dilkw** [comment]
> @dilkw Are there any patterns such as Android OS versions?

Android os: 10
Device: Xiaomi

**Comment by gpeal** [comment]
@dilkw 100% Android 10 Xiaomi?

**Comment by dilkw** [comment]
> @dilkw 100% Android 10 Xiaomi?

yes

**Comment by dilkw** [comment]
Hi, how should I solve this problem?

**Comment by mitulbharatchandra** [comment]
Hi there, I also started getting same crash.
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void com.airbnb.lottie.LottieAnimationView.h()' on a null object reference
