### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'void com.airbnb.lottie.q.c.a.a(com.airbnb.lottie.q.c.a$b)' on a null object reference

### ISSUE THREAD

**Issue by yushiwo** [airbnb/lottie-android#2058]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.airbnb.lottie.q.c.a.a(com.airbnb.lottie.q.c.a$b)' on a null object reference
at com.airbnb.lottie.animation.content.TrimPathContent.(TrimPathContent.java:32)
at com.airbnb.lottie.model.content.ShapeTrimPath.toContent(ShapeTrimPath.java:69)
at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
at com.airbnb.lottie.animation.content.ContentGroup.(ContentGroup.java:67)
at com.airbnb.lottie.model.layer.ShapeLayer.(ShapeLayer.java:26)
at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:55)
at com.airbnb.lottie.model.layer.CompositionLayer.(CompositionLayer.java:56)
at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:58)
at com.airbnb.lottie.model.layer.CompositionLayer.(CompositionLayer.java:56)
at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:322)
at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:221)
at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:586)
at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:148)
at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:28)
at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:135)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6211)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by gpeal** [comment]
Can you attach your animation?

**Comment by gpeal** [comment]
I'll close this until you attach your animation. Feel free to reopen it with the animation though.
