### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by aliceInWahed** [airbnb/lottie-android#2083]
hi @gpeal, I had the same issues, affecting user on Android 8.1, 9, and 11. these errors are being captured by firebase Crashlytics and Sentry

line 244
<img width="626" alt="Screenshot 2022-05-26 at 1 36 07 PM" src="https://user-images.githubusercontent.com/79141836/170425201-3903d891-8a87-470d-9291-66559689ec54.png">

line 241 Android 7, 9, 11, 12
<img width="626" alt="Screenshot 2022-05-26 at 1 56 31 PM" src="https://user-images.githubusercontent.com/79141836/170426268-fdeb16da-44ff-4863-9a67-c25ecea0bc7c.png">

Can we add the null checking for the lines above just like what had implemented below?
<img width="875" alt="Screenshot 2022-05-26 at 1 26 19 PM" src="https://user-images.githubusercontent.com/79141836/170426366-481a1ab3-66a3-4121-9989-2e24b5b701b2.png">

_Originally posted by @aliceInWahed in https://github.com/airbnb/lottie-android/issues/1650#issuecomment-1138179169_

**Comment by gpeal** [comment]
Does this happen all the time or only sometimes? What version of Lottie are you using? Can you attach your animation?

I don't think your suggestion will fix this issue. The stack trace indicates that an `Integer` value is null, not `parentLayers`.

**Comment by msaikrishna** [comment]
Hey @gpeal thanks for the fix. When can we expect this to be a part of a release? Currently this crashes accounts to be the highest out of others

**Comment by gpeal** [comment]
@msaikrishna Should be soon! You can use a SNAPSHOT or compile your own release if it's an emergency.

**Comment by fengruyi** [comment]
how to get SNAPSHOT version,thanks

**Comment by gpeal** [comment]
Add the `https://oss.sonatype.org/content/repositories/snapshots` maven repo url then you should be able to use `5.3.0-SNAPSHOT`

**Comment by Sky24n** [comment]
> Add the `https://oss.sonatype.org/content/repositories/snapshots` maven repo url then you should be able to use `5.3.0-SNAPSHOT`

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.airbnb.android:lottie:5.3.0-SNAPSHOT.

**Comment by sandeepyohans** [comment]
Hi @gpeal , I am getting same NPE in 6.0.0 version also. Upgraded Lottie version in my Android app from 4.1.0 for the same issue. Checked it on Android 10 and 12. What shall I do?

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                 	at com.airbnb.lottie.model.layer.SolidLayer.drawLayer(SolidLayer.java:43)
                 	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:259)
                 	at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
                 	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:259)
                 	at com.airbnb.lottie.LottieDrawable.renderAndDrawAsBitmap(LottieDrawable.java:1496)
                 	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:525)
                 	at android.widget.ImageView.onDraw(ImageView.java:1442)
                 	at android.view.View.draw(View.java:22644)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21519)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
                 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
                 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
                 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
                 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4421)
                 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4149)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3309)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8658)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                 	at android.view.Choreographer.doFrame(Choreographer.java:780)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7839)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
