### ISSUE TITLE
 java.lang.RuntimeException: Font asset not found

### ISSUE THREAD

**Issue by sanketkoladiya** [airbnb/lottie-android#2092]
I am showing the lottie preview  from the zip (from server) by using LottieCompositionFactory.fromZipStream() method . zip file contain the data.json, images (folder), fonts folder with .ttf file but still I am getting below exception.

java.lang.RuntimeException: Font asset not found fonts/Winter_Sans.ttf
        at android.graphics.Typeface.createFromAsset(Typeface.java:992)
        at com.airbnb.lottie.manager.FontAssetManager.getFontFamily(FontAssetManager.java:90)
        at com.airbnb.lottie.manager.FontAssetManager.getTypeface(FontAssetManager.java:64)
        at com.airbnb.lottie.LottieDrawable.getTypeface(LottieDrawable.java:1242)
        at com.airbnb.lottie.model.layer.TextLayer.getTypeface(TextLayer.java:303)
        at com.airbnb.lottie.model.layer.TextLayer.drawTextWithFont(TextLayer.java:236)

Any help would be appreciated.

**Comment by sanketkoladiya** [comment]
@gpeal  can you please help me put. The zip file from raw folder also giving the same error when i try to preview from res/raw folder in android.

**Comment by sanketkoladiya** [comment]
@gpeal  i already embed the fonts in zip files. when i try to preview the zip https://lottiefiles.com/preview here its working perfect. for android i added my fonts in fonts folder along with the images and data.json . can you tell me how i can put font in zip file for preview from zip ?

**Comment by gpeal** [comment]
@sanketkoladiya It will be in the next release. Or you can use `5.2.1-SNAPSHOT` now.

**Comment by Astarconcepts** [comment]
So fonts should be added in new a folder 
images
fonts/font.ttf
data.json 

Like this?
