### ISSUE TITLE
NullPointerException: pathGroups can contain null entry

### ISSUE THREAD

**Issue by Kevinrob** [airbnb/lottie-android#210]
I have a crash with a specific JSON with this stackstrace:

```
java.lang.NullPointerException: Attempt to read from field 'java.util.List com.airbnb.lottie.StrokeContent$PathGroup.paths' on a null object reference
      at com.airbnb.lottie.StrokeContent$PathGroup.access$100(StrokeContent.java:256)
      at com.airbnb.lottie.StrokeContent.getBounds(StrokeContent.java:207)
      at com.airbnb.lottie.ContentGroup.getBounds(ContentGroup.java:175)
      at com.airbnb.lottie.ContentGroup.getBounds(ContentGroup.java:175)
      at com.airbnb.lottie.ShapeLayer.getBounds(ShapeLayer.java:29)
      at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:165)
      at com.airbnb.lottie.CompositionLayer.drawLayer(CompositionLayer.java:54)
      at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:160)
      at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:207)
      at android.widget.ImageView.onDraw(ImageView.java:1316)
      [...]
```

I use `com.airbnb.android:lottie:2.0.0-beta2` but the app crash with `1.5.3` too.

When runtime reach this code:
```java
    PathGroup currentPathGroup = null;
    for (int i = contentsAfter.size() - 1; i >= 0; i--) {
      Content content = contentsAfter.get(i);
      if (content instanceof TrimPathContent &&
          ((TrimPathContent) content).getType() == ShapeTrimPath.Type.Individually) {
        if (currentPathGroup != null) {
          pathGroups.add(currentPathGroup);
        }
        currentPathGroup = new PathGroup((TrimPathContent) content);
        ((TrimPathContent) content).addListener(this);
      } else if (content instanceof PathContent) {
        if (currentPathGroup == null) {
          currentPathGroup = new PathGroup(trimPathContentBefore);
        }
        currentPathGroup.paths.add((PathContent) content);
      }
    }
    pathGroups.add(currentPathGroup);
```

`contentsAfter.size() == 2`
So, `currentPathGroup == null`, and this code don't check for null value:

```
    path.reset();
    for (int i = 0; i < pathGroups.size(); i++) {
      PathGroup pathGroup = pathGroups.get(i);
      for (int j = 0; j < pathGroup.paths.size(); j++) {
        path.addPath(pathGroup.paths.get(i).getPath(), parentMatrix);
      }
    }
    path.computeBounds(rect, false);
```

Tell me if you need the JSON file, but it work with HTML.

**Comment by Kevinrob** [comment]
Thanks @gpeal! it works well!
