### ISSUE TITLE
NullPointerException when trying to render animation file

### ISSUE THREAD

**Issue by mnayef95** [airbnb/lottie-android#2134]
**Describe the bug**
I'm trying to use this [animation file](https://lottiefiles.com/7574-like) however the Lottie is crashing with 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableColorValue.createAnimation()' on a null object reference
                 	at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:35)
                 	at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:81)
                 	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                 	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:61)
                 	at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:35)
                 	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                 	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:61)
                 	at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
                 	at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:47)
                 	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                 	at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:50)
                 	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                 	at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:50)
                 	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                 	at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:250)
                 	at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:212)
                 	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:386)
                 	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:69)
                 	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:67)
                 	at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
                 	at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
                 	at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8751)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**What version of Lottie did you test this on?**
I tested on all versions from `2.7.0` to `5.2.0`

**What version of Android did you test this on?**
Samsung Galaxy Note 10+ Android 12

**Steps To Reproduce**
Just use this [animation file](https://lottiefiles.com/7574-like) and the app will crash

**Comment by gpeal** [comment]
Lottie's parsing is sensitive to the order of properties because it uses an in-order streaming parser. Your json file was modified such that the layer type stroke was _after_ its color. That caused Lottie to skip over the color parsing.

For performance reasons, the JSON _must_ have the layer type property before any other field or else Lottie will skip over it not knowing how to handle it.

This works on web because JSON is a first class citizen in Javascript and it doesn't have to go through this step.

<details>
<summary>Before</summary>

![before](https://user-images.githubusercontent.com/1307745/204068007-10b62255-3c00-4ea0-96b8-99e5926b1a75.png)

</details>

<details>
<summary>AFter</summary>

![after](https://user-images.githubusercontent.com/1307745/204068009-c9877ecb-0d37-41ed-a679-c4342d2a5494.png)

</details>

[Here](https://github.com/airbnb/lottie-android/files/10095475/2134.json.zip) is the fixed json.
