### ISSUE TITLE
 java.lang.IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by alenloncaric** [airbnb/lottie-android#2141]
Hi guys,

using api > 26 lottie works without a problem, but when using api <27 when debugging i get this error if I don't pause lottie before i enter debugging. It is not always but it happens quite often

Lottie version: implementation 'com.airbnb.android:lottie:5.2.0'

   --------- beginning of crash
2022-10-11 11:53:14.119 10411-10411/com.xxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxx, PID: 10411
    java.lang.IllegalStateException: Underflow in restore - more restores than saves
        at android.graphics.Canvas.native_restore(Native Method)
        at android.graphics.Canvas.restore(Canvas.java:522)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:131)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
        at com.airbnb.lottie.LottieDrawable.renderAndDrawAsBitmap(LottieDrawable.java:1418)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:515)
        at android.widget.ImageView.onDraw(ImageView.java:1298)
        at android.view.View.draw(View.java:17215)
        at android.view.View.updateDisplayListIfDirty(View.java:16197)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16160)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6350)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by gpeal** [comment]
Can you attach an animation or something else that would help me repro this?

**Comment by gpeal** [comment]
Closing due to a lack of repro.
