### ISSUE TITLE
com.airbnb.lottie.LottieComposition.getDuration()' on a null object reference

### ISSUE THREAD

**Issue by XuanNguyen12** [airbnb/lottie-android#2159]
I had the same issue, affecting only Vivo android 12 device users. These errors are being logged by firebase Crashlytics:

Lottie version: 4.2.1 and  5.2.0
My code:

 lottieAnimationView.setAnimation("quick_boost.json")

![image](https://user-images.githubusercontent.com/117880646/200986019-67196897-45e9-46e0-94a5-5fde00c3f7fa.png)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float com.airbnb.lottie.LottieComposition.getDuration()' on a null object reference
       at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:74)
       at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:79)
       at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
       at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
       at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:35)
       at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:37)
       at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:68)
       at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:31)
       at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:58)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:56)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:318)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:217)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:586)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:148)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:28)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:135)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8348)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by XuanNguyen12** [comment]
@gpeal when do you have a release to fix this bug?
