### ISSUE TITLE
NPE: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

### ISSUE THREAD

**Issue by danmov26** [airbnb/lottie-android#2194]
```
Non-fatal Exception: java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
       at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.getMatrix(TransformKeyframeAnimation.java:232)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
       at com.airbnb.lottie.LottieDrawable.drawDirectlyToCanvas(LottieDrawable.java:1354)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:517)
       at android.widget.ImageView.onDraw(ImageView.java:1453)
       at android.view.View.draw(View.java:23901)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.draw(View.java:23904)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.draw(View.java:23904)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Got a message from Firebase Crashlytics - Galaxy A10. Using latest 5.2.0 version.
I see you have already fixed this in the same method `getMatrix()` for positionValue:
`positionValue != null && (positionValue.x != 0 || positionValue.y != 0)`

Сould you please fix it for anchorPointValue that way? Now:
`anchorPointValue.x != 0 || anchorPointValue.y != 0`
TO
`anchorPointValue != null && (anchorPointValue.x != 0 || anchorPointValue.y != 0)`

**Comment by gpeal** [comment]
Is it only happening with a specific anything? Only on specific devices, Android versions, manufacturers, etc?

**Comment by danmov26** [comment]
Hello. Thanks for answer. This only happened once on this phone Galaxy A10 (Android 11).

**Comment by danmov26** [comment]
In this video I show you Lottie animation

https://user-images.githubusercontent.com/66782790/205353419-4660f20a-9ba6-4f37-adfb-3c2ea5395b33.mp4

**Comment by danmov26** [comment]
I just tested on galaxy a10 in BrowserStack emulator. No errors.

**Comment by gpeal** [comment]
5.3.0-SNAPSHOT will have it

**Comment by danmov26** [comment]
I offer a thousand apologies. Android studio cannot find this version. Help me please.
![Снимок экрана 2022-12-08 005139](https://user-images.githubusercontent.com/66782790/206304763-b136024a-ef46-46e3-ae04-0e9b07b4ea4d.png)

**Comment by gpeal** [comment]
You have to add the maven snapshot repository `https://oss.sonatype.org/content/repositories/snapshots/`

**Comment by danmov26** [comment]
Thank you very much!

**Comment by danmov26** [comment]
Good day, [gpeal](https://github.com/gpeal)!

I got new same error but from another place:

```
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
       at com.airbnb.lottie.animation.content.EllipseContent.getPath(EllipseContent.java:86)
       at com.airbnb.lottie.animation.content.BaseStrokeContent.draw(BaseStrokeContent.java:201)
       at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:48)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:36)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
       at com.airbnb.lottie.LottieDrawable.drawDirectlyToCanvas(LottieDrawable.java:1354)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:517)
       at android.widget.ImageView.onDraw(ImageView.java:1367)
       at android.view.View.draw(View.java:19275)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.draw(View.java:19278)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.draw(View.java:19278)
       at com.android.internal.policy.DecorView.draw(DecorView.java:788)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3013)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2817)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2370)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1403)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6790)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:778)
       at android.view.Choreographer.doFrame(Choreographer.java:713)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

![Снимок экрана 2022-12-10 173725](https://user-images.githubusercontent.com/66782790/206860693-5e847075-178f-48f8-a652-e850b4948e93.png)

This user still uses library version 5.2.0

And here is the code from EllipseContent.java:86
```
85: PointF size = sizeAnimation.getValue();
86: float halfWidth = size.x / 2f;
87: float halfHeight = size.y / 2f;
```

It seems that we need to add a check for null here too.
