### ISSUE TITLE
Non-fatal Exception: java.lang.IllegalStateException: Unable to parse composition

### ISSUE THREAD

**Issue by arpitkushwaha** [airbnb/lottie-android#2199]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the animation part that doesn't work.

**Describe the bug**
Hello, I am facing the below crash in production. Can you please provide some insights on why this is happening and how to prevent this? Getting below stack trace:

```
Non-fatal Exception: java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:72)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:70)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
       at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:260)
       at android.app.ActivityThread.main(ActivityThread.java:8269)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**What version of Lottie did you test this on?**
lottieVersion = "3.0.3"

**What version of Android did you test this on?**
Android 11,12,8,9

**Steps To Reproduce**
I could not reproduce it. It is happening in production.

**Screenshots**

**Comment by gpeal** [comment]
1. You are using a very old version of Lottie. Could you upgrade?
2. Could you attach your animation? Without it, I can't provide any assistance.

**Comment by arpitkushwaha** [comment]
Thanks for the reply @gpeal. I will upgrade Lottie's version and analyze the crash logs for the next production build, if something comes up I will revert back to this thread and attach the animation.

Thanks for your assistance.

**Comment by tauseeqafzal0850** [comment]
implementation "com.airbnb.android:lottie:4.2.0"
   
  and in XML 
  app:lottie_rawRes="@raw/animation"
