### ISSUE TITLE
NullPointerException: float android.graphics.PointF.x in EllipseContent.java line 86

### ISSUE THREAD

**Issue by danmov26** [airbnb/lottie-android#2206]
```
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
       at com.airbnb.lottie.animation.content.EllipseContent.getPath(EllipseContent.java:86)
       at com.airbnb.lottie.animation.content.BaseStrokeContent.draw(BaseStrokeContent.java:201)
       at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:48)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:185)
       at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:36)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
       at com.airbnb.lottie.LottieDrawable.drawDirectlyToCanvas(LottieDrawable.java:1354)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:517)
       at android.widget.ImageView.onDraw(ImageView.java:1367)
       at android.view.View.draw(View.java:19275)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.draw(View.java:19278)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.updateDisplayListIfDirty(View.java:18216)
       at android.view.View.draw(View.java:19003)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
       at android.view.View.draw(View.java:19278)
       at com.android.internal.policy.DecorView.draw(DecorView.java:788)
       at android.view.View.updateDisplayListIfDirty(View.java:18225)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3013)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2817)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2370)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1403)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6790)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:778)
       at android.view.Choreographer.doFrame(Choreographer.java:713)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

![206860693-5e847075-178f-48f8-a652-e850b4948e93](https://user-images.githubusercontent.com/66782790/206906390-8aa5aa5e-2d02-458f-935a-b9051e2b0cf6.png)

This user still uses library version 5.2.0

And here is the code from EllipseContent.java:86

```
85: PointF size = sizeAnimation.getValue();
86: float halfWidth = size.x / 2f;
87: float halfHeight = size.y / 2f;
```

It seems that we need to add a check for null here.

**Comment by gpeal** [comment]
Does it happen 100% of the time? Are there any trends in the devices?

**Comment by gpeal** [comment]
I find it very bizarre that you're the only one having #2206 #2207 and #2194. These errors really shouldn't be happening with valid Lottie json files. Is it possible that your animations are dynamically generated or something? Are they served from the network? Maybe your backend is sending json properties out of order sometimes? Json property order does actually matter for Lottie because it uses a streaming parser and if a property is moved before its type, it skip those propeties.

**Comment by danmov26** [comment]
Here are videos showing how i generate the files
[Videos.zip](https://github.com/airbnb/lottie-android/files/10229995/Videos.zip)

If you help me I will sponsor you. but I really need help, I don't understand why these errors occur and why avd is without animation. For some reason, I also started writing about avd, because maybe this is related, so I sent everything I can, I send it.

**Comment by danmov26** [comment]
Or maybe it's because I'm reformatting data.json that way:

![Снимок экрана 2022-12-14 203951](https://user-images.githubusercontent.com/66782790/207672651-c38707ba-5c88-4410-954c-44dae9d91d54.png)

Should I have left the json in one line? Without reformatting, that Android Studio does.

**Comment by gpeal** [comment]
This crash doesn't happen every time, right? Only sometimes. Have you ever seen this happen yourself or only in your crash analytics?

**Comment by danmov26** [comment]
Only from crashlytics

**Comment by gpeal** [comment]
Does this only happen with certain manufacturers or on certain Android versions?

**Comment by gpeal** [comment]
Closing due to lack of activity. Feel free to reopen with more info.

**Comment by SamuelW786** [comment]
Hey
