### ISSUE TITLE
Unable to parse composition 

### ISSUE THREAD

**Issue by dreamGitBhargav** [airbnb/lottie-android#2226]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
I am facing an ArrayIndex out of bound issue, which throws Unable to parse composition while loading lottie json file from the asset folder to my lottie view. I m facing this issue only in the android os 7 version.

we were using same animation file past year and we did not observe any crash. in latest release we are resolving fresco libs at 2.5.0 where as previously we were using 2.6.0 of fresco. after this we started seeing this issue.

java.lang.ArrayIndexOutOfBoundsException: size=2 offset=-8675855395576610810 byteCount=1

Stackstrace
Fatal Exception: java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView.values(SourceFile:72)
       at o.skipToPrevious.ag$a()
       at com.airbnb.lottie.LottieAnimationView$4.values(SourceFile:84)
       at com.airbnb.lottie.LottieAnimationView$4.ag$a(SourceFile:77)
       at o.MediaSessionCompat$Callback.toString(SourceFile:109)
       at com.airbnb.lottie.LottieAnimationView.ah$a(SourceFile:527)
       at com.airbnb.lottie.LottieAnimationView.setAnimation(SourceFile:411)
       at com.app.ui.pagerAnimation.CustomPagerAnimationView.setPagerAnimationVM(SourceFile:41)
       at o.UiVersions$StylesBuilder.executeBindings(SourceFile:157)
       at androidx.databinding.ViewDataBinding.executeBindingsInternal(SourceFile:512)
       at androidx.databinding.ViewDataBinding.executePendingBindings(SourceFile:484)
       at androidx.databinding.ViewDataBinding$7.run(SourceFile:218)
       at androidx.databinding.ViewDataBinding$8.doFrame(SourceFile:320)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:618)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
       
  Caused by java.lang.ArrayIndexOutOfBoundsException: size=5 offset=-3770922273037352936 byteCount=1
       at okio.-Util.checkOffsetAndCount(SourceFile:26)
       at okio.Buffer.getByte(SourceFile:1084)
       at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.skipQuotedValue(SourceFile:753)
       at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.skipValue(SourceFile:865)
       at com.airbnb.lottie.parser.ShapeFillParser.parse(SourceFile:59)
       at com.airbnb.lottie.parser.ContentModelParser.parse(SourceFile:63)
       at com.airbnb.lottie.parser.ShapeGroupParser.parse(SourceFile:41)
       at com.airbnb.lottie.parser.ContentModelParser.parse(SourceFile:54)
       at com.airbnb.lottie.parser.LayerParser.parse(SourceFile:169)
       at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseAssets(SourceFile:168)
       at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(SourceFile:89)
       at com.airbnb.lottie.LottieCompositionFactory.parse(SourceFile:362)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(SourceFile:355)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(SourceFile:298)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(SourceFile:291)
       at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(SourceFile:189)
       at com.airbnb.lottie.LottieCompositionFactory.cache(SourceFile:156)
       at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda3.call()
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**What version of Lottie did you test this on?**
We are using com.airbnb.android:lottie:5.1.1
we are using com.squareup.okio:okio:2.9.0

**What version of Android did you test this on?**
I am not able to repro this issue as it's happing for a few users in prod with android os 7.

**Steps To Reproduce**
Not able to repro the issue as its happening on android os 7.
[confetti.json.zip](https://github.com/airbnb/lottie-android/files/10444905/confetti.json.zip)

**Screenshots**

**Comment by gpeal** [comment]
Considering this device is running [xposed](https://forum.xda-developers.com/f/xposed-general.3094/), this is likely an issue with their filesystem or other system modifications they made and not an issue with Lottie.

If you want to add application code to retry parsing when it fails like this but I'm not sure there is something Lottie specific that can be done here.
