### ISSUE TITLE
clipToCompositionBounds field not found exception when trying to add LottieAnimationView by XML or programically

### ISSUE THREAD

**Issue by tomerpetel** [airbnb/lottie-android#2269]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Describe the bug**
Crash once init LottieAnimationView
When initiating a new LottieAnimationView object either from XML or programmatically I'm getting hit by an exception stating that  clipToCompositionBounds not found.

` java.lang.NoSuchFieldError: No static field LottieAnimationView_lottie_clipToCompositionBounds of type I in class Lcom/airbnb/lottie/R$styleable; or its superclasses (declaration of 'com.airbnb.lottie.R$styleable' appears in /data/app/~~_k_8ywDmbxfsm4tgNBVFfw==/com.bluegate.app.debug-upZwxhsn5Y9kpceQ7flkgw==/base.apk)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.init(LottieAnimationView.java:178)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:116)`

**What version of Lottie did you test this on?**
5.2.0 (doesn't happen on my current Lottie version which is 4.2.1

**What version of Android did you test this on?**
Android 13

**Steps To Reproduce**

1. Add LottieAnimationView from XML or programically
2. Application crash

**Comment by tomerpetel** [comment]
I can't attach the current project. I'll try to reproduce it and attach
