### ISSUE TITLE
App crash on invalid json url

### ISSUE THREAD

**Issue by vinodkumarsagitla** [airbnb/lottie-android#2271]
My issue is when josn url exist on remote server it working fine but **not exist then app is crash** with below exception
But in **ios app not crash** (no animation is showing i.e empty view) with invalid same josn url  
I try to put code in **try-catch** but still app crash
So my question is their is any way to check is **url exist on server or not** or any way to prevent crash for url not exist

`java.lang.IllegalStateException: Unable to parse composition
                                                                              	at com.airbnb.lottie.LottieAnimationView.lambda$static$0(LottieAnimationView.java:72)
                                                                              	at com.airbnb.lottie.LottieAnimationView$$ExternalSyntheticLambda2.onResult(Unknown Source:2)
                                                                              	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:84)
                                                                              	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:77)
                                                                              	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:162)
                                                                              	at com.airbnb.lottie.LottieTask.lambda$notifyListeners$0$com-airbnb-lottie-LottieTask(LottieTask.java:138)
                                                                              	at com.airbnb.lottie.LottieTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                              	at android.os.Handler.handleCallback(Handler.java:942)
                                                                              	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              	at android.os.Looper.loopOnce(Looper.java:201)
                                                                              	at android.os.Looper.loop(Looper.java:288)
                                                                              	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                              	at java.lang.reflect.Method.invoke(Native Method)
                                                                              	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                              	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                              Caused by: com.airbnb.lottie.parser.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
                                                                              	at com.airbnb.lottie.parser.moshi.JsonReader.syntaxError(JsonReader.java:251)
                                                                              	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:951)
                                                                              	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:355)
                                                                              	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:144)
                                                                              	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:56)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:362)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:355)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:298)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:291)
                                                                              	at com.airbnb.lottie.network.NetworkFetcher.fromJsonStream(NetworkFetcher.java:149)
                                                                              	at com.airbnb.lottie.network.NetworkFetcher.fromInputStream(NetworkFetcher.java:122)
                                                                              	at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:83)
                                                                              	at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:44)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory.lambda$fromUrl$0(LottieCompositionFactory.java:97)
                                                                              	at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda2.call(Unknown Source:6)`

**Comment by MSVhora** [comment]
Hi @vinodkumarsagitla, Can you give more details where you are facing this issue:

Device: 
Android version: 
Sample Working JSON Url:
Sample Nonworking JSON Url: 

I tried to reproduce the issue, but I am not getting any crash, its showing nice Snackbar with composition error and animation viewer keeps loading.

**Comment by vinodkumarsagitla** [comment]
My issue is when url is not valid i.e does not exist on remote server like
https://test com/test.json
So my point is app should not crash when url is not exist and show no or
empty animation

**Comment by MSVhora** [comment]
Hello @vinodkumarsagitla,

I have created a sample project to test out this issue, but I am not able to reproduce the same. I am using library version **com.airbnb.android:lottie:6.0.0**.

I have tested both valid and invalid json url with or without fallbackRes. Kindly check the same, this issue might be in previous versions or already fixed.

Repository Link: **https://github.com/MSVhora/LottieAndroidIssue2271**

**Comment by vinodkumarsagitla** [comment]
Thanks @MSVhora for you coordination

**Comment by vinodkumarsagitla** [comment]
@MSVhora I request to you please remove my client server url from your sample app [LottieAndroidIssue2271](https://github.com/MSVhora/LottieAndroidIssue2271)

**Comment by MSVhora** [comment]
> @MSVhora I request to you please remove my client server url from your sample app [LottieAndroidIssue2271](https://github.com/MSVhora/LottieAndroidIssue2271)

will remove
