### ISSUE TITLE
LottieCompose - java.lang.IllegalStateException: Missing values for keyframe

### ISSUE THREAD

**Issue by danilerofei** [airbnb/lottie-android#2294]
## Description
java.lang.IllegalStateException: Missing values for keyframe.
at com.airbnb.lottie.animation.keyframe.IntegerKeyframeAnimation.getIntValue(IntegerKeyframeAnimation.java:24)
at com.airbnb.lottie.animation.keyframe.IntegerKeyframeAnimation.getValue(IntegerKeyframeAnimation.java:16)
at com.airbnb.lottie.animation.keyframe.IntegerKeyframeAnimation.getValue(IntegerKeyframeAnimation.java:8)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:150)
at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:130)
at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:259)
at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:683)
at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$2.invoke(LottieAnimation.kt:128)
at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$2.invoke(LottieAnimation.kt:98)
at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:119)
at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:350)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:339)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:347)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:339)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:347)
at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:57)
at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:370)
at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:369)
at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:369)
at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:57)
at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:301)
at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:242)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:334)
at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:939)
at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:154)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:347)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:339)
at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:939)
at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1046)
at android.view.View.draw(View.java:23427)
at android.view.View.updateDisplayListIfDirty(View.java:22262)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4562)
at android.view.View.updateDisplayListIfDirty(View.java:22213)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4562)
at android.view.View.updateDisplayListIfDirty(View.java:22213)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4562)
at android.view.View.updateDisplayListIfDirty(View.java:22213)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4562)
at android.view.View.updateDisplayListIfDirty(View.java:22213)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4853)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4548)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3734)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9399)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:420)
at android.view.Choreographer.doFrame(Choreographer.java:900)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8380)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Expected behavior: [What you expected to happen]
It should render the animation

Actual behavior: [What actually happened]
Application breaks down with above error.

## Versions
lottie - 6.0.1-SNAPSHOT

NOTE: Same JSON working on iOS application

**Comment by gpeal** [comment]
Can you attach your animation or, preferable, aep file?

**Comment by danilerofei** [comment]
https://lottiefiles.com/144093-project-open-rate

I have problems with this animation

**Comment by mojtabamovahedi** [comment]
i think u need just update ur library to the last version
