### ISSUE TITLE
Getting ANR on Library (BaseLayer.<init>).

### ISSUE THREAD

**Issue by NStreet8579** [airbnb/lottie-android#2315]
Please check the below ANR getting from Crashlytic. 

main (runnable):tid=1 systid=26430 
       at android.graphics.Path.<init>(Path.java:66)
       at com.airbnb.lottie.model.layer.BaseLayer.<init>(BaseLayer.java:66)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:38)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:298)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:216)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:504)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java)
       at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
       at com.airbnb.lottie.LottieTask.access$100(LottieTask.java)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8245)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

Coming for Few Users. Mainly on Oppo (Reno2 Z)

**Comment by gpeal** [comment]
ANRs like this usually signal when the main thread is busy but arbitrarily land on whatever line it happens to be on when the watchdog timer expires. I don't think that this particular ANR is actually an issue with this line. You can search for other ANR issues here to see similar things.

**Comment by NStreet8579** [comment]
Sure Will check.
