### ISSUE TITLE
Release new version which compatible with  compose 1.5

### ISSUE THREAD

**Issue by karthickramanathan95** [airbnb/lottie-android#2387]
Compose 1.5 changes had incompatability with the available latest version. Release stable version compatible with latest compose
```
java.lang.NoSuchMethodError: No static method LottieAnimation(Lcom/airbnb/lottie/LottieComposition;Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;ZZZLcom/airbnb/lottie/RenderMode;ZLcom/airbnb/lottie/compose/LottieDynamicProperties;Landroidx/compose/ui/Alignment;Landroidx/compose/ui/layout/ContentScale;ZLjava/util/Map;Landroidx/compose/runtime/Composer;III)V in class Lcom/airbnb/lottie/compose/LottieAnimationKt; or its super classes (declaration of 'com.airbnb.lottie.compose.LottieAnimationKt' appears in /data/app/~~8Yf7qxG20bCkpPgwSnl-Ew==/com.healthifyme.dev-wkMvwjEUj3M6koF4a1EkTQ==/base.apk!classes35.dex)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt.ReviewDoneScreen(ReviewScreen.kt:411)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt.access$ReviewDoneScreen(ReviewScreen.kt:1)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt$ReviewScreen$8$1$6.invoke(ReviewScreen.kt:310)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt$ReviewScreen$8$1$6.invoke(ReviewScreen.kt:286)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:780)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:769)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:941)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:607)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:757)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:740)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:794)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt$ReviewScreen$8.invoke(ReviewScreen.kt:265)
                                                                                                    	at com.sample.review.presentation.ui.ReviewScreenKt$ReviewScreen$8.invoke(ReviewScreen.kt:196)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(ModalBottomSheet.kt:590)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(ModalBottomSheet.kt:587)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
```

**Comment by karthickramanathan95** [comment]
Wrong issue. Closing as not an issue

**Comment by prithivraj** [comment]
@karthickramanathan95 did you manage to find the fix for this crash?

**Comment by karthickramanathan95** [comment]
@prithivraj  Yes, we had different versions on different modules that caused the issue, changed all to the latest version fixed it
