### ISSUE TITLE
Adding Color Filter crashed

### ISSUE THREAD

**Issue by harshit-hike** [airbnb/lottie-android#239]
Exception log : 

```
java.lang.NullPointerException
                                                                   at com.airbnb.lottie.LottieDrawable$ColorFilterData.hashCode(LottieDrawable.java:508)
                                                                   at java.util.HashMap.secondaryHash(HashMap.java:350)
                                                                   at java.util.HashMap.put(HashMap.java:404)
                                                                   at java.util.HashSet.add(HashSet.java:95)
                                                                   at com.airbnb.lottie.LottieDrawable.addColorFilterInternal(LottieDrawable.java:267)
                                                                   at com.airbnb.lottie.LottieDrawable.addColorFilter(LottieDrawable.java:241)
                                                                   at com.airbnb.lottie.LottieAnimationView.addColorFilter(LottieAnimationView.java:164)
```

**Bug 1**
In reference to LottieDrawable.java
```
ColorFilterData(String layerName, @Nullable String contentName,
        @Nullable ColorFilter colorFilter) {
      this.layerName = layerName;
      this.contentName = contentName;
      this.colorFilter = colorFilter;
    }
```

```
    @Override public int hashCode() {
      int hashCode = 17;
      hashCode = hashCode * 31 * layerName.hashCode();
      hashCode = hashCode * 31 * contentName.hashCode();
      return hashCode;
    }
```

In the above mentioned code, contentName is nullable but there is no check for nullable in hashCode().

**Bug 2**
In reference to LottieDrawable.java

```
 private void addColorFilterInternal(@Nullable String layerName, @Nullable String contentName,
      @Nullable ColorFilter colorFilter) {
    final ColorFilterData data = new ColorFilterData(layerName, contentName, colorFilter);
    if (colorFilter == null && colorFilterData.contains(data)) {
      colorFilterData.remove(data);
    } else {
      colorFilterData.add(new ColorFilterData(layerName, contentName, colorFilter));
    }

    if (compositionLayer == null) {
      return;
    }

    compositionLayer.addColorFilter(layerName, contentName, colorFilter);
  }
```
According to ColorFilterData constructor, layerName cannot be null.

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/commit/246b2565327a5bddd9d3f7f1afba31038abab70e fixes the first one.

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/commit/091bcdaba064604bfcba751530ec1e826170af60 fixes the second
