### ISSUE TITLE
IllegalStateException: Unable to parse composition

### ISSUE THREAD

**Issue by IvanHalitskyi** [airbnb/lottie-android#2399]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). 🟢 
2. I know what part of my animation doesn't work. 🔴 
3. I have created a simplified version of my animation 🔴
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.🔴

**Describe the bug**
We have the following animation - https://lottie.host/4bc1f285-0930-40fa-b96a-27991d5a17e9/PkyXLZthcb.json
It simply does not work when we are trying to apply it in the very basic Android project, the application crashes (stacktrace is attached below) 

After some debugging, we think that it is because of `to` and `ti` keys, they are set to `null`, but expect to have arrays
This animation still displays correctly on [https://app.lottiefiles.com/](https://app.lottiefiles.com/) so we are not sure why Android cannot display that

**What version of Lottie did you test this on?**
6.1.0

**What version of Android did you test this on?**
SDK 33

**Steps To Reproduce**

1. Set up a project using 6.1.0 library version
2. Display animation using `app:lottie_rawRes`

**Screenshots**
```
FATAL EXCEPTION: main
Process: com.babbel.mobile.android.en, PID: 8973
java.lang.IllegalStateException: Unable to parse composition
	at com.airbnb.lottie.LottieAnimationView.lambda$static$0(LottieAnimationView.java:75)
	at com.airbnb.lottie.LottieAnimationView$$ExternalSyntheticLambda1.onResult(Unknown Source:2)
	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:117)
	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:99)
	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:162)
	at com.airbnb.lottie.LottieTask.lambda$notifyListeners$0$com-airbnb-lottie-LottieTask(LottieTask.java:138)
	at com.airbnb.lottie.LottieTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Unknown point starts with NULL
	at com.airbnb.lottie.parser.JsonUtils.jsonToPoint(JsonUtils.java:55)
	at com.airbnb.lottie.parser.KeyframeParser.parseKeyframe(KeyframeParser.java:128)
	at com.airbnb.lottie.parser.KeyframeParser.parse(KeyframeParser.java:81)
	at com.airbnb.lottie.parser.PathKeyframeParser.parse(PathKeyframeParser.java:21)
	at com.airbnb.lottie.parser.AnimatablePathValueParser.parse(AnimatablePathValueParser.java:35)
	at com.airbnb.lottie.parser.AnimatablePathValueParser.parseSplitPath(AnimatablePathValueParser.java:61)
	at com.airbnb.lottie.parser.AnimatableTransformParser.parse(AnimatableTransformParser.java:72)
	at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:139)
	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseAssets(LottieCompositionMoshiParser.java:168)
	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:89)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:407)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:400)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:343)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:333)
	at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:290)
	at com.airbnb.lottie.LottieCompositionFactory.lambda$fromRawRes$2(LottieCompositionFactory.java:256)
	at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda8.call(Unknown Source:8)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by kudanai** [comment]
I think this might be a bug on our end (LottieFiles). Investigating the issue on our end.

**Comment by kudanai** [comment]
@IvanHalitskyi I had a look at your exported JSON and noticed it has a bunch of "_render" keys in it.
This is a side effect of putting the json through lottie-web and grabbing the lottie-web internal object model. Which will render again on lottie-web but will fail on other players since it's no longer valid lottie.

Do you know if this happened here?

**Comment by csbenz** [comment]
@kudanai @IvanHalitskyi So what are we supposed to do to fix this? It's not possible to use the web editor at all? What's the use of the web editor if it breaks files? How can I fix my json file? Thanks!

**Comment by kudanai** [comment]
@csbenz a web editor shouldn't break files like this. This happens when users (or editor) incorrectly takes a state dump from lottie-web (player) and passes it off as a Lottie. At this time i'm not which (if any) editors do this. 

Fixing the file might be a bit of a tedious and manual process.

**Comment by csbenz** [comment]
@kudanai Thanks for your response. What does "take a state dump" mean in this case?

**Comment by kudanai** [comment]
@csbenz essentially when lottie-web parses the lottie .json, it doesn't retain the original structure. It processes it into a model that's more suitable for render tasks. It uses this render optimised model as its internal state while it renders on screen. This new model is accessible via the lottie-web api and on occasion people dump it back to .json thinking it will still be valid lottie, which it is not.

The way it works, lottie-web is still able to absorb and use this modified file because it tries to do the same mutations on load. However, other players such as lottie-android and lottie-ios can't understand it since they're internal models are different.

**Comment by yourusernqm** [comment]
@kudanai hi , i just downloaded a bunch of animations from the marketplace and all of them have this issue andsame "_render" tag in them. is there a way to fix them ?

**Comment by kudanai** [comment]
@yourusernqm we do not at this time have a straightforward fix for it. Do you have a link to the marketplace? might be able to help you out on that front

**Comment by ShkurtiA** [comment]
https://lottiefiles.com/animations/error-404-0DNVvPkCmA?from=search

https://lottiefiles.com/animations/no-date-animation-wWKOVUzGQf?from=search

https://lottiefiles.com/animations/ufo-404-Nj3rN5178E?from=search

https://lottiefiles.com/animations/work-from-home-yrzv5FOie0?from=search

@kudanai none of this can play from the marketplace in android lottie: 6.4.1



error log for first file

`java.lang.IllegalStateException: Unable to parse composition
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.lambda$static$0(LottieAnimationView.java:74)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$$ExternalSyntheticLambda1.onResult(D8$$SyntheticClass:0)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:116)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:98)
                                                                                                    	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:179)
                                                                                                    	at com.airbnb.lottie.LottieTask.notifyListenersInternal(LottieTask.java:156)
                                                                                                    	at com.airbnb.lottie.LottieTask.$r8$lambda$AdJFAWRq87LYDwF2-gMLZe0_AkA(Unknown Source:0)
                                                                                                    	at com.airbnb.lottie.LottieTask$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Unknown point starts with NULL
                                                                                                    	at com.airbnb.lottie.parser.JsonUtils.jsonToPoint(JsonUtils.java:55)
                                                                                                    	at com.airbnb.lottie.parser.KeyframeParser.parseKeyframe(KeyframeParser.java:128)
                                                                                                    	at com.airbnb.lottie.parser.KeyframeParser.parse(KeyframeParser.java:81)
                                                                                                    	at com.airbnb.lottie.parser.PathKeyframeParser.parse(PathKeyframeParser.java:21)
                                                                                                    	at com.airbnb.lottie.parser.AnimatablePathValueParser.parse(AnimatablePathValueParser.java:35)
                                                                                                    	at com.airbnb.lottie.parser.AnimatablePathValueParser.parseSplitPath(AnimatablePathValueParser.java:61)
                                                                                                    	at com.airbnb.lottie.parser.AnimatableTransformParser.parse(AnimatableTransformParser.java:72)
                                                                                                    	at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:145)
                                                                                                    	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:120)
                                                                                                    	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:86)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:430)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:420)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:366)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:358)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:315)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.lambda$fromRawRes$2(LottieCompositionFactory.java:270)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda7.call(D8$$SyntheticClass:0`

**Comment by ShkurtiA** [comment]
I can confirm that the json you posted work on android. I downloaded them recently, can you please show me how you did the reexport,

if I click download button on the right side, it doesnt work

<img width="1667" alt="image" src="https://github.com/airbnb/lottie-android/assets/8733915/665953b0-3a98-4c2c-b412-680f6b656cab">
