### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ShowkaseBrowserActivity

### ISSUE THREAD

**Issue by Monabr** [airbnb/lottie-android#2429]
Hello.

With each of my releases, bots come to me and launch ShowkaseBrowserActivity, it crashes and I get bad statistics. Is there any way to fix this?

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{.../com.airbnb.android.showkase.ui.ShowkaseBrowserActivity}: com.airbnb.android.showkase.exceptions.ShowkaseException: Missing key in bundle. Please start this activity by using the intent returned by the ShowkaseBrowserActivity.getIntent() method.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by gpeal** [comment]
I think you meant to post this on https://github.com/airbnb/Showkase
