### ISSUE TITLE
Caused by: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by xieguorong123456** [airbnb/lottie-android#2535]
java.lang.IllegalStateException: Unable to parse composition
	at com.airbnb.lottie.LottieAnimationView$1.a(Unknown Source:16)
	at com.airbnb.lottie.LottieAnimationView$1.onResult(Unknown Source:2)
	at com.airbnb.lottie.LottieAnimationView$3.a(Unknown Source:36)
	at com.airbnb.lottie.LottieAnimationView$3.onResult(Unknown Source:2)
	at com.airbnb.lottie.LottieTask.g(Unknown Source:37)
	at com.airbnb.lottie.LottieTask.c(Unknown Source:0)
	at com.airbnb.lottie.LottieTask$1.run(Unknown Source:37)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
	at android.app.ActivityThread.main(ActivityThread.java:9975)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
Caused by: java.io.FileNotFoundException: bj_tabbar_lottie_vehicle_use.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:1046)
	at android.content.res.AssetManager.open(AssetManager.java:1023)
	at com.airbnb.lottie.LottieCompositionFactory.h(Unknown Source:30)
	at com.airbnb.lottie.LottieCompositionFactory$2.b(Unknown Source:6)
	at com.airbnb.lottie.LottieCompositionFactory$2.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:933)

**Comment by gpeal** [comment]
This is likely an issue in your app in which the animation file is getting deleted or is not specified directly. If you can reproduce this in a project, feel free to attach and reopen this.
