### ISSUE TITLE
When i use this to ListView, I have some problems;

### ISSUE THREAD

**Issue by SLSIC** [airbnb/lottie-android#280]
if i use Lottie as listview's item, the devices main thread will be block;
there's item's xml layout:
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/item_anim"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@id/timeTv"
        android:layout_alignTop="@id/timeTv"
        android:layout_gravity="center"
        android:layout_marginTop="5dp"
        android:layout_toRightOf="@id/timeTv"
        app:lottie_autoPlay="true"
        app:lottie_fileName="data.json"
        app:lottie_loop="true"
        />
if i use it in code like following:
            final LottieAnimationView anim = vh.getView(R.id.item_anim);
            LottieComposition.Factory.fromAssetFileName(mContext, "data.json", new OnCompositionLoadedListener() {
                @Override
                public void onCompositionLoaded(LottieComposition composition) {
                    anim.setComposition(composition);
                    anim.playAnimation();
                }
            });
then,exception
Process: com.tq.myapplication, PID: 20813
                                                                      java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@547f71c8 rejected from java.util.concurrent.ThreadPoolExecutor@527c98e0[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 67]
                                                                          at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
                                                                          at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:128)
                                                                          at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java:116)
                                                                          at com.tq.adapter.ListViewAdapter.convert(ListViewAdapter.java:47)

**Comment by gpeal** [comment]
@SLSIC Try setting the cache strategy to Weak or Strong when you set the composition. Then it will only deserialize once.
