### ISSUE TITLE
Issue : The Path cannot loop back on itself

### ISSUE THREAD

**Issue by anaghvj** [airbnb/lottie-android#288]
I am receiving runtime exception

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                      at java.lang.Thread.run(Thread.java:761)
                                                                   Caused by: java.lang.IllegalArgumentException: The Path cannot loop back on itself.
                                                                      at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:185)
                                                                      at android.view.animation.PathInterpolator.initCubic(PathInterpolator.java:154)
                                                                      at android.view.animation.PathInterpolator.<init>(PathInterpolator.java:85)
                                                                      at android.support.v4.view.animation.PathInterpolatorCompatApi21.create(PathInterpolatorCompatApi21.java:47)
                                                                      at android.support.v4.view.animation.PathInterpolatorCompat.create(PathInterpolatorCompat.java:81)
                                                                      at com.airbnb.lottie.Keyframe$Factory.newInstance(Keyframe.java:134)
                                                                      at com.airbnb.lottie.PathKeyframe$Factory.newInstance(PathKeyframe.java:26)
                                                                      at com.airbnb.lottie.AnimatablePathValue.<init>(AnimatablePathValue.java:39)
                                                                      at com.airbnb.lottie.AnimatablePathValue.createAnimatablePathOrSplitDimensionPath(AnimatablePathValue.java:15)
                                                                      at com.airbnb.lottie.AnimatableTransform$Factory.newInstance(AnimatableTransform.java:59)
                                                                      at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java:229)
                                                                      at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:202)
                                                                      at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:194)
                                                                      at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:163)
                                                                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
                                                                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                      at java.lang.Thread.run(Thread.java:761) 
```
Attaching the Bodymovin ZIP
[Archive.zip](https://github.com/airbnb/lottie-android/files/985958/Archive.zip)

My code
 `<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true" />`

` animationView = (LottieAnimationView) rootView.findViewById(R.id.animation_view);
        animationView.setAnimation("screen.json");
        animationView.loop(true);
        animationView.setImageAssetsFolder("images");
        animationView.playAnimation();`

**Comment by gpeal** [comment]
@anaghvj Can you attach the after effects file?

**Comment by sachinsimiliate** [comment]
[Onboarding 2page_edit.aep.zip](https://github.com/airbnb/lottie-android/files/987038/Onboarding.2page_edit.aep.zip)
