### ISSUE TITLE
Exception when trying to load composition from input stream

### ISSUE THREAD

**Issue by kanvuduc** [airbnb/lottie-android#335]
```
Failed to load composition.
     java.lang.IllegalStateException: Unable to load JSON.
         at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:171)
         at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
         at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
```

```java
animationView = (LottieAnimationView) findViewById(R.id.animation_view);

        HandlerThread x = new HandlerThread("LottieComposition") {
            @Override
            public void run() {
                try {
                    URL url = new URL("https://www.lottiefiles.com/storage/datafiles/VQEMQej23ncH677/data.json");
                    InputStream stream = url.openStream();

                    LottieComposition.Factory.fromInputStream(getApplicationContext(), stream, new OnCompositionLoadedListener() {
                        @Override
                        public void onCompositionLoaded(@Nullable final LottieComposition composition) {
                            animationView.post(new Runnable() {
                                @Override
                                public void run() {
                                    animationView.setComposition(composition);
                                    animationView.playAnimation();
                                }
                            });
                        }
                    });
                } catch (MalformedURLException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        };

        x.start();
```

**Comment by gpeal** [comment]
fromInputStream is meant to be used for files only. To load from the network, I recommend using a networking library like retrofit to get a jsonobject and using that instead. I did something similar in the lottie sample app [here](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java#L449)
