### ISSUE TITLE
Exception: IncompatibleClassChangeError

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#363]
Hi, The crash platform catches a Exception following, but I can't recurrent it.

```
java.lang.IncompatibleClassChangeError: Class 'com.airbnb.lottie.br' does not implement interface 'com.airbnb.lottie.aa' in call to 'void com.airbnb.lottie.aa.a(android.graphics.Canvas, android.graphics.Matrix, int)' (declaration of 'com.airbnb.lottie.y' appears in /data/app/free.vpn.unblock.proxy.vpnmonster-2/base.apk)
	at com.airbnb.lottie.y.a(Unknown Source)
	at com.airbnb.lottie.y.a(Unknown Source)
	at com.airbnb.lottie.bw.b(Unknown Source)
	at com.airbnb.lottie.o.a(Unknown Source)
	at com.airbnb.lottie.v.b(Unknown Source)
	at com.airbnb.lottie.o.a(Unknown Source)
	at com.airbnb.lottie.ax.draw(Unknown Source)
	at android.widget.ImageView.onDraw(ImageView.java:1286)
	at android.view.View.draw(View.java:17122)
	at android.view.View.buildDrawingCacheImpl(View.java:16411)
	at android.view.View.buildDrawingCache(View.java:16272)
	at android.view.View.updateDisplayListIfDirty(View.java:16085)
	at android.view.View.draw(View.java:16888)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16099)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
	at android.view.View.updateDisplayListIfDirty(View.java:16067)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1250)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6311)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by gpeal** [comment]
@SwayChen Can you attach a sample project that repros this? There isn't enough to go off of here and it may be related to your specific project setup.

**Comment by SwayChen** [comment]
@gpeal I'm sorry can not offer sample, because I don't meet the Exception in test. Just the crash platform catches it. I preload JSON as a Composition and use setComposition.

**Comment by gpeal** [comment]
@SwayChen Does your crash reporting indicate anything unusual such as this only happening on Samsung devices or only on a specific platform version?

**Comment by SwayChen** [comment]
@gpeal No, now it was caught once in Sony Z3+. Maybe leave it out now, I will contact again if find more wrong info.

**Comment by gpeal** [comment]
It's possible that the user's device is in some strange state or rooted or something. If this happens to a significant number of users, feel free to reopen. Fwiw, we have never seen this in the Airbnb app in production.

**Comment by leonsimple** [comment]
same crash 
  | Caused by: java.lang.IncompatibleClassChangeError:Expected 'byte[] Decoder.BASE64Decoder.decode_buffer' to be a static field rather than a instance field (declaration of 'com.airbnb.lottie.parser.LayerParser' appears in /data/user/0/com.xxxxxx.xxxxxx/.cache/classes.jar)
-- | --
1 | at com.airbnb.lottie.parser.LayerParser.parse(SourceFile:54)
2 | at com.airbnb.lottie.parser.LottieCompositionParser.parseLayers(SourceFile:104)
3 | at com.airbnb.lottie.parser.LottieCompositionParser.parse(SourceFile:72)
4 | at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(SourceFile:276)
5 | at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(SourceFile:22)
6 | at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(SourceFile:12)
7 | at android.os.AsyncTask$2.call(AsyncTask.java:305)
8 | at java.util.concurrent.FutureTask.run(FutureTask.java:237)
9 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11 | at java.lang.Thread.run(Thread.java:761)

**Comment by leonsimple** [comment]
but i edit com.airbnb.lottie.parser.AsyncCompositionLoader to close IO
it's wrong？
`
  @Override protected LottieComposition doInBackground(JsonReader... params) {
    try {
      return LottieComposition.Factory.fromJsonSync(params[0]);
    } catch (IOException e) {
      throw new IllegalStateException(e);
    } finally {
      JsonReader param = params[0];
      if (param != null) {
        try {
          param.close();
        } catch (IOException e) {
          e.printStackTrace();
        }
      }
    }
  }`
