### ISSUE TITLE
v2.1.0 >> NullPointer in LottieDrawable$animator

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#439]
I can't reappear it, but caught by crash SDK. Exception message following

```
java.lang.NullPointerException
	at com.airbnb.lottie.BaseLayer.forModel(BaseLayer.java)
	                               onValueChanged(BaseLayer.java)
	                               setMatteLayer(BaseLayer.java)
	                               addAnimation(BaseLayer.java)
	                               getBounds(BaseLayer.java)
	                               draw(BaseLayer.java)
	                               clearCanvas(BaseLayer.java)
	                               applyMasks(BaseLayer.java)
	                               setVisible(BaseLayer.java)
	                               setProgress(BaseLayer.java)
	                               setContents(BaseLayer.java)
	                               addColorFilter(BaseLayer.java)
	                               access$000(BaseLayer.java)
	at com.airbnb.lottie.CompositionLayer.getBounds(CompositionLayer.java)
	                                      setProgress(CompositionLayer.java)
	                                      addColorFilter(CompositionLayer.java)
	at com.airbnb.lottie.LottieDrawable.getImageAssetsFolder(LottieDrawable.java)
	                                    setPerformanceTrackingEnabled(LottieDrawable.java)
	                                    setProgress(LottieDrawable.java)
	                                    getImageAsset(LottieDrawable.java)
	                                    access$100(LottieDrawable.java)
	at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1251)
	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1175)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1216)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:637)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:543)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5433)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by gpeal** [comment]
@SwayChen the formatting is not right on your stack trace. Can you attach a properly formatted stack trace and an animation that repros this?

**Comment by SwayChen** [comment]
@gpeal Pity about that! It doesn't appear during my developing, so I can't offer stack trace in Android Studio. The exception message I offer before was caught by crash platform.

**Comment by gpeal** [comment]
@SwayChen Can you attach a better stack trace? There is some strange formatting in the one you posted.

**Comment by SwayChen** [comment]
@gpeal I can't... the crash platform makes these stack trace through mapping.txt

**Comment by gpeal** [comment]
I think this will be fixed by https://github.com/airbnb/lottie-android/commit/509da1bca7f5b363574279c9f0633c24b4ae5faa

**Comment by gpeal** [comment]
@SwayChen 2.2.3 is now out
