### ISSUE TITLE
Crash with custom font and \r

### ISSUE THREAD

**Issue by jackeleene** [airbnb/lottie-android#445]
Hi,

I'm currently trying to integrate an animation with custom font. I don't have the After effect file so I won't be able to post it here. Although, here is the JSON part that causes the problem : 
`{
		"ch": "\r",
		"size": 60,
		"style": "Bold",
		"w": 0,
		"fFamily": "Nunito"
	}`

This misses the "data" object and I get a NullPointerException in FontCharacter Factory.
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.optJSONArray(java.lang.String)' on a null object reference
                                                                                 at com.airbnb.lottie.FontCharacter$Factory.newInstance(FontCharacter.java:61)
                                                                                 at com.airbnb.lottie.LottieComposition$Factory.parseChars(LottieComposition.java:360)
                                                                                 at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:266)
                                                                                 at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226)
                                                                                 at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
                                                                                 at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:304)`

I managed to get it work anyway since I only had to add a couple lines in my JSON file but since it's supposed to be generated, it would be best if it was ignored in the library. 

Thanks

**Comment by RishabhTayal** [comment]
Having the same issue. What's the solution?

**Comment by jackeleene** [comment]
I've edited the JSON file adding an empty JSONObject name "data" in every JSONObject that contains 
`"ch": "\r"`

My example would be something like

`{ "ch": "\r", "size": 60, "style": "Bold", "w": 0, "fFamily": "Nunito", "data": {} }`

Hope this helps

**Comment by RishabhTayal** [comment]
Thanks I will try it.
