### ISSUE TITLE
Exception found in version 2.2.0

### ISSUE THREAD

**Issue by reallychenchi** [airbnb/lottie-android#449]
With version 2.1.2 there is not such problem, after we update to 2.2.0, the exception was found.

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.remove(ArrayList.java:586)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:169)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:390)
       at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java:355)
       at com.airbnb.lottie.FileCompositionLoader.onPostExecute(FileCompositionLoader.java:21)
       at com.airbnb.lottie.FileCompositionLoader.onPostExecute(FileCompositionLoader.java:7)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by lxdyglt** [comment]
Got the same issue, pls fix it
