### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dss886** [airbnb/lottie-android#452]
StackTrace:
```
java.lang.ArrayIndexOutOfBoundsException: src.length=13 srcPos=8 dst.length=13 dstPos=9 length=5
	at java.lang.System.arraycopy(System.java)
	at android.support.v4.util.SparseArrayCompat.put(SparseArrayCompat.java:209)
	at com.airbnb.lottie.Keyframe$Factory.newInstance(Keyframe.java:160)
	at com.airbnb.lottie.Keyframe$Factory.parseKeyframes(Keyframe.java:181)
	at com.airbnb.lottie.AnimatableValueParser.parseKeyframes(AnimatableValueParser.java:40)
	at com.airbnb.lottie.AnimatableValueParser.parseJson(AnimatableValueParser.java:31)
	at com.airbnb.lottie.AnimatableShapeValue$Factory.newInstance(AnimatableShapeValue.java:37)
	at com.airbnb.lottie.Mask$Factory.newMask(Mask.java:43)
	at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java:266)
	at com.airbnb.lottie.LottieComposition$Factory.parsePrecomps(LottieComposition.java:312)
	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:264)
	at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```
Keyframe.newInstance() is a static method. I guess there are some multithreaded operation, but I am quite sure I didn't initial LottieAnimationView in multithread.

Is it a inner bug or I did something wrong?

**Comment by gpeal** [comment]
@dss886 What are the repro steps for this?

**Comment by dss886** [comment]
@gpeal Actually I don't know…it is one of the crash logs after I published my app.

**Comment by SwayChen** [comment]
@gpeal @dss886 this exception also caught by crash-platform in my app.

**Comment by gpeal** [comment]
How common is the crash?

**Comment by dss886** [comment]
@gpeal About 4-5 crash per day in my case. The distribution of the system version is uniform from 5.0 to 7.1.

**Comment by dss886** [comment]
And this crash begin to happen after I upgraded Lottie to 2.2.0. The last version of my app 
 which is using Lottie 2.0.0 is ok.

**Comment by moni890185** [comment]
We face the same one, ~250 crashes per day, it's the most common crash we have in production but we can't reproduce it. Same here, we are on 2.2.0 and it does not appear to be related to any specific device/OS.

**Comment by gpeal** [comment]
Thanks. I'll look in to this asap.

**Comment by SwayChen** [comment]
Hi, this Exception still exists on `2.2.1`

**Comment by gpeal** [comment]
@SwayChen Can you post another stack trace?

**Comment by SwayChen** [comment]
I don't know the following trace is helpful or not. It's a crash log making with mapping file by Analytics platform, but it is similar with the trace by @dss886 .
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=13 srcPos=11 dst.length=13 dstPos=12 length=2
	at java.lang.System.arraycopy(System.java)
	at android.support.v4.util.SparseArrayCompat.put(SparseArrayCompat.java)
	at com.airbnb.lottie.Keyframe$Factory.newInstance(Keyframe.java)
	                                      parseKeyframes(Keyframe.java)
	at com.airbnb.lottie.PathKeyframe$Factory.newInstance(PathKeyframe.java)
	at com.airbnb.lottie.AnimatablePathValue.<init>(AnimatablePathValue.java)
	at com.airbnb.lottie.AnimatableTransform$Factory.newInstance(AnimatableTransform.java)
	                                                 throwMissingTransform(AnimatableTransform.java)
	at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java)
	                                           onPostExecute(FileCompositionLoader.java)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
java.lang.ArrayIndexOutOfBoundsException: src.length=13 srcPos=11 dst.length=13 dstPos=12 length=2
	at java.lang.System.arraycopy(System.java)
	at android.support.v4.util.SparseArrayCompat.put(SparseArrayCompat.java)
	at com.airbnb.lottie.Keyframe$Factory.newInstance(Keyframe.java)
	                                      parseKeyframes(Keyframe.java)
	at com.airbnb.lottie.PathKeyframe$Factory.newInstance(PathKeyframe.java)
	at com.airbnb.lottie.AnimatablePathValue.<init>(AnimatablePathValue.java)
	at com.airbnb.lottie.AnimatableTransform$Factory.newInstance(AnimatableTransform.java)
	                                                 throwMissingTransform(AnimatableTransform.java)
	at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJson(LottieComposition.java)
	                                               fromInputStream(LottieComposition.java)
	                                               fromJsonSync(LottieComposition.java)
	                                               parseLayers(LottieComposition.java)
	                                               parsePrecomps(LottieComposition.java)
	                                               addLayer(LottieComposition.java)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java)
	                                           onPostExecute(FileCompositionLoader.java)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by gpeal** [comment]
@SwayChen Can you double check that this is definitely 2.2.1? This looks like it's coming from the try/catch that explicitly catches this: https://github.com/airbnb/lottie-android/blob/c7f4abb89fb10ec84085aa9760d52dc23225c1dd/lottie/src/main/java/com/airbnb/lottie/animation/Keyframe.java#L167

**Comment by SwayChen** [comment]
So sorry about that! I thought I have change to 2.2.1, but not in fact... :(

sorry to waste your time.

**Comment by dss886** [comment]
well, I got a similar crash with 2.2.1...

```
java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
	at android.support.v4.util.ContainerHelpers.binarySearch(ContainerHelpers.java:51)
	at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java:85)
	at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java:76)
	at com.airbnb.lottie.animation.Keyframe$Factory.newInstance(Keyframe.java:159)
	at com.airbnb.lottie.animation.Keyframe$Factory.parseKeyframes(Keyframe.java:195)
	at com.airbnb.lottie.model.animatable.AnimatableValueParser.parseKeyframes(AnimatableValueParser.java:43)
	at com.airbnb.lottie.model.animatable.AnimatableValueParser.parseJson(AnimatableValueParser.java:34)
	at com.airbnb.lottie.model.animatable.AnimatableShapeValue$Factory.newInstance(AnimatableShapeValue.java:45)
	at com.airbnb.lottie.model.content.Mask$Factory.newMask(Mask.java:47)
	at com.airbnb.lottie.model.layer.Layer$Factory.newInstance(Layer.java:278)
	at com.airbnb.lottie.LottieComposition$Factory.parsePrecomps(LottieComposition.java:326)
	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:278)
	at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:241)
	at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:20)
	at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:10)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
```

**Comment by gpeal** [comment]
@dss886 @SwayChen @moni890185  v2.2.4 is now out
