### ISSUE TITLE
enableMergePathsForKitKatAndAbove ConcurrentModificationException

### ISSUE THREAD

**Issue by magic1983** [airbnb/lottie-android#455]
In the newest version,There is a problem,this is stackover:

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.remove(ArrayList.java:586)
       at com.airbnb.lottie.LottieDrawable.enableMergePathsForKitKatAndAbove(LottieDrawable.java)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java)
       at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java)
       at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java)
       at com.airbnb.lottie.FileCompositionLoader.onPostExecute(FileCompositionLoader.java)
       at android.os.AsyncTask.finish(AsyncTask.java:631)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5214)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/issues/449
