### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in 2.2.3

### ISSUE THREAD

**Issue by letterb** [airbnb/lottie-android#472]
occur this crash in 2.2.1. After I update to com.airbnb.android:lottie:2.2.3, it occur again, Help please!

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
	at android.support.v4.util.ContainerHelpers.binarySearch(ContainerHelpers.java)
	at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java)
	at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java)
	at com.airbnb.lottie.animation.Keyframe$Factory.newInstance(Keyframe.java)
	at com.airbnb.lottie.model.animatable.AnimatablePathValue.<init>(AnimatablePathValue.java)
	at com.airbnb.lottie.model.animatable.AnimatablePathValue.createAnimatablePathOrSplitDimensionPath(AnimatablePathValue.java)
	at com.airbnb.lottie.model.animatable.AnimatableTransform$Factory.newInstance(AnimatableTransform.java)
	at com.airbnb.lottie.model.layer.Layer$Factory.newInstance(Layer.java)

**Comment by gpeal** [comment]
@letterb Try 2.2.4
This should have fixed it: https://github.com/airbnb/lottie-android/commit/5af69e7f81877a465d10718450c3dfa65891cdab

**Comment by letterb** [comment]
Thanks! i will try it soon!
