### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wurensen** [airbnb/lottie-android#493]
java.lang.NullPointerException
	at com.airbnb.lottie.BaseLayer.setProgress(BaseLayer.java:358)
	at com.airbnb.lottie.CompositionLayer.setProgress(CompositionLayer.java:116)
	at com.airbnb.lottie.CompositionLayer.setProgress(CompositionLayer.java:128)
	at com.airbnb.lottie.CompositionLayer.setProgress(CompositionLayer.java:128)
	at com.airbnb.lottie.LottieDrawable.setProgress(LottieDrawable.java:407)
	at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:67)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1251)
	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1175)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1216)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:637)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:543)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(NativeStart.java)

I can't recurrence this exception.Lottie version 2.1.2.

**Comment by gpeal** [comment]
@wurensen Can you try with 2.2.5 and attach the animation that crashes?
If you're using 2.1.2, the code looks like it's crashing [here](https://github.com/airbnb/lottie-android/blob/3d7ed119b4d145f837fa3f7d051b668148ce1143/lottie/src/main/java/com/airbnb/lottie/BaseLayer.java) and it doesn't seem like it would be possible to get an NPE there.

**Comment by gpeal** [comment]
I'm not sure what you mean by `I can't recurrence this exception.Lottie version 2.1.2.`

**Comment by wurensen** [comment]
I'll update to 2.2.5.
