### ISSUE TITLE
ArrayIndexOutOfBoundsException: length=0; index=0

### ISSUE THREAD

**Issue by chievent** [airbnb/lottie-android#507]
I'm using lottie v2.2.5 and this crash was reported by some user. Please fix it.

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:271)
       at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:241)
       at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:20)
       at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:10)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by gpeal** [comment]
@chievent There is an issue with your animation json because there is no version number specified. Can you try and re-export the json? There should be a top level key "v" with value "4.10.0" or something similar.
