### ISSUE TITLE
When I used the version of 2.2.5.I couldn't get the com.android.support:appcompat-v7:26.1.0?

### ISSUE THREAD

**Issue by xiaozhao0331** [airbnb/lottie-android#554]
Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0
Install Repository and sync project

**Comment by xiaozhao0331** [comment]
And  when I used version 2.2.0,i got this  ,please help me , :)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                   Process: com.koalareading.koalareading, PID: 24709
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:330)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:776)
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;
                                                       at com.airbnb.lottie.PerformanceTracker.<init>(PerformanceTracker.java:22)
                                                       at com.airbnb.lottie.LottieComposition.<init>(LottieComposition.java:44)
                                                       at com.airbnb.lottie.LottieComposition.<init>(LottieComposition.java:33)
                                                       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:260)
                                                       at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226)
                                                       at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
                                                       at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:776) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArraySet" on path: DexPathList[[dex file "/data/user/0/com.xxxxx.xxxxx/cache/hack/hackload.dex", zip file "/data/app/com.xxxx.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.x.xxx-1/lib/arm, /system/fake-libs, /data/app/com.xxxx.xxx-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.airbnb.lottie.PerformanceTracker.<init>(PerformanceTracker.java:22) 
                                                       at com.airbnb.lottie.LottieComposition.<init>(LottieComposition.java:44) 
                                                       at com.airbnb.lottie.LottieComposition.<init>(LottieComposition.java:33) 
                                                       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:260) 
                                                       at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226) 
                                                       at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17) 
                                                       at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:776)

**Comment by gpeal** [comment]
@xiaozhao0331 Add
```
maven {  url 'https://maven.google.com' }
```
to your build.gradle file per this: https://developer.android.com/studio/build/dependencies.html

This isn't a lottie specific issue.
