### ISSUE TITLE
NumberFormatException: Invalid int: "4.10.1"

### ISSUE THREAD

**Issue by inemnitable** [airbnb/lottie-android#559]
Reopen for #488 

java.lang.NumberFormatException: Invalid int: "4.10.1"
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:410)
at java.lang.Integer.parseInt(Integer.java:367)
at java.lang.Integer.parseInt(Integer.java:334)
at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:271)
at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:241)
at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:20)
at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(FileCompositionLoader.java:10)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by inemnitable** [comment]
Reposting my comment from #488:

I'm seeing a fair number of these crashes (~hundreds) in production on several devices. The affected devices include Hudl 2, ASUS MeMO Pad 7, Hi10 plus, and quite a few others. I'm only seeing crashes on OS version 5.1 and 5.1.1, but I'm not sure that that's related.

I dug a bit into the code and the only explanation I could come up with is that these few devices suffer from an incorrect implementation of String.split().

**Comment by gpeal** [comment]
@inemnitable Let me know if this fixes the issue. I just pushed a new 2.3.2-SNAPSHOT

**Comment by inemnitable** [comment]
@gpeal Thanks Gabriel. It could be a while before the new version makes it to production in our app and I don't have access to any affected devices to test. I'll update this thread when I know more.

**Comment by hongyangAndroid** [comment]
I also find some crashes about parse v("4.5.4") , can I change "4.5.4" to "4" to solve this temporarily until 2.5.0 Stable。
