### ISSUE TITLE
2.5.0-beta2 Crashing Android

### ISSUE THREAD

**Issue by tallesborges** [airbnb/lottie-android#590]
Hello the version 2.5.0-beta2 is crashing some android devices.
I was not able to reproduce the crash but I'm uploading a log image from fabric

<img width="1599" alt="screen shot 2018-01-10 at 12 55 39" src="https://user-images.githubusercontent.com/3486359/34783484-777728ea-f60a-11e7-8c72-d0c463977f49.png">

**Comment by gpeal** [comment]
@tallesborges Can you attach the animation that is crashing?

**Comment by gpeal** [comment]
@tallesborges bump

**Comment by tallesborges** [comment]
Sorry guys, I rollback to version 2.3.1 and this crash was fixed, I was not able to reproduce this error on my tests. 
I have a lot of animations on my app and I don't know which animation make it crash

**Comment by tallesborges** [comment]
`
                                                                     Process: com.opalastudios.pads, PID: 5884
                                                                     java.lang.NullPointerException
                                                                         at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:50)
                                                                         at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:47)
                                                                         at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                                                                         at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:47)
                                                                         at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                                                                         at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:223)
                                                                         at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:185)
                                                                         at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:472)
                                                                         at com.airbnb.lottie.LottieAnimationView$3.onCompositionLoaded(LottieAnimationView.java:416)
                                                                         at com.airbnb.lottie.model.JsonCompositionLoader.onPostExecute(JsonCompositionLoader.java:26)
                                                                         at com.airbnb.lottie.model.JsonCompositionLoader.onPostExecute(JsonCompositionLoader.java:10)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                         at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5590)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
                                                                         at dalvik.system.NativeStart.main(Native Method)

`
