### ISSUE TITLE
Crash when loading json on upgrade from 2.3.1 to 2.5.0-rc1  | Calling .createAnimation() on null 

### ISSUE THREAD

**Issue by rjaylwar** [airbnb/lottie-android#613]
I have some Json which plays perfectly fine on v2.3.1 but when I upgraded to v2.5.0-rc1 I get a warning in the logs and then it crashes.

[red_equalizer.json.zip](https://github.com/airbnb/lottie-android/files/1691298/red_equalizer.json.zip)

```
W/LOTTIE: Lottie doesn't support 3D layers.
W/LOTTIE: Layer has no transform property. You may be using an unsupported layer type such as a camera.
```

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableValue.createAnimation()' on a null object reference
      at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.<init>(TransformKeyframeAnimation.java:35)
      at com.airbnb.lottie.model.animatable.AnimatableTransform.createAnimation(AnimatableTransform.java:78)
      at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:71)
      at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:59)
      at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
      at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
      at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
      at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
      at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
      at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
      at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:225)
      at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:187)
      at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:472)
      at com.airbnb.lottie.LottieAnimationView$1.onCompositionLoaded(LottieAnimationView.java:78)
      at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
      at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
      at android.os.AsyncTask.finish(AsyncTask.java:695)
      at android.os.AsyncTask.-wrap1(Unknown Source:0)
      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
      at android.os.Handler.dispatchMessage(Handler.java:105)
      at android.os.Looper.loop(Looper.java:164)
      at android.app.ActivityThread.main(ActivityThread.java:6541)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

The animation was created using https://www.haiku.ai/ so I do not have an after-effects file

**Comment by gpeal** [comment]
I see. I just took a look and I switched to a streaming json parser in 2.5. Due to that, the "ty" type property **must** be the first key in each object. I'll email the Haiku dev and give him a heads up. I'm going to close this here though since there is nothing I can do about it.

In the mean time, go in your json and move an "ty" keys to the beginning of their respective objects.

**Comment by gpeal** [comment]
@zackbrown fyi
