### ISSUE TITLE
IndexOutOfBoundsException in interpolateBetween()

### ISSUE THREAD

**Issue by margauxdivernois** [airbnb/lottie-android#622]
Hello Lottie Team,

I currently have a crash in my application when setting a local animation file. Please note that the animation file is correctly working with the iOS Lottie SDK, and that the whole Android code is working with another animation.

```
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2 
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.airbnb.lottie.model.content.ShapeData.interpolateBetween(ShapeData.java:72)
at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:23)
at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:11)
at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:61)
at com.airbnb.lottie.animation.content.BaseStrokeContent.draw(BaseStrokeContent.java:160)
at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:36)
at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:300)
at android.widget.ImageView.onDraw(ImageView.java:1176)
at android.view.View.draw(View.java:15231)
...
```

After looking for a short while, it seems that your code in the function interpolateBetween() in ShapeData contains : 

```
if (!curves.isEmpty() && curves.size() != shapeData1.getCurves().size() && curves.size() != shapeData2.getCurves().size()) {
      throw new IllegalStateException("Curves must have the same number of control points. This: "
          + getCurves().size()
          + "\tShape 1: " + shapeData1.getCurves().size() + "\tShape 2: "
          + shapeData2.getCurves().size());
} else if (curves.isEmpty()) {
      for (int i = shapeData1.getCurves().size() - 1; i >= 0; i--) {
        curves.add(new CubicCurveData());
      }
}
```

In my case, curves.isEmpty() returns true, but shapeData1.getCurves().size() and shapeData2.getCurves.size() does not have the same value. As we skip the rest of the check in the if, we continue in the function. Next, the following is called, resulting in the crash. 

```
for (int i = curves.size() - 1; i >= 0; i--) {
      CubicCurveData curve1 = shapeData1.getCurves().get(i);
      CubicCurveData curve2 = shapeData2.getCurves().get(i);
      ...
}
```

I'm currently using `compile 'com.airbnb.android:lottie:2.5.0-rc1'`

Such crash should not happen, but it also means that the JSON file I am setting is incorrect. I would be interested in knowing what, in After Effect could create such problem and how to detect/correct it. I did read #197 but it seems like the JSON file was exported with the most recent Bodymovin version.

I will try to get the After Effect file to send it to the team by mail (but I need to wait for the authorization). Until then, any advice is welcomed.

Thank you

**Comment by gpeal** [comment]
@margauxdivernois Your animation is trying to animate from one shape to another that has a different number of bezier vertices. Lottie has no way of accurately animating between the shapes unless the vertices are 1:1. I would suggest re-working your animation such that all shapes have the same number of vertices throughout the animation.

If you are unsure which one is breaking, try exporting individual layers/shapes to figure it out with trial and error.
