### ISSUE TITLE
Crash in Animated Typography Sample

### ISSUE THREAD

**Issue by dbof10** [airbnb/lottie-android#63]
1. In the sample, I tried to input `Ç` to see how it animate. But it crashed with a logcat

`Caused by: java.io.FileNotFoundException: Mobilo/Ç.json
                                                                     at android.content.res.AssetManager.openAsset(Native Method)
                                                                     at android.content.res.AssetManager.open(AssetManager.java:363)
                                                                     at android.content.res.AssetManager.open(AssetManager.java:337)
                                                                     at com.airbnb.lottie.LottieComposition.fromAssetFileName(LottieComposition.java:50)
                                                                     at com.airbnb.lottie.samples.LottieFontViewGroup.onKeyUp(LottieFontViewGroup.java:188) `

  When I debug, character `Ç` and `C` have the same keycode which is `31`. Solution to this? 

2. I used the same keyboard as above with different languages input. It works when I input `A-Z` in `French, English`. However, it doesn't work in `Vietnamese` language when it is given `A-Z` characters. Any clues?

Thanks

**Comment by gpeal** [comment]
@dbof10 The app only contains animations for A-Z because it's just a tech demo :) I can fix the crash though.

**Comment by dbof10** [comment]
I know, like I said  character `Ç ` and `C` have the same keycode. I just want to know your solution.

**Comment by dbof10** [comment]
Thanks!!!
