### ISSUE TITLE
ConcurrentModificationException in BaseLottieAnimator since 2.5.0

### ISSUE THREAD

**Issue by Kevinrob** [airbnb/lottie-android#639]
Since I have updated to `2.5.0`. I have a `ConcurrentModificationException`.

```
02-19 14:11:04.556 23267-23267/xxx.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: xxx.xxx.xxx, PID: 23267
                                                                          java.util.ConcurrentModificationException
                                                                              at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
                                                                              at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
                                                                              at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:87)
                                                                              at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:98)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:655)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                              at android.os.Handler.handleCallback(Handler.java:790)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

In `BaseLottieAnimator`, maybe we can change `updateListeners` and `listeners` for a thread safe type? Like `CopyOnWriteArraySet` ?  

I can do a PR with pleasure 👍

**Comment by gpeal** [comment]
@Kevinrob I would accept a PR for this.
