### ISSUE TITLE
Android LottieAnimationView setAnimation crash

### ISSUE THREAD

**Issue by nijian81** [airbnb/lottie-android#653]
java.lang.IllegalStateException: Unable to find file loading_common.json
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java:115)
	at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:326)
	at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:299)
	at org.iqiyi.video.ui.PanelMsgLayerImplLoading.initUi(PanelMsgLayerImplLoading.java:151)
	at org.iqiyi.video.ui.PanelMsgLayerController.showMessageUi(PanelMsgLayerController.java:101)
	at org.iqiyi.video.ui.PanelMsgLayerController.showMessage(PanelMsgLayerController.java:78)
	at org.iqiyi.video.ui.QYPlayerViewController.initPlayerViewControllerHighPriority(QYPlayerViewController.java:543)
	at org.iqiyi.video.ui.QYPlayerViewController.onActivityCreate(QYPlayerViewController.java:1637)
	at org.iqiyi.video.ui.QYPlayerUIController.onCreate(QYPlayerUIController.java:93)
	at org.iqiyi.video.player.PlayerPresenter.onActivityResume(PlayerPresenter.java:320)
	at org.qiyi.video.embedded.player.EmbeddedPlayerUI.resumeMethod(EmbeddedPlayerUI.java:363)
	at org.qiyi.video.embedded.player.EmbeddedPlayerUI.doOnResume(EmbeddedPlayerUI.java:255)
	at org.qiyi.video.embedded.player.EmbeddedPlayerUI.onResume(EmbeddedPlayerUI.java:240)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2389)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1465)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1809)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2580)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2367)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:2322)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:2229)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:700)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:5671)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by: java.io.FileNotFoundException: loading_common.json
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:354)
	at android.content.res.AssetManager.open(AssetManager.java:328)
	at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java:113)
	... 30 more

**Comment by DrankoLQ** [comment]
Is your json file localized in the assets folder?

**Comment by gpeal** [comment]
@nijian81 Your json file should be in src/main/assets like @DrankoLQ indicated.
