### ISSUE TITLE
Errors on Android: Unexpected gradient length

### ISSUE THREAD

**Issue by mbc4srf** [airbnb/lottie-android#679]
I'm getting errors reported by my developer, and I don't know if they are critical or not. I have no idea what they mean nor how to fix them. They apparently only show up in Android, not iOS, and viewing it in the Lottie Previewer looks fine.

For example: 

[Beacon Searching 2.zip](https://github.com/airbnb/lottie-android/files/1808991/Beacon.Searching.2.zip)
> W/LOTTIE: Unexpected gradient length: 26. Expected 20. This may affect the appearance of the gradient. Make sure to save your After Effects file before exporting an animation with gradients.

What does "26" mean? How would I get it to be "20" ? If I calculate the length of the gradient based on the Start Point and End Point in After Effects, the length would be 2.02, so it must be something else?

Attached is my AE file. There is a USB adapter drawing with 10 gradients. I'm getting errors for 4 of them, not for the other 6, and I can't tell why--I didn't really do anything different with them.

**Comment by 275288698** [comment]
i got the same error when use gradient effect. here is stacktrace:

  java.lang.IllegalArgumentException: needs >= 2 number of colors
                                                                        at android.graphics.LinearGradient.<init>(LinearGradient.java:55)
                                                                        at com.airbnb.lottie.GradientStrokeContent.getLinearGradient(GradientStrokeContent.java:89)
                                                                        at com.airbnb.lottie.GradientStrokeContent.draw(GradientStrokeContent.java:57)
                                                                        at com.airbnb.lottie.ContentGroup.draw(ContentGroup.java:185)
                                                                        at com.airbnb.lottie.ContentGroup.draw(ContentGroup.java:185)
                                                                        at com.airbnb.lottie.ShapeLayer.drawLayer(ShapeLayer.java:24)
                                                                        at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:162)
                                                                        at com.airbnb.lottie.CompositionLayer.drawLayer(CompositionLayer.java:75)
                                                                        at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:162)
                                                                        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:283)

**Comment by gpeal** [comment]
@275288698 If it looks fine, you can ignore it. If it doesn't make sure to save the composition before exporting it with bodymovin.

**Comment by gpeal** [comment]
I'm removing this warning from future versions because it normally isn't problematic

**Comment by sumit-anantwar** [comment]
this isn't a warning, the app crashes with the exception
