### ISSUE TITLE
Setting min and max progress doesn't respect start frame and crashes

### ISSUE THREAD

**Issue by headsvk** [airbnb/lottie-android#703]
#628 **setProgres going to wrong frame when startFrame > 0** fixed only the setProgress function but not related setMinProgress, setMaxProgress and setMinAndMaxProgress setters.

This results in a crash when you try to use, e.g. setProgress(0.5f):
`java.lang.IllegalStateException: Frame must be [71,000000,23,000000]. It is 23,000000
at com.airbnb.lottie.utils.LottieValueAnimator.verifyFrame(LottieValueAnimator.java:230)
at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:112)`

**Comment by apuli** [comment]
Same error but with setMinAndMaxProgress and setMaxProgress...
@gpeal I checked out your code and you are not testing 1f as maxProgress, still crashing for me:

`java.lang.IllegalStateException: Frame must be [16.000000,0.000000]. It is 16.000000
        at com.airbnb.lottie.utils.LottieValueAnimator.verifyFrame(LottieValueAnimator.java:278)
        at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:115)`

**Comment by gpeal** [comment]
@apuli Could you put up a PR for this?
