### ISSUE TITLE
NumberFormatException on latest master

### ISSUE THREAD

**Issue by parthmg** [airbnb/lottie-android#727]
Stacktrace:
com.airbnb.lottie, PID: 3932
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NumberFormatException: 32.0000610351562
        at android.util.JsonReader.nextInt(JsonReader.java:522)
        at com.airbnb.lottie.parser.FontCharacterParser.parse(FontCharacterParser.java:33)
        at com.airbnb.lottie.parser.LottieCompositionParser.parseChars(LottieCompositionParser.java:201)
        at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:81)
        at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:276)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:22)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:12)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)

When I changed the number from 32.0000610351562 to 32 (and a few other Floats in json) the animation is working (althogh not as desired as a lot of things have changed).

One more thing is that same file works on iOS but fails on Android.

**Comment by parthmg** [comment]
@avadhbsd

**Comment by gpeal** [comment]
@parthmg @avadhbsd Can you attach the animation?

**Comment by parthmg** [comment]
@gpeal I have mailed the animation files to lottie@airbnb.com

**Comment by avadhbsd** [comment]
@parthmg I am not sure  if @gpeal can access the lottie@airbnb.com @gpeal please let me know if we shall attach the AE here at github?

**Comment by gpeal** [comment]
I received it. Thanks.

**Comment by parthmg** [comment]
@gpeal Any update?

**Comment by avadhbsd** [comment]
@parthmg can you please confirm if you can play another Lottie .json file that has float values? or that crashes it too?

**Comment by parthmg** [comment]
@avadhbsd Yes, Other files with float values work as expected. Even [material_wave_loading](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/res/raw/material_wave_loading.json) has float values and that works as expected. Have tried few others aswell.
