### ISSUE TITLE
java.lang.IllegalArgumentException: The Path must start at (0,0) and end at (1,1)

### ISSUE THREAD

**Issue by paulingit** [airbnb/lottie-android#733]
I am getting an IllegalArgumentException when using Lottie library on Android 7.

Lib Version: 2.5.1

Stack Trace: 
Caused by java.lang.IllegalArgumentException: The Path must start at (0,0) and end at (1,1)
       at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:164)
       at android.view.animation.PathInterpolator.initCubic(PathInterpolator.java:154)
       at android.view.animation.PathInterpolator.(PathInterpolator.java:85)
       at android.support.v4.view.animation.PathInterpolatorCompat.create(SourceFile:82)
       at com.airbnb.lottie.parser.KeyframeParser.parseKeyframe(SourceFile:130)
       at com.airbnb.lottie.parser.KeyframeParser.parse(SourceFile:58)
       at com.airbnb.lottie.parser.KeyframesParser.parse(SourceFile:40)
       at com.airbnb.lottie.parser.AnimatableValueParser.parse(SourceFile:87)
       at com.airbnb.lottie.parser.AnimatableValueParser.parseFloat(SourceFile:33)
       at com.airbnb.lottie.parser.ShapeTrimPathParser.parse(SourceFile:26)
       at com.airbnb.lottie.parser.ContentModelParser.parse(SourceFile:66)
       at com.airbnb.lottie.parser.LayerParser.parse(SourceFile:111)
       at com.airbnb.lottie.parser.LottieCompositionParser.parseAssets(SourceFile:142)
       at com.airbnb.lottie.parser.LottieCompositionParser.parse(SourceFile:75)
       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(SourceFile:276)
       at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(SourceFile:22)
       at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(SourceFile:12)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
I did a bit of research around this to find no proper solution. Highly appreciate if some help can be provided on this.

**Comment by gpeal** [comment]
@paulingit Can you attach your animation

**Comment by RadoVidjenGost** [comment]
I have tried the example at https://developer.android.com/training/animation/reposition-view with path, but it throws the same exception. Please help.

**Comment by zsoltk** [comment]
@gpeal +1 for this issue. Crashing on production with the same exception, and only on devices with Android 7+

**Comment by maxbaldrighi** [comment]
With the same stacktrace, happening also on **Samsung Galaxy J1 Ace** running Android **5.1.1**.
Lottie version: **2.5.1**

**Comment by gpeal** [comment]
@maxbaldrighi @zsoltk @RadoVidjenGost Can you attach your animations? I can't debug without that.

**Comment by maxbaldrighi** [comment]
@gpeal, sure!
could you share your email so that I can send it in private, please?

**Comment by scott-u-texas** [comment]
Was there a resolution to this issue? I tried the sample code as well and have the same issue.

**Comment by gpeal** [comment]
@maxbaldrighi @scott-u-texas You can create a minimal-repro animation (ie delete extra layers and simplify shapes) to repro it without uploading your animation

**Comment by gpeal** [comment]
@maxbaldrighi Are you still having an issue with this?

**Comment by zjupure** [comment]
how this issue fixed？I still according this problem on online products.
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:366)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.IllegalArgumentException: The Path must start at (0,0) and end at (1,1)
	at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:177)
	at android.view.animation.PathInterpolator.initCubic(PathInterpolator.java:167)
	at android.view.animation.PathInterpolator.<init>(PathInterpolator.java:95)
	at android.support.v4.view.animation.PathInterpolatorCompat.create(SourceFile:82)
	at com.airbnb.lottie.animation.Keyframe$Factory.newInstance(SourceFile:197)
	at com.airbnb.lottie.animation.keyframe.PathKeyframe$Factory.newInstance(SourceFile:48)
	at com.airbnb.lottie.model.animatable.AnimatablePathValue.<init>(SourceFile:47)
	at com.airbnb.lottie.model.animatable.AnimatablePathValue.createAnimatablePathOrSplitDimensionPath(SourceFile:23)
	at com.airbnb.lottie.model.animatable.AnimatableTransform$Factory.newInstance(SourceFile:120)
	at com.airbnb.lottie.model.layer.Layer$Factory.newInstance(SourceFile:271)
	at com.airbnb.lottie.LottieComposition$Factory.a(SourceFile:319)
	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(SourceFile:292)
	at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(SourceFile:252)
	at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(SourceFile:20)
	at com.airbnb.lottie.model.FileCompositionLoader.doInBackground(SourceFile:10)
	at android.os.AsyncTask$2.call(AsyncTask.java:345)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by gpeal** [comment]
@zjupure Can you attach an AEP file that reproduces this? You can attach it as a zip file
