### ISSUE TITLE
NullPointerException when I upgrade from 2.3.1 to 2.5.4

### ISSUE THREAD

**Issue by chenggoi** [airbnb/lottie-android#738]
This is Error Log : 
```
W System.err: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
W System.err:    at android.graphics.Path.setFillType(Path.java:260)
W System.err:    at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:62)
W System.err:    at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
W System.err:    at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
W System.err:    at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
W System.err:    at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
W System.err:    at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
W System.err:    at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
W System.err:    at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:225)
W System.err:    at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:187)
W System.err:    at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:472)
W System.err:    at com.airbnb.lottie.LottieAnimationView$3.onCompositionLoaded(LottieAnimationView.java:416)
W System.err:    at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
W System.err:    at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
W System.err:    at android.os.AsyncTask.finish(AsyncTask.java:695)
W System.err:    at android.os.AsyncTask.-wrap1(Unknown Source:0)
W System.err:    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W System.err:    at android.os.Handler.dispatchMessage(Handler.java:105)
W System.err:    at android.os.Looper.loop(Looper.java:164)
W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6809)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
And this is my AE file and JSON file
[anim.zip](https://github.com/airbnb/lottie-android/files/1946345/anim.zip)

Thank you.

**Comment by gpeal** [comment]
It seems to load fine for me on the latest master
![recording](https://user-images.githubusercontent.com/1307745/39712320-e4bd0522-5222-11e8-958a-34cec6b412d1.gif)

If it is still broken, reopen this with a repro project.
