### ISSUE TITLE
ArrayIndexOutOfBounds exception Lottie Layer Parser

### ISSUE THREAD

**Issue by AnkitAndroaid** [airbnb/lottie-android#761]
[Circle.json.zip](https://github.com/airbnb/lottie-android/files/1990556/Circle.json.zip)

I was trying to test Lottie Animation in my app. But Got this following error. I Used Lottie version 2.5.4 in Android app. 

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
                                                                  at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:99)
                                                                  at com.airbnb.lottie.parser.LottieCompositionParser.parseAssets(LottieCompositionParser.java:142)
                                                                  at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:75)
                                                                  at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:276)
                                                                  at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:22)
                                                                  at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:12)
                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by the-wr** [comment]
Same here. Not 100% reproducible.

```
                   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=61; index=61
                      at android.support.v4.util.ContainerHelpers.binarySearch(ContainerHelpers.java:51)
                      at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java:85)
                      at android.support.v4.util.SparseArrayCompat.get(SparseArrayCompat.java:76)
                      at com.airbnb.lottie.Keyframe$Factory.newInstance(Keyframe.java:153)
                      at com.airbnb.lottie.PathKeyframe$Factory.newInstance(PathKeyframe.java:26)
                      at com.airbnb.lottie.AnimatablePathValue.<init>(AnimatablePathValue.java:39)
                      at com.airbnb.lottie.AnimatablePathValue.createAnimatablePathOrSplitDimensionPath(AnimatablePathValue.java:15)
                      at com.airbnb.lottie.AnimatableTransform$Factory.newInstance(AnimatableTransform.java:108)
                      at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java:258)
                      at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:283)
                      at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:267)
                      at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226)
                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
```

**Comment by gpeal** [comment]
@AnkitAndroaid @the-wr Are there any trends in the devices? Manufacturers? OS versions?

**Comment by the-wr** [comment]
@gpeal Upgrading to the latest release fixed the issue for me. Sorry for false alarm.
