### ISSUE TITLE
Crash Samsung Galaxy J7

### ISSUE THREAD

**Issue by myfknoll** [airbnb/lottie-android#769]
We have issues running lottie on an Samsung Galaxy J5, the file cannot be found

# Date: 2018-05-11T07:34:15Z
# OS Version: 7.0
# Device: Galaxy J7(2016)
# RAM Free: 18.1%
# Disk Free: 7.4%

Caused by java.io.FileNotFoundException: filename.json
       at android.content.res.AssetManager.openAsset(AssetManager.java)
       at android.content.res.AssetManager.open(AssetManager.java:423)
       at android.content.res.AssetManager.open(AssetManager.java:397)
       at com.airbnb.lottie.LottieComposition$Factory.fromAssetFileName(LottieComposition.java:192)
       at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:405)
       at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:377)
       at com.airbnb.lottie.LottieAnimationView.onRestoreInstanceState(LottieAnimationView.java:230)
       at android.view.View.dispatchRestoreInstanceState(View.java:16960)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3478)
       at android.view.View.restoreHierarchyState(View.java:16938)
       at android.support.v4.app.Fragment.restoreViewState(Fragment.java:396)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
       at android.app.Activity.performStart(Activity.java:6973)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

I cannot immagine why it crashes there, but is there any possibility to AVOID crashes there? And maybe only log this issue, maybe via a callback?

**Comment by gpeal** [comment]
@myfknoll This isn't a Lottie issue. It appears as if the file doesn't exist within your app for those phones. Lottie just passes through to Android to handle that.
