### ISSUE TITLE
Unable to open asset.  java.io.FileNotFoundException: open/img_0.png

### ISSUE THREAD

**Issue by kinber95** [airbnb/lottie-android#771]
Hello,

I get this error then I wan't to animate my json file:

```
`05-15 00:58:16.485 14636-14636/de.app.haveltec.ilockit W/LOTTIE: Unable to open asset.
    java.io.FileNotFoundException: open/img_2.png
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:374)
        at android.content.res.AssetManager.open(AssetManager.java:348)
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:84)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:800)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.getBounds(ImageLayer.java:52)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:196)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:311)
        at android.widget.ImageView.onDraw(ImageView.java:1367)
        at android.view.View.draw(View.java:19192)
        at android.view.View.buildDrawingCacheImpl(View.java:18440)
        at android.view.View.buildDrawingCache(View.java:18300)
        at android.view.View.updateDisplayListIfDirty(View.java:18119)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`
```

I loading the animation via xml : 

```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/activity_home_lock_state_iv"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="24dp"
        android:layout_marginEnd="24dp"
        android:layout_marginStart="24dp"
        android:layout_marginTop="24dp"
        app:layout_constraintBottom_toTopOf="@+id/home_activity_lock_controll_btn"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/home_activity_battery_iv"
        app:lottie_imageAssetsFolder="open"
        app:lottie_rawRes="@raw/lock_open"
        app:lottie_autoPlay="true"/>
```

The json file is in my res/raw folder and the png files for the json are in the src/main/assets/open folder. This is how my json looks : http://app.ilockit.bike/data.json. 

I search for a while in the internet, but no solution helps...

**Comment by RISHABHPATNI1108** [comment]
Why this issue is closed
I am having the same issue and the link provided is broken,

**Comment by gpeal** [comment]
@RISHABHPATNI1108 http://airbnb.io/lottie/#/android?id=images
