### ISSUE TITLE
java.lang.NullPointerException when i load full screen animation

### ISSUE THREAD

**Issue by georgeyang1024** [airbnb/lottie-android#772]
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
                                                                         at android.graphics.Path.setFillType(Path.java:240)
                                                                         at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:62)
                                                                         at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
                                                                         at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                                                                         at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
                                                                         at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
                                                                         at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                                                                         at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
                                                                         at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
                                                                         at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
                                                                         at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                                                                         at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
                                                                         at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
                                                                         at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:484)
                                                                         at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java:377)
                                                                         at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
                                                                         at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                         at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:157)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5571)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by gpeal** [comment]
@georgeyang1024 Please attach your aep file (zipped)

**Comment by georgeyang1024** [comment]
[sign.zip](https://github.com/airbnb/lottie-android/files/2007254/sign.zip)
please check

**Comment by w401634075** [comment]
do this can fix this bug
in this lottie\src\main\java\com\airbnb\lottie\parser\GradientFillParser.java class
change     Path.FillType fillType = null;    to   Path.FillType fillType = Path.FillType.EVEN_ODD;
sug:     change    GradientType gradientType = null;   to    GradientType gradientType = GradientType.Radial;

**Comment by gpeal** [comment]
@georgeyang1024 The animation you attached is full of images that you didn't include.

Can you create a simple sample that reproduces this?

**Comment by georgeyang1024** [comment]
@gpeal 
 i try to remove the full image layer of the gradient,it work!
