### ISSUE TITLE
please help me what's hapen

### ISSUE THREAD

**Issue by huangyulai** [airbnb/lottie-android#776]
05-16 10:13:08.356 24871-24871/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xiangbo.xld.com.mytencentview, PID: 24871
    java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
        at android.graphics.Path.setFillType(Path.java:255)
        at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:62)
        at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:488)
        at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java:381)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
        at android.os.AsyncTask.finish(AsyncTask.java:660)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by huangyulai** [comment]
How to solve this problem?
