### ISSUE TITLE
Crash App, If display "Featured Lottiefiles" in "Recent menu" in scroll down

### ISSUE THREAD

**Issue by rezamusic881** [airbnb/lottie-android#779]
#### Expected behavior
Supposedly, The "Lottiefiles Feature" feature in the "Recent" menu does not cause the Crash application when scrolling down.

#### Actual behavior
When I go to "Lottiefiles Feature" in the "Current" menu causes the Crash app when scrolling down.

#### How to reproduce
1. Instal App [here](  https://play.google.com/store/apps/details?id=com.airbnb.lottie)
2. Run the app
3. Go to "Lottiefiles feature"
4. Click on the "Recent" tab, Wait Loading until the "Recent" menu shows something.
5. Then scrowl down, Application will Crash.

***
***

* Browser : Redmi Note 5A
* System Operating : 7.1.0 Nougat
* App Version : 2.5.5

#### Recording Of The Bug
https://youtu.be/KWkwwu-tr5E

#### Logcat
```
--------- beginning of crash
05-19 23:04:21.468  5703  5703 E AndroidRuntime: FATAL EXCEPTION: main
05-19 23:04:21.468  5703  5703 E AndroidRuntime: Process: com.airbnb.lottie, PID: 5703
05-19 23:04:21.468  5703  5703 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown color
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.graphics.Color.parseColor(Color.java:154)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.lottie.samples.model.AnimationData.bgColorInt(AnimationData.kt:38)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.lottie.samples.AnimationItemView.setAnimationData(AnimationItemView.kt:30)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.lottie.samples.AnimationItemViewModel_.bind(AnimationItemViewModel_.java:81)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.lottie.samples.AnimationItemViewModel_.bind(AnimationItemViewModel_.java:30)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:57)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:96)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.epoxy.EpoxyControllerAdapter.onBindViewHolder(EpoxyControllerAdapter.java:10)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:14)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-19 23:04:21.468  5703  5703 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

#### Proof Of Work Done
[Submit in github](http://www.github.com/rezamusic881)

**Comment by gpeal** [comment]
This is now fixed
