### ISSUE TITLE
App crash- font not found in asset folder

### ISSUE THREAD

**Issue by bdndreams** [airbnb/lottie-android#793]
Application is crashed, I have view pager and add LottianimationView in each page, but when i scroll on view pager application get crashed, on random pages.

AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.lifescan.reveal.adhoctest, PID: 26977
                                                   java.lang.RuntimeException: Font asset not found fonts/Museo Sans.ttf
                                                       at android.graphics.Typeface.createFromAsset(Typeface.java:274)
                                                       at com.airbnb.lottie.manager.FontAssetManager.getFontFamily(FontAssetManager.java:86)
                                                       at com.airbnb.lottie.manager.FontAssetManager.getTypeface(FontAssetManager.java:60)
                                                       at com.airbnb.lottie.LottieDrawable.getTypeface(LottieDrawable.java:827)
                                                       at com.airbnb.lottie.model.layer.TextLayer.drawTextWithFont(TextLayer.java:161)
                                                       at com.airbnb.lottie.model.layer.TextLayer.drawLayer(TextLayer.java:125)
                                                       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
                                                       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
                                                       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
                                                       at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
                                                       at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
                                                       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:311)
                                                       at android.widget.ImageView.onDraw(ImageView.java:1270)
                                                       at android.view.View.draw(View.java:17469)
                                                       at android.view.View.buildDrawingCacheImpl(View.java:16764)
                                                       at android.view.View.buildDrawingCache(View.java:16625)
                                                       at android.view.View.draw(View.java:17231)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16459)
                                                       at droid.app.ActivityThread.main(ActivityThread.java:7229)

**Comment by D4rkness** [comment]
How have you solved the problem, because i'm can't work it out ?

**Comment by gabriellferreira** [comment]
You just have to manually copy your font (ttf format) to 'assets/font'. And of course properly specify it in the animation export process.

**Comment by gabriellferreira** [comment]
> How have you solved the problem, because i'm can't work it out ?

You just have to manually copy your font (ttf format) to 'assets/font'. And of course properly specify it in the animation export process.
