### ISSUE TITLE
java.lang.NullPointerException when opening file for preview

### ISSUE THREAD

**Issue by anthonyfr** [airbnb/lottie-android#851]
When I open the Sample App preview -> Open a file and select my [json file,](https://gist.github.com/anthonyfr/92cdd6658d0f090377949a6abb7f95e0#file-animation-json) the app crashes with a NullPointerException. 
I see from the logs and the code that when the json file has a "shape" without a name "nm", it passes a null String to KeyPath, causing the crash when calling .equals.  

The crash logs are:
`07-24 21:58:40.147 28074-28074/com.airbnb.lottie E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie, PID: 28074
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.airbnb.lottie.model.KeyPath.isContainer(KeyPath.java:199)
        at com.airbnb.lottie.model.KeyPath.matches(KeyPath.java:101)
        at com.airbnb.lottie.animation.content.ContentGroup.resolveKeyPath(ContentGroup.java:192)
        at com.airbnb.lottie.animation.content.ContentGroup.resolveKeyPath(ContentGroup.java:210)
        at com.airbnb.lottie.model.layer.ShapeLayer.resolveChildKeyPath(ShapeLayer.java:41)
        at com.airbnb.lottie.model.layer.BaseLayer.resolveKeyPath(BaseLayer.java:472)
        at com.airbnb.lottie.model.layer.CompositionLayer.resolveChildKeyPath(CompositionLayer.java:184)
        at com.airbnb.lottie.model.layer.BaseLayer.resolveKeyPath(BaseLayer.java:472)
        at com.airbnb.lottie.LottieDrawable.resolveKeyPath(LottieDrawable.java:753)
        at com.airbnb.lottie.LottieAnimationView.resolveKeyPath(LottieAnimationView.java:742)
        at com.airbnb.lottie.samples.PlayerFragment$onViewCreated$32.buildModels(PlayerFragment.kt:334)
        at com.airbnb.epoxy.EpoxyRecyclerView$2.buildModels(EpoxyRecyclerView.java:426)
        at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:179)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)`

**Comment by anthonyfr** [comment]
@gpeal The designer made the animation on Haiku. I will send the files I get by email.

**Comment by gpeal** [comment]
@anthonyfr We don't officially support Haiku but it looks like they are exporting shapes that change their number of vertices which Lottie doesn't support. Please file an issue with them.
