### ISSUE TITLE
java.lang.IllegalStateException: Cannot invoke setValue on a background thread

### ISSUE THREAD

**Issue by bkhezry** [airbnb/lottie-android#867]
I just run sample and get this error for each item click:

`
08-05 02:46:33.045 25265-25320/com.airbnb.lottie E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.airbnb.lottie, PID: 25265
    java.lang.IllegalStateException: Cannot invoke setValue on a background thread
        at android.arch.lifecycle.LiveData.assertMainThread(LiveData.java:435)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:279)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.airbnb.lottie.samples.PlayerViewModel$handleJsonResponse$1.onResult(PlayerViewModel.kt:89)
        at com.airbnb.lottie.samples.PlayerViewModel$handleJsonResponse$1.onResult(PlayerViewModel.kt:28)
        at com.airbnb.lottie.LottieTask.addListener(LottieTask.java:72)
        at com.airbnb.lottie.samples.PlayerViewModel.handleJsonResponse(PlayerViewModel.kt:88)
        at com.airbnb.lottie.samples.PlayerViewModel.access$handleJsonResponse(PlayerViewModel.kt:28)
        at com.airbnb.lottie.samples.PlayerViewModel$fetchAnimationByUrl$2.invoke(PlayerViewModel.kt:75)
        at com.airbnb.lottie.samples.PlayerViewModel$fetchAnimationByUrl$2.invoke(PlayerViewModel.kt:28)
        at com.airbnb.lottie.samples.OkHttpCallback.onResponse(OkHttpCallback.kt:12)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
`

**Comment by bkhezry** [comment]
error just change to
`
08-05 10:09:20.415 3705-3705/com.airbnb.lottie E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie, PID: 3705
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1166)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:163)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okhttp3.internal.Util.skipAll(Util.java:175)
        at okhttp3.internal.Util.discard(Util.java:157)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.close(Http1Codec.java:424)
        at okio.RealBufferedSource.close(RealBufferedSource.java:469)
        at okhttp3.internal.Util.closeQuietly(Util.java:110)
        at okhttp3.ResponseBody.string(ResponseBody.java:177)
        at com.airbnb.lottie.samples.PlayerViewModel$onResponse$1.run(PlayerViewModel.kt:80)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5476)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)

`
