### ISSUE TITLE
[Bug]When application closed, open again will crash

### ISSUE THREAD

**Issue by kenneth2008** [airbnb/lottie-android#900]
The application start like this:
SplashScreenActivity-> LoginActivity(Animation in this activity)

Dismiss the application at LoginActivity can reproduce the problem.
- the application must dismiss by Activity.finish( ) command
- it will not happened if dismiss at Register page or others
- it will not happened if clean every thing on Android application manager

> Version:
> com.airbnb.android:lottie:2.6.0-beta19
> 

json file:
`{"v":"5.1.20","fr":24,"ip":0,"op":960,"w":1080,"h":1920,"nm":"belchar_login","ddd":0,"assets":[{"id":"image_0","w":3200,"h":1500,"u":"images/","p":"img_0.png","e":0},{"id":"image_1","w":1080,"h":1920,"u":"images/","p":"img_1.jpg","e":0}],"layers":[{"ddd":0,"ind":1,"ty":2,"nm":"circle_00000.tif","cl":"tif","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[-3500,472,0],"e":[-92,472,0],"to":[568,0,0],"ti":[-568,0,0]},{"t":959}],"ix":2},"a":{"a":0,"k":[1600,750,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":981,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":2,"nm":"circle_00000.tif","cl":"tif","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[-92,472,0],"e":[2862,472,0],"to":[492.333343505859,0,0],"ti":[-492.333343505859,0,0]},{"t":959}],"ix":2},"a":{"a":0,"k":[1600,750,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":981,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":2,"nm":"leave_background.jpg","cl":"jpg","refId":"image_1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[540,960,0],"ix":2},"a":{"a":0,"k":[540,960,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":986,"st":0,"bm":0}],"markers":[]}
`
```
Error message:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.airbnb.lottie.LottieImageAsset.getBitmap()' on a null object reference
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:69)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:835)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:32)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:315)
        at android.widget.ImageView.onDraw(ImageView.java:1286)
        at android.view.View.draw(View.java:17096)
        at android.view.View.buildDrawingCacheImpl(View.java:16385)
        at android.view.View.buildDrawingCache(View.java:16246)
        at android.view.View.draw(View.java:16854)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)


```

**Comment by kenneth2008** [comment]
```
private fun setupAnimation() {
        animation_view.imageAssetsFolder = "images/"
        animation_view.setAnimation("login_bg_v2.json")
        animation_view.repeatCount = LottieDrawable.INFINITE
        animation_view.playAnimation()
}
```
Above is how I setup in activity

 ```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        app:lottie_autoPlay="true"
        app:lottie_fileName="login_bg_v2.json"
        app:lottie_loop="true"
        app:lottie_imageAssetsFolder="images/"
        android:scaleType="centerCrop" />
```
In XML file

Besides, my assets has a file names login_bg_v2.json,  and directory images.
![test](https://user-images.githubusercontent.com/5935483/44324021-c60b4380-a486-11e8-838e-f2de1a78f1ba.png)

**Comment by vivekjha1990** [comment]
We are getting the same crash on a lottie containing only shape layers.

**Comment by martin25tung** [comment]
I have the same problem.
when I open activity again 
it always crash like this

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.airbnb.lottie.LottieImageAsset.getBitmap()' on a null object reference
        at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:69)
        at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:835)
        at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:68)
        at com.airbnb.lottie.model.layer.ImageLayer.getBounds(ImageLayer.java:52)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:209)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:315)
        at android.widget.ImageView.onDraw(ImageView.java:1367)

**Comment by janehoo** [comment]
I have the same problem.
when I open activity first,
everything is ok.
but When I click the back button, 
then, it will crash when I enter again.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.airbnb.lottie.LottieImageAsset.getBitmap()' on a null object reference

**Comment by dinorahtovar** [comment]
Hello, one question, Is this bug solved and merged? We are still facing this over DialogFragments 
Using: 
`
    implementation 'com.airbnb.android:lottie:2.6.0-beta19'
`

Every time we try to open the same dialog from a RecyclerView it crash

**Comment by pankaj89** [comment]
Hello, 
This is resolved in the latest version but my project is not androidx compatible so i used

``` implementation 'com.airbnb.android:lottie:2.7.0' ```

It worked
