### ISSUE TITLE
layerName can be NULL

### ISSUE THREAD

**Issue by OleksandrKucherenko** [airbnb/lottie-android#951]
https://github.com/airbnb/lottie-android/blob/c567cbb970b747ce29a8f46ca115934a4a2aa9e3/lottie/src/main/java/com/airbnb/lottie/parser/LayerParser.java#L216

Example of the animated icon that make a problem for parser: 
```json
{"fr":25,"ip":0,"op":234,"w":1920,"h":1920,"ddd":0,"assets":[{"id":"comp_0","layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 1","td":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[960,960,0]},"a":{"a":0,"k":[0,0,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":0,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-730,-452],[-54,-196],[58,-200],[708,-456]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-366.439,-745.423],[-33.904,-198.364],[34.357,-197.636],[368.535,-770.784]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":8,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-366.439,-745.423],[-33.904,-198.364],[34.357,-197.636],[368.535,-770.784]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-248.582,-788.455],[-29.46,-198.887],[29.129,-197.113],[263.843,-809.235]],"c":true}]},{"i":{"x":0.278,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p278_1_0p167_0p167","t":10,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-248.582,-788.455],[-29.46,-198.887],[29.129,-197.113],[263.843,-809.235]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-54,-830],[-20,-200],[18,-196],[66,-816]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":20,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-54,-830],[-20,-200],[18,-196],[66,-816]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-54,-830],[-20,-200],[18,-196],[66,-816]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.179,"y":0},"n":"0p833_0p833_0p179_0","t":25,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-54,-830],[-20,-200],[18,-196],[66,-816]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-176.226,-788.43],[-24.639,-199.454],[23.457,-196.546],[183.587,-800.886]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":29,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-176.226,-788.43],[-24.639,-199.454],[23.457,-196.546],[183.587,-800.886]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-455.679,-713.108],[-36.274,-198.085],[37.146,-197.915],[453.405,-716.212]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":35,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-455.679,-713.108],[-36.274,-198.085],[37.146,-197.915],[453.405,-716.212]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-586.998,-624.283],[-42.304,-197.376],[44.24,-198.624],[592.014,-643.693]],"c":true}]},{"i":{"x":0.383,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p383_1_0p167_0p167","t":39,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-586.998,-624.283],[-42.304,-197.376],[44.24,-198.624],[592.014,-643.693]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-2,-958],[-730,-452],[-54,-196],[58,-200],[708,-456]],"c":true}]},{"t":55}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","c":{"a":0,"k":[0.0419477,0.6028952,0,1]},"o":{"a":0,"k":100},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group"}],"ip":0,"op":125,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":4,"nm":"Accordion 2","tt":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":-68.7},"p":{"a":0,"k":[960,952,0]},"a":{"a":0,"k":[540,540,0]},"s":{"a":0,"k":[140,140,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[33.287,13.648],[9.33,10.144]],"o":[[-13.767,0.674],[-33.268,-13.641],[0,0]],"v":[[63.464,24.473],[-6.344,13.922],[-63.465,-27.57]],"c":false}},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"st","c":{"a":0,"k":[1,1,1,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":32.357},"lc":2,"lj":2,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"tr","p":{"a":0,"k":[715.84,102.595],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7}
```

exception callstack:
```
Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
        at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:216)
        at com.airbnb.lottie.parser.LottieCompositionParser.parseLayers(LottieCompositionParser.java:104)
        at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:72)
        at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:276)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:22)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.doInBackground(AsyncCompositionLoader.java:12) 
```

**Comment by gpeal** [comment]
@OleksandrKucherenko Was this exported with after effects?

**Comment by OleksandrKucherenko** [comment]
Yes, and after that was used some kind of open source size optimization tools... will try to find the name of it. anyway, the tool simply removes non-critical for after effect attributes from JSON.

**Comment by OleksandrKucherenko** [comment]
👍
