### ISSUE TITLE
Unable to parse composition

### ISSUE THREAD

**Issue by casolorz** [airbnb/lottie-android#956]
My graphics designer generated a lottie file using haiku.app. The json file seems to work here https://www.lottiefiles.com/preview but when I put it on Android I get an error. I tried other lottie files from the web and they worked fine on Android so I'm guessing my implementation is fine, I mean it is just pretty much a copy paste so I don't know what could be wrong with it. 

This is the stack trace:

```
java.lang.IllegalStateException: Unable to parse composition
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:77)
        at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:75)
        at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
        at com.airbnb.lottie.LottieTask.access$300(LottieTask.java:26)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NumberFormatException: 52.499
        at android.util.JsonReader.nextInt(JsonReader.java:522)
        at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:46)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:226)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:161)
        at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:155)
        at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:127)
        at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:114)
        at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:112)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

This is the json. 
`{"ip":0,"fr":60,"v":"5.1.20","assets":[],"layers":[{"ty":4,"nm":"play","ip":0,"st":0,"ind":3,"hix":2,"ks":{"o":{"a":0,"k":100},"or":{"a":0,"k":[0,0,0]},"a":{"a":0,"k":[12,12,0]},"p":{"s":true,"x":{"a":1,"k":[{"t":0,"s":[20],"e":[20],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":119}]},"y":{"a":1,"k":[{"t":0,"s":[21],"e":[21],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":119}]}},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"s":{"a":0,"k":[100,100,100]}},"shapes":[{"ty":"gr","nm":"play shape group","it":[{"ty":"sh","ks":{"a":0,"k":{"c":true,"v":[[10,14.5],[10,5.5],[16,10]],"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]]}}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":100},"r":1,"c":{"a":0,"k":[0,0,0,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0}}]},{"ty":"gr","nm":"play shape group","it":[{"ty":"sh","ks":{"a":0,"k":{"c":true,"v":[[10,14.5],[10,5.5],[16,10]],"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]]}}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":100},"r":1,"c":{"a":0,"k":[0,0,0,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0}}]},{"ty":"gr","nm":"play shape group","it":[{"ty":"sh","ks":{"a":0,"k":{"c":true,"v":[[12,0],[2,10],[12,20],[22,10]],"i":[[5.52,0],[0,-5.52],[-5.52,0],[0,5.52]],"o":[[-5.52,0],[0,5.52],[5.52,0],[0,-5.52]]}}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":100},"r":1,"c":{"a":0,"k":[1,0.7568627450980392,0.027450980392156862,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0}}]},{"ty":"gr","nm":"play shape group","it":[{"ty":"rc","s":{"a":0,"k":[24,24]},"r":{"a":0,"k":0},"p":{"a":0,"k":[12,12]}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":0},"r":1,"c":{"a":0,"k":[0,0,0,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,-2]},"r":{"a":0,"k":0}}]}],"op":119},{"ty":4,"nm":"circle","ip":0,"st":0,"ind":2,"hix":1,"ks":{"o":{"a":1,"k":[{"t":0,"s":[100],"e":[100],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":46,"s":[100],"e":[0],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":119}]},"or":{"a":0,"k":[0,0,0]},"a":{"a":0,"k":[10,10,0]},"p":{"s":true,"x":{"a":1,"k":[{"t":0,"s":[20],"e":[20],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":119}]},"y":{"a":1,"k":[{"t":0,"s":[20],"e":[20],"i":{"x":[1],"y":[1]},"o":{"x":[0],"y":[0]}},{"t":119}]}},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"s":{"a":1,"k":[{"t":0,"s":[80,80],"e":[200,200],"i":{"x":[0.15,0.15],"y":[0.86,0.86]},"o":{"x":[0.785,0.785],"y":[0.135,0.135]}},{"t":119}]}},"shapes":[{"ty":"gr","nm":"circle shape group","it":[{"ty":"el","p":{"a":0,"k":[10,10]},"s":{"a":0,"k":[20,20]}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":100},"r":1,"c":{"a":0,"k":[1,1,1,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0}}]},{"ty":"gr","nm":"circle shape group","it":[{"ty":"rc","s":{"a":0,"k":[20,20]},"r":{"a":0,"k":0},"p":{"a":0,"k":[10,10]}},{"ty":"st","o":{"a":0,"k":0},"w":{"a":0,"k":0},"c":{"a":0,"k":[0,0,0,0]},"lc":3,"lj":1},{"ty":"fl","o":{"a":0,"k":0},"r":1,"c":{"a":0,"k":[0,0,0,1]}},{"ty":"tr","o":{"a":0,"k":100},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[100,100]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0}}]}],"op":119}],"op":119,"w":52.499,"h":53.067}`

And this is my xml:
 ```
<com.airbnb.lottie.LottieAnimationView
                            android:id="@+id/someid"
                            android:layout_width="48dp"
                            android:layout_height="48dp"
                            app:lottie_rawRes="@raw/json_file"
                         />
```

And like I said, if I replace the json with others that I have found on the web then it works just fine.

**Comment by casolorz** [comment]
Just realized it is doing `nextInt` and my value for `width` is not an `int`. Is this something I should report to haiku.app then?

**Comment by gpeal** [comment]
@casolorz Yes, this is probably Haiku specific. Could you file a bug there. I would like to avoid making specific changes for non-After Effects platforms if possible. If they have a good reason for making width/height a non-int, have them open a subsequent issue here.
