### ISSUE TITLE
NullPointException caused by setAnimation()

### ISSUE THREAD

**Issue by yanbinbin** [airbnb/lottie-android#989]
5 Caused by:
--
6 java.lang.NullPointerException:Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
7 android.view.View.setLayerType(View.java:17991)
8 com.airbnb.lottie.LottieAnimationView.u(LottieAnimationView.java:882)
9 com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:489)
10 com.airbnb.lottie.LottieAnimationView.a(LottieAnimationView.java:411)
11 com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:393)

**Comment by yanbinbin** [comment]
Anyone alse has the exception ?

**Comment by yanbinbin** [comment]
version 2.5.2_0

**Comment by gpeal** [comment]
@yanbinbin Can you start by updating lottie to 2.7.0 (non-androidx) or 2.8.0 (androidx)?

**Comment by sixiangjun** [comment]
I also have the exception eventhought I update lottie to 2.7.0

**Comment by gpeal** [comment]
@sixiangjun Can you attach the animation?

**Comment by gpeal** [comment]
@sixiangjun That stack trace is obfuscated. Do you have one that is not?

**Comment by zhangxy1219** [comment]
Also have the same exception, here is the stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
at android.view.View.setLayerType(View.java:17991)
at com.airbnb.lottie.LottieAnimationView.enableOrDisableHardwareLayer(LottieAnimationView.java:727)
at com.airbnb.lottie.LottieAnimationView.cancelAnimation(LottieAnimationView.java:680)
```

**Comment by gpeal** [comment]
@yanbinbin @zhangxy1219 Does this only occur on specific phones or OS versions?

**Comment by gpeal** [comment]
String.contains is not called from View.setLayerType on AOSP.

**Comment by yanbinbin** [comment]
> @yanbinbin @zhangxy1219 Does this only occur on specific phones or OS versions?

yeah, on vivo 8.1.0

**Comment by gpeal** [comment]
@yanbinbin Does it only happen on that device?

**Comment by yanbinbin** [comment]
No,  not only this device.

**Comment by gpeal** [comment]
@yanbinbin Are there any patterns to the devices (specific manufacturers, OS versions, etc)?

**Comment by gpeal** [comment]
@yanbinbin @zhangxy1219 @sixiangjun Are you still seeing this? The line number doesn't match up for the 8.1.0 source code in View.java line 17991.

**Comment by gpeal** [comment]
Closing this due to inactivity and because it hasn't been verified to happen on 3.0+. Feel free to reopen with more information and repro steps.
